### PR TITLE
Use git describe as the BUILD_DESC in build.h, this way we git the ta…

### PR DESCRIPTION
**Pull request by jonspock**
…g and the number of commits since that tag

### CODE REVIEW

**Comment by jonspock** [comment]
Use may have to run "genbuild.sh" manually the 1st time if you get a compiler error

**Comment by jonspock** [comment]
Dependency issue fixed

**Comment by rejectedpromise** [comment]
utACK
needs squash :wink:

**Comment by jonspock** [comment]
squashed now

**Comment by Fuzzbawls** [comment]
Two different local/native build cases resulted in a very dirty version string on the Splash screen, about page, and Information UI tab. Both of these builds mimicked what a self-compiler would do when compiling the `master` branch or a specific PR when testing proposed changes.

screen shot 2017-10-26 at 7 42 40 pm

Without this PR, this is what the version string looks like when doing the same compile against `master` or a PR test build. Note that the `-dirty` suffix is because I'm testing a different PR without committing it's changes.

screen shot 2017-10-26 at 10 28 06 pm

I think this alone is enough to NACK in it's current state for the time being. I'm not seeing much of an improvement when compiling against a tagged commit, as it stands `CLIENT_VERSION_IS_RELEASE` boolean changes are rather infrequent and manually doing them is a trivial process that is already described in the release-process documentation. I am, however, seeing a regression in non-release builds that are commonplace for testers.

I'm also not seeing anything regarding the number of commits since the last tag that was mentioned in slack. While that may be of substantial use/benefit on it's own, it doesn't seem to be included yet.

**Comment by jonspock** [comment]
No, that is the expected and desired behavior. It will only be as good as our tags
The number of commits is there 4934 since the v0.11.0.7 tag. That is why we should have more recent tags on Master.  Even if you don't want to use tags on master for releases it it useful to know when we branch off for a release and that should be tagged so the history will be there if those branches are ever deleted. Like I said this helps for High Sierra DMG packaging because I've already setup this flow and don't want to go backward and undo it if it means extra steps each time

**Pull request closed without merging**
