### PR TITLE
[RPC][MN] Serialize in ADDRV2 for TorV3 in RPC's

### PR DESCRIPTION
**Pull request by Liquid369**
With some work being done in PIVX-Labs by @Duddino we noticed that the RPC's for decoding and creating master node broadcasts are in Pre-BIP 155 format or AddrV1 serialization.
In order for us to create support for Tor master nodes in MPW, we need these RPC's to be able to serialize a TorV3 address.

There's a few caveats for decoding that there may be other solutions provided by someone else, but for now since receiving the stream, we cannot tell if its PreBIP155 or not, so we unserialize by AddrV1 first and if it fails, we check and attempt AddrV2.

### CODE REVIEW

**Review by Duddino — APPROVED** [review]
The PR works, unless there was a bip155 serialized address of length 13, which doesn't seem to be the case. Maybe instead of detecting the type "automatically", a flag can be added to the RPC?
tACK 6d3d5354e44d347670ad5b32249ff8d6a80e19a7 because the above is a really small nitpick

**Comment by Liquid369** [comment]
I did think of trying to add a flag, but with the process in the RPCs and with these having the possibility of being done on separate daemons, the flag would not help us too much unless we are adding to the stream and can use that as an identifier for it. I did a fair bit of comparison between the encoded broadcasts between addrv1/2 and I haven't seen any signifiers for it, to make that change worth it/usable.

Or with the flag, we would again need to have some insight into the hex string provided to us, but I can spend some more time to see if I overlooked anything.

**Review by panleone — APPROVED** [review]
tACK 6d3d5354e44d347670ad5b32249ff8d6a80e19a7 tested on Duddino's node throught MPW, works as intended.
Still for v6.0 I would really like to see v1 serialization being completely removed from the code

**Comment by Liquid369** [comment]
> tACK [6d3d535](https://github.com/PIVX-Project/PIVX/commit/6d3d5354e44d347670ad5b32249ff8d6a80e19a7) tested on Duddino's node throught MPW, works as intended.
> Still for v6.0 I would really like to see v1 serialization being completely removed from the code

I agree and am looking into it. Have to do a fair bit of testing, for sanity of all types. But we have to continue to discuss a small cut-off so we can do the interim release possibly. Then the following can be bundled into 6.0 for the removal of v1 serialization.

**Review by Fuzzbawls — APPROVED** [review]
ACK 6d3d5354e44d347670ad5b32249ff8d6a80e19a7

Did a couple local regtest TORv3 MNs

**Pull request merged**
