### PR TITLE
[Qt] Feature: setstakesplitthreshold value set in Qt GUI

### PR DESCRIPTION
**Pull request by lex-dev1**
This is the implementation of the feature request [#424](https://github.com/PIVX-Project/PIVX/issues/424)

34343763-83a0cad2-e9e3-11e7-893b-78d11f012868

Requested feature has been completed considering current architecture of CWallet class. 

This architecture raised few concerns that we would like to bring to everyone's attention. We believe some attention should be paid to the future possibility of refactoring done for this class and setting up a separate issue if approved by core team task specifically for that purpose.

We would like to bring current implementation with public fields in this class to core team's attention. The way it's currently implemented may result in the possibility of future unstable code and ultimately bugs in application in general. 

CWallet class as a Base class allows the derived classes to get direct access to CWallet class fields and alter their status without regard for its inner implementation. Getter/setter allows to solve this issue by means of controlling input parameters in the Base class.

It is required to check the existing public fields and in cases where it is necessary to make class fields private and accessible through setter/getter, which will allow to control their alteration.

This task will also require additional work on tests coverage in addition to refactoring.

### CODE REVIEW

**Comment by Fuzzbawls** [comment]
I think the placement of this setting in the coin control UI is not ideal, and should rather be placed in the Options/Settings UI. Otherwise the concept is sound.

**Comment by lex-dev1** [comment]
Original description of this issues contains following request: "Could we get a text box in the Qt options or Coin control" Would you like to duplication this feature in options?

**Comment by Fuzzbawls** [comment]
I personally would rather it be only in the options UI. Having persistent settings like this one in coin-control just seems like improper placement to me. I know what the original issue said and clarification should have been made on my part there, so I do apologize for not doing that sooner.

We can see what others think too.

**Comment by datasubsystems** [comment]
Fuzzbawls, no worries this is easy adjustment to make. Thank you very much for your feedback!

**Comment by Mrs-X** [comment]
- it belongs in the "Options" dialog, probably below the 2 Automint options
- it's not exactly part of this PR, but while you're at it, the command-help says the threshold needs to be `1 < threshold < 999999`, however you can enter `0` here. Maybe we should put `1` as default value in the RPC and the UI.

I've never used this option, but I guess for those who do it's a nice feature to have in the UI 👍

**Comment by lex-dev1** [comment]
The control has been moved to options.

screenshot_20171228_001419

**Comment by datasubsystems** [comment]
@Fuzzbawls @Mrs-X The reason I have decided to use "Wallet" tab is that setstakesplitthreshold <1 - 999,999>belongs to that section in CLI

**Comment by Fuzzbawls** [comment]
I'm ok with it being in the wallet tab as shown above

**Comment by Mrs-X** [comment]
This one should also be merged to master,  not 3.0!

**Comment by Fuzzbawls** [comment]
@Mrs-X good catch on the base branch

**Pull request closed without merging**
