### PR TITLE
[RPC] redirect sendtoaddress to shieldedsendmany for shielded recipient

### PR DESCRIPTION
**Pull request by random-zebra**
Same as we did with `sendmany` on #2014 .
Keep old implementation for transparent recipients.
Add test case in `sapling_wallet` functional test (also currently running live on https://faucet.pivx.link/).

### CODE REVIEW

**Review by furszy — COMMENTED** [review]
Would be good to decouple the "convert params to 'shieldedsendmany' format" block into its own method and call it in `sendmany` and `sendtoaddress`. So we don't duplicate the code.

**Comment by random-zebra** [comment]
Updated.

**Review by Fuzzbawls — APPROVED** [review]
ACK 7dbd3bff6a459d388cbff552a5ca11a24b541ac1

**Review by furszy — APPROVED** [review]
utACK 7dbd3bff6a459d388cbff552a5ca11a24b541ac1

**Pull request merged**
