### PR TITLE
[Refactoring] Remove checkpoints circular dependencies

### PR DESCRIPTION
**Pull request by random-zebra**
Based on top of
- [x] #2641 

This removes two groups of circular dependencies:
1. checkpoints <-> validation
   By moving `GetLastCheckpoint()` function to validation.cpp (as it's only used by `ContextualCheckBlockHeader`).
2. checkpoints <-> chainparams
   By moving `CCheckpointData` declaration to chainparams (where the per-network checkpoint data is defined), thus making chainparams independent from checkpoints.

### CODE REVIEW

**Comment by random-zebra** [comment]
Rebased on master.

**Review by furszy — APPROVED** [review]
code ACK e25b1153d72760855b8f020cc5cd04838d49acbd

**Comment by random-zebra** [comment]
Rebased, fixing conflict in `miner_tests.cpp`

**Review by furszy — APPROVED** [review]
re-ACK 50fb7797b5a58cd927e9539f8cf4e9cf21546cfb

**Pull request merged**
