### PR TITLE
[Validation] Remove dead zc checks from ATMP

### PR DESCRIPTION
**Pull request by furszy**
Since v5 the network is not longer accepting zc transactions. No need to continue having the zerocoin dead code in the accept to mempool function.
This PR cleans it up, removing the unneeded zc mentions in the ATMP process.

### CODE REVIEW

**Review by random-zebra — DISMISSED** [review]
utACK 2a108b66ae146f4f1525047089d4bcc2cd755328

**Review by Fuzzbawls — DISMISSED** [review]
utACK 2a108b66ae146f4f1525047089d4bcc2cd755328

**Comment by random-zebra** [comment]
Needs rebase.

**Comment by furszy** [comment]
rebased.

**Review by random-zebra — APPROVED** [review]
re-utACK 315da8c7c089aa5fbf1fa23814571fa25e770fdf and merging...

**Pull request merged**
