### PR TITLE
Improving masternode check inputs and add process

### PR DESCRIPTION
**Pull request by furszy**
Improvements to the check inputs and add process:

* Removed an unneeded disk lookup (`GetTransaction` function call).
* Removed an unneeded `cs_main` lock.
* Added a missing `chainActive` guard.
* Cleaned a redundant pcoinsTip access.

### CODE REVIEW

**Review by random-zebra — APPROVED** [review]
Nice. utACK bbfa1021baadd6416ec43f9ac7c558d91f878b4a

**Review by Fuzzbawls — DISMISSED** [review]
utACK bbfa1021baadd6416ec43f9ac7c558d91f878b4a

**Comment by furszy** [comment]
This was conflicting with master, rebased.

**Review by random-zebra — APPROVED** [review]
re-utACK 9660555b27ebc06b9e97637450df7ae33c1da7d3 and merging...

**Pull request merged**
