### PR TITLE
[Refactor] Remove OpenSSL

### PR DESCRIPTION
**Pull request by Fuzzbawls**
The natural follow-up to #2278, #2286, and #2288. With these three PRs merged, there are only a few minor pieces of code that still rely on OpenSSL:

- a call to `RAND_bytes` during the ::SLOW path of ProcRand
- feeding output from our RNG back into OpenSSL via `RAND_add` during the ::SLOW and ::SLEEP paths.
- an unused function in `utilstrencodings.cpp` (`DecodeBase64Secure()`, now removed)
- some stale (un-needed/un-used) header includes
- bip38 exclusive usages including the following:
  - using OpenSSL's AES for encryption, now switched to using ctaes
  - using OpenSSL to do HMAC_SHA256 hashing in `crypto/scrypt.cpp`, now switched to using our native HMAC_SHA256 header
  - an unused function in `hash.h` (`std::string Hash(std::string input)`), now removed
  - a SHA256 Hash function to compute a void pointer, switched to using template objects

Upstream PRs backported: https://github.com/bitcoin/bitcoin/pull/17265, https://github.com/bitcoin/bitcoin/pull/17515, and https://github.com/bitcoin/bitcoin/pull/18825

The changes to bip38 were tested by doing two-way encryption/decryption between `master` and this PR

### CODE REVIEW

**Comment by random-zebra** [comment]
Gitian at c316548dcb9b8db6131725fe5df0057e2db45b17

```
71fb56953f6656ade0fefec6e6c7e5ab893c19cb0a38e71aeb82f999b7b98467  pivx-5.1.99-aarch64-linux-gnu-debug.tar.gz
be0ab4a42d772ef5d2038d6e08cf4521651a970d382051b9c36facb5257fe612  pivx-5.1.99-aarch64-linux-gnu.tar.gz
55887321917a4dce9dc8f9928cff4205d847edc6811a5e820993f1d9cdeb5f18  pivx-5.1.99-arm-linux-gnueabihf-debug.tar.gz
c50d7c3d201ef0c622c979ad319f9bc92b3fd275835cf256ec925f1fa49ec3f8  pivx-5.1.99-arm-linux-gnueabihf.tar.gz
71bfd398d6dee3e65d51793c0c33d95d5bb269923283f8f11831b6936d746a30  pivx-5.1.99-i686-pc-linux-gnu-debug.tar.gz
18bd104357e916661a7fbb7fdbbdc766b7ec9e29dd0806955ddc8b2e5cca9878  pivx-5.1.99-i686-pc-linux-gnu.tar.gz
743e2961048dcf2a464a928707cd42eb6f6b8d2465105e7265d7244b17e1bc83  pivx-5.1.99-x86_64-linux-gnu-debug.tar.gz
90c8efb4e824d4d9e173681af5b19a6d0f7e4288a8bbdcf0cc2f0909cd15adcd  pivx-5.1.99-x86_64-linux-gnu.tar.gz
a4b4ba24a594f12f5f0c09fee31d8452da8ee5506105a7a2f82694fe81deeb6f  src/pivx-5.1.99.tar.gz
086ece2c284e8cb5af5b601076b77bc7f8eaf4aebd4cc7396c323a95a03c2d09  pivx-linux-5.1-res.yml

73568933d279d27598a58abd97c4740c18752edccedea54216fc11bfe7444d03  pivx-5.1.99-win-unsigned.tar.gz
5ed6613a6d56e1594c9462ecf864f7fa6274ea98109fee3267abab5c2b71a298  pivx-5.1.99-win64-debug.zip
6e1bd384146926436b1a90a323849ad3cffa6640d5226a59d429e8e97f8a49b1  pivx-5.1.99-win64-setup-unsigned.exe
f2c1b0074aef3f078a8d1e91d3940fcdac9f161d58737f9e99eacdc747ccd4df  pivx-5.1.99-win64.zip
a4b4ba24a594f12f5f0c09fee31d8452da8ee5506105a7a2f82694fe81deeb6f  src/pivx-5.1.99.tar.gz
e5d65a180f9884969bb7a3bb933166d9995a5ea30ab261834c7b67dc3dfbd3cc  pivx-win-5.1-res.yml

81f86bdfeef5b3d927e41df9f11cb3f5f2eec0305f2ee6e368de3c7a723409d5  pivx-5.1.99-osx-unsigned.dmg
6bdb8275c7f1e35c1fe957bdabc9b634853325966b878edd26c5b0e0ae1e0e0f  pivx-5.1.99-osx-unsigned.tar.gz
565860287b9bce003052e6ea789fc6034904b68a654dbc0d0f4cce6f2e710911  pivx-5.1.99-osx64.tar.gz
a4b4ba24a594f12f5f0c09fee31d8452da8ee5506105a7a2f82694fe81deeb6f  src/pivx-5.1.99.tar.gz
41ba3945c4b760bff53ed8c359331308d5152a7d1c3d578ca67b210f263dc7aa  pivx-osx-5.1-res.yml
```

**Review by random-zebra — DISMISSED** [review]
Great PR.
Tested BIP38/Scrypt changes with encryption/decryption between this and master.
Tested resync on mainnet and testnet, and builds (local/depends/gitian) on linux.
All good. Just a minor non-blocking nit, which can be ignored.
ACK c316548dcb9b8db6131725fe5df0057e2db45b17

Note: this is going to have conflicts with #2314

**Comment by Fuzzbawls** [comment]
Rebased now that #2314 was merged and removed the redundant hasher object in `scrypt.cpp`

**Comment by random-zebra** [comment]
Gitian [Merge 556333129e77876d0339834bf12845c106fae371 into 44ddf8a59a407e946224c46498f38a4f7c968037]

```
63182f731897a004b53efe883062b6b9714bbc728a49a5df3341e31e633b3bc6  pivx-5.1.99-aarch64-linux-gnu-debug.tar.gz
daad4c5a3b8fdf6c1d8cf0f605ee0dc996ce854e43a59d6f8f73bff9e23d432a  pivx-5.1.99-aarch64-linux-gnu.tar.gz
3515ccd53d5c672ac2bf1c090930be9532da2bc62c7c42875db6e0b4721e727d  pivx-5.1.99-arm-linux-gnueabihf-debug.tar.gz
95be64efeb024a3db1b54dd548b473bb61683f83f17ec85d5f26a166c62facc3  pivx-5.1.99-arm-linux-gnueabihf.tar.gz
86a01775a302f325f36b3a353cce9ae28c55bb660adf5db466bd0b79ebea6d75  pivx-5.1.99-i686-pc-linux-gnu-debug.tar.gz
16a848a7225f9bb3b514888ade01a99c91dc24437157ef29cb13762ac3d2b896  pivx-5.1.99-i686-pc-linux-gnu.tar.gz
69739b443955c28d4f8204ab9af2faa3884452f7b56182fe27c14c684fb1666d  pivx-5.1.99-x86_64-linux-gnu-debug.tar.gz
c15683e4a450a16f73e241c9167eba155c6458f376ba99466f898594bbf23301  pivx-5.1.99-x86_64-linux-gnu.tar.gz
a7537235f3ef7c1eb6716c8e2a0e69f0c0075481ef4b97a66ca29da67fe696ad  src/pivx-5.1.99.tar.gz
d37cea840deb6b4384c7ce7de4c6ceab39bbe57561bf3b4cc3416b1b75baf638  pivx-linux-5.1-res.yml

e349a2ee151c9c398118fce66778dba2550d4783fcc3c07300802c2993c9408d  pivx-5.1.99-win-unsigned.tar.gz
0e305b6739dd567df29ea76666913e584c098d031b6d02a4851a5b4bef928b62  pivx-5.1.99-win64-debug.zip
7ece649ab42048d9cdf139cfeb2f9168c3711f3d533adb9fc1a5d8a6e6f24e89  pivx-5.1.99-win64-setup-unsigned.exe
c0fe98b2feb07dd9b9ef7dc814dbbeae0f033c8404e8a6590f7a26ab9484e102  pivx-5.1.99-win64.zip
a7537235f3ef7c1eb6716c8e2a0e69f0c0075481ef4b97a66ca29da67fe696ad  src/pivx-5.1.99.tar.gz
e99358fe9f2f059b18cb506c4b1f10688b07dd4b674993424847b55b5a8a8d87  pivx-win-5.1-res.yml

c6ddf78965136a91dbcb4447adf89539b48f55675c37a1fc3210f81b7b500210  pivx-5.1.99-osx-unsigned.dmg
fad3b0e67fd0df1a16531422572a4087470a7e250c022be2f07d58d0308b587d  pivx-5.1.99-osx-unsigned.tar.gz
d260c0850e00a85fe364c1ed09a736b89869b991fd7069f390604ee9299625a5  pivx-5.1.99-osx64.tar.gz
a7537235f3ef7c1eb6716c8e2a0e69f0c0075481ef4b97a66ca29da67fe696ad  src/pivx-5.1.99.tar.gz
8fbbf30c1512a995ec90ec1494d64f34a2f17acd39d42575a82d45664ba8a5c7  pivx-osx-5.1-res.yml
```

**Comment by random-zebra** [comment]
@furszy I assume that we have different hashes because your gitian was done on top of 10319fd3be6804a6508f3c4513aae521a6753b42 (and mine on top of 44ddf8a59a407e946224c46498f38a4f7c968037).

**Review by random-zebra — APPROVED** [review]
ACK 556333129e77876d0339834bf12845c106fae371

**Review by furszy — APPROVED** [review]
k, ACK 5563331 and merging..

**Pull request merged**
