### PR TITLE
Add -backupzpiv startup flag.

### PR DESCRIPTION
**Pull request by presstab**
This will backup the wallet everytime a zpiv is minted. It will keep 10 backups at a time.

### CODE REVIEW

**Comment by rejectedpromise** [comment]
utACK

**Comment by Fuzzbawls** [comment]
Testing this now. Do we want to also add this to the GUI's settings dialog? or default it to enabled?

**Comment by Fuzzbawls** [comment]
Confirmed working as intended
ACK 2ece795

Above questions still remain.

**Comment by borris345** [comment]
This should be added to compiled exes as soon as. Don't want people saying they lost coins

**Pull request merged**
