### PR TITLE
[GUI] Remove BIP70

### PR DESCRIPTION
**Pull request by Fuzzbawls**
Following with upstream's https://github.com/bitcoin/bitcoin/pull/17165, this removes the support for the problematic BIP70, which we weren't fully supporting anyways.

This removes the protobuf dependency completely, as well as removes the GUI's dependency on libssl

### CODE REVIEW

**Review by random-zebra — DISMISSED** [review]
Tested local build / depends / gitian. ACK 84771b01063c5bb2968b231eaf5b6cdbc48c1aeb

**Comment by random-zebra** [comment]
Needs rebase

**Comment by Fuzzbawls** [comment]
rebased

**Review by random-zebra — APPROVED** [review]
utACK 6e25d8320eb9f8f4c2c6f7cd09dd299126cdb454 after rebase

**Review by furszy — APPROVED** [review]
build tested, ACK 6e25d83 and merging..

**Pull request merged**
