### PR TITLE
[RPC] Update univalue and unify JSON obj pushes

### PR DESCRIPTION
**Pull request by Fuzzbawls**
The pervious usage of `push_back(Pair())` was needed for compatibility with the old json spirit library, which we transitioned away from quite a while ago in favor of Univalue.

Univalue provides a more convenient method for pushing key/value pairs into a JSON object or array in the form of `pushKV()`, which is easier to read and leads to shorter code segments.

This PR first updates our univalue subtree with upstream, which has removed the now-unneeded declaration methods for `push_back(Pair())`, as well as patch a bug with `pushKV()` being supplied with a boolean instead of an integer argument.

92c8273 handles the majority of the work to replace usages of `push_back(Pair())` with `pushKV()` with a reproducible shell command.

b401d55 takes care of 3 instances that were not picked up in the previous commit due to multiline code

7723a0a finally, this commit adds the scripted-diff verification linter to TravisCI for future use.

Note: Depending on merge order, existing open PRs may "leak" new or conflicting introductions of `push_back(Pair())`

### CODE REVIEW

**Review by random-zebra — APPROVED** [review]
ACK 28522af5e7c06e32a3eb9024d1d683b9d87f838e

Would merge this sooner rather than later, to minimize the need for multiple rebases (being it a sweeping change) and be sure that open PRs do not introduce code with the outdated `push_back(Pair())`.

**Comment by Fuzzbawls** [comment]
Updated to resolve conflicts. and yes, would be good to merge this sooner rather than later as rebasing isn't possible with subtree updates, need to manually redo the process.

**Review by random-zebra — APPROVED** [review]
rebase ut-ACK 7723a0a9aec61833a3570fbade91c0a78c3207e3

**Review by furszy — APPROVED** [review]
utACK 7723a0a

**Pull request merged**
