### PR TITLE
[Depends] Update macOS cross-compiling toolchain

### PR DESCRIPTION
**Pull request by Fuzzbawls**
This backports the following upstream PRs to update the macOS cross-compiling tools:

https://github.com/bitcoin/bitcoin/pull/17550
https://github.com/bitcoin/bitcoin/pull/16392
https://github.com/bitcoin/bitcoin/pull/18589
https://github.com/bitcoin/bitcoin/pull/19240
https://github.com/bitcoin/bitcoin/pull/19407
https://github.com/bitcoin/bitcoin/pull/17919
https://github.com/bitcoin/bitcoin/pull/19530
https://github.com/bitcoin/bitcoin/pull/17057
https://github.com/bitcoin/bitcoin/pull/20333
https://github.com/bitcoin/bitcoin/pull/18051
https://github.com/bitcoin/bitcoin/pull/19124
https://github.com/bitcoin/bitcoin/pull/20298
https://github.com/bitcoin/bitcoin/pull/20447

The tools being updated are

### Clang
Upgraded from `3.7.1` to `8.0.0`

### cctools

* cctools `877.8` -> `949.0.1`
* LD64 `253.9` -> `530`
* TAPI `1000.10.8`

### DSStore
Upgraded from `1.1.2` to `1.3.0` (this removes the biplist dependency)

This also effectively bumps our minimum supported macOS version to 10.12 (Sierra).

### CODE REVIEW

**Review by furszy — COMMENTED** [review]
looking quite nice ☕ ☕, this is something that we should had done long time ago.

Some extra points:

You can remove the `random.cpp` getentropy() fallback for macOS < 10.12 (#18364) . 

Plus there are other macOS < 10.12 fallbacks that can be cleaned in other places as well. 
I modified some of them here https://github.com/furszy/PIVX/tree/2021_depends-macos-toolchain. (If you want to cherry-pick them here, you will need to rebase this PR on master, the last commit will conflict with the util.cpp/system.cpp rename that was recently merged).

Aside from that, will do a gitian run.

**Comment by Fuzzbawls** [comment]
Yeah, I intentionally left any Qt version fallback logic in the `src/` tree as I wanted to keep this in the depends/build scope to avoid conflicts as much as possible. will be a logical follow-up PR to remove any such fallbacks or no-longer-necessary bits of compatibility code.

**Comment by furszy** [comment]
yep, sounds good.

**Review by furszy — APPROVED** [review]
tested ACK e1b89ac5786330f67b4d5a22d6ab8cd516276113

```
Hashes report:
51db9a64bc2d4cf95b34aba30cdf17601d29cbc0bceb45acc60b4b6eea58ec3b  pivx-5.1.99-osx-unsigned.dmg
c75e135e86847d4676b8c560d06e22f5f211b312e3c5753eaab52c3300071971  pivx-5.1.99-osx-unsigned.tar.gz
3bdb78d5f041f7ebeea1faa3bf1fd39bc2ab4a02652014159eb2db005e4da14e  pivx-5.1.99-osx64.tar.gz
a942ac90d00dd368613ea3ee8fd8b365d6d25aa019f6fe6ea33ab8b437fb6dc9  src/pivx-5.1.99.tar.gz
f47df6e0435dee6cd3369a0ee65ecf94a35792f4bc7e96753d02cf383bc22376  pivx-osx-6.0-res.yml
```

Took me some time to make it work locally. The gitian-build script limitations to build from a PR made me consume some time.
Had to manually checkout and rebase on master the local repo. Plus, fresh gitian-builds for OSX alone doesn't work, the target requires to have downloaded the rust target for linux: `rust-1.42.0-x86_64-unknown-linux-gnu.tar.gz` (this is not related to this PR, happen in master as well).

**Review by random-zebra — APPROVED** [review]
utACK e1b89ac5786330f67b4d5a22d6ab8cd516276113

**Pull request merged**
