### PR TITLE
[WIP] Deterministic zPIV Generation

### PR DESCRIPTION
**Pull request by presstab**
Fulfilling #349 

**Description:** Deterministically generate zPiv using a given seed. This will allow for users to backup a seed, and have the ability to recover/import their zPiv using the seed value.

**Status:** For testing purposes only! Working on testnet. Deterministic 256 bit seed is generated and added to the wallet.dat on startup (if it does not have the seed already). Can manually replace the seed using RPC `setzpivseed`. Code will likely have significant refactoring and clean up.

**Diagram:**
deterministic zpiv

### CODE REVIEW

**Comment by borris345** [comment]
Is this seed just for zpiv or is it the whole wallet with piv aswell?

**Comment by presstab** [comment]
@borris345 This is only for zPIV.

**Comment by jonspock** [comment]
ACK

**Comment by Fuzzbawls** [comment]
Similar to my comment in #413; should this not introduce a wallet version bump? and has there been consideration made for pre-existing wallets? or is this primarily only applied to **NEW** wallet files?

**Comment by presstab** [comment]
This checks for the existence of a zPIV seed and if it DNE then it will add one. So this should be plug and play for new and old wallet files.

**Comment by Sieres** [comment]
this branch has been tested against a number of different scenarios including backwards compatibility and in-flight scenarios.

**Pull request closed without merging**
