### PR TITLE
[MoveOnly] Move non-wallet RPC files to subdir

### PR DESCRIPTION
**Pull request by Fuzzbawls**
No code changes here, just moving of non-wallet rpc files to their own
subdir.

### CODE REVIEW

**Comment by rejectedpromise** [comment]
utACK

**Comment by Mrs-X** [comment]
Hmh, merge conflicts.
Do you resolve them, @Fuzzbawls ?

**Comment by Fuzzbawls** [comment]
#549 being merged created the conflict. I'll rebase this in a bit

**Comment by Mrs-X** [comment]
Merging...

**Pull request merged**
