### PR TITLE
[Trivial] [GUI] Request Dialog typo fix

### PR DESCRIPTION
**Pull request by JSKitty**
From: **Instead of share a PIVX address**
To: **Instead of only sharing a PIVX address**

### CODE REVIEW

**Comment by furszy** [comment]
@JSKitty remember to merge commits please. "Revert" commits are only used when code was merged into master.

**Comment by random-zebra** [comment]
Kitty, I think Furszy meant "squash" commits. I can do that for you, if you want.

**Comment by JSKitty** [comment]
eh, not really sure what happened with the commits there. But the .ts file was reverted atleast I guess.

**Comment by JSKitty** [comment]
Annnd that made it worse, alrighty, I'll just make a new PR.

**Pull request closed without merging**
