### PR TITLE
Always flush block and undo when switching to new file

### PR DESCRIPTION
**Pull request by furszy**
Fixing a possible blocks db corruption cause.

> Previously, the undo weren't being flushed during a reindex because
fKnown was set to true in FindBlockPos. That is the correct behaviour
for block files as they aren't being touched, but undo files are
touched.

> This changes the behavior to always flush when switching to a new file
(even for block files, though that isn't really necessary).

Coming from #6948.

### CODE REVIEW

**Comment by random-zebra** [comment]
Nice. Would be good to include bitcoin/bitcoin#7023 here, to remove the warning.

**Comment by furszy** [comment]
Added 7023 per feedback. Compiler warning removed.

**Review by random-zebra — APPROVED** [review]
utACK ab4f1845a6c37b3dc9cb541a554a980129a3050f

**Review by Fuzzbawls — APPROVED** [review]
ACK ab4f1845a6c37b3dc9cb541a554a980129a3050f

**Pull request merged**
