### PR TITLE
icon UI holding position

### PR DESCRIPTION
**Pull request by gjhiggins**
colorise b&w icons to improve usability, interim solution

### CODE REVIEW

**Comment by Fuzzbawls** [comment]
when you say "interim solution", to what issue/problem/discrepancy are you referring to?

**Comment by Fuzzbawls** [comment]
Current: 
screen shot 2017-03-13 at 7 04 46 pm

Proposed:
screen shot 2017-03-13 at 7 18 07 pm

**Comment by Mrs-X** [comment]
I'm not a GFX dev, but I think the visibility is better for the white icons IMO.

**Comment by PIVX-Project** [comment]
I prefer the existing

**Pull request closed without merging**
