### PR TITLE
public mn address from rpc

### PR DESCRIPTION
**Pull request by thiagokroger**

### CODE REVIEW

**Comment by Mrs-X** [comment]
Some time ago there was some discussion and popular demand to actually remove any IPs from the logs and RPC command for privacy reasons (of course anyone with some coding knowledge like e.g. you could revert that change anyway).

Personally I don't care, but let's wait what others say....

**Comment by thiagokroger** [comment]
Supposing that I need to search a MN by ip address in some tool that I am developing, is there any other way?

**Comment by Fuzzbawls** [comment]
NACK

If you're developing a tool that exposes MN IP addresses publicly, you may want to consider redesigning the tool to **NOT** do that instead.

MNOs know the addresses of their own MNs already, and I cannot think of any legitimate reason for that information to be distinguishable to anyone else.

**Comment by thiagokroger** [comment]
If I have a tool for monitoring like MNO, and I have 3 nodes in the same server... like Pivx, Zcoin and Syscoin. I just want to search for my ip address to start monitoring them, but since pivx is hiding the address, it makes things harder, so I might need to just have my own version of the project with this pull request, if people want to hide the address, they can use something like onion.

**Comment by Mrs-X** [comment]
I monitor mine with `pivx-cli masternode list` and grep for the public address, e.g.
`pivx-cli1 masternode list | grep -B 1 'addr1\|addr2'`

**Comment by Mrs-X** [comment]
Since the community decided about a year ago to remove the IPs from RPC commands and the normal log we'll keep it like it is.

Still a big thank you for your contribution, help is always appreciated :+1:

**Pull request closed without merging**
