### PR TITLE
Better sigcache implementation (CuckooCache)

### PR DESCRIPTION
**Pull request by furszy**
Built on top of #1668.

Part of the back port series to get us closer to upstream's sigcache current state.

The main ones are:

* bitcoin#8895
* bitcoin#9480
* bitcoin#9393

### CODE REVIEW

**Comment by random-zebra** [comment]
Need to include the cuckoocache header in the makefile to be able to compile on all platforms (ref: bitcoin/bitcoin#9393).

**Comment by furszy** [comment]
done, updated. I didn't check travis output.
curiously it is compiling fine locally with the missing header file include.

**Comment by random-zebra** [comment]
This can be rebased now.

**Comment by furszy** [comment]
rebased.

**Pull request merged**
