### PR TITLE
[GUI] Include MN Rewards in the dashboard chart

### PR DESCRIPTION
**Pull request by furszy**
Revival of #1362 with further cleanup.

As we don't have zPIV anymore, this PR removes it from the dashboard chart and include the Masternodes rewards instead.

### CODE REVIEW

**Comment by Fuzzbawls** [comment]
So far this is looking good.

From a visual/presentation perspective, I would maybe change some verbiage though. "PIV" as a column label, for example, is ambiguous, as both staking and MN rewards are both paid out in "PIV".

Given the string changes to the chart description, I think that it may be better to have the column key labels read as "Staking" and "Masternode" respectively, instead of "PIV" and "MN Rewards" especially since "rewards" is implied for both.

**Comment by furszy** [comment]
sure agree, updated per feedback 👍 . (plus rebased on master).

**Review by random-zebra — DISMISSED** [review]
`TransactionFilterProxy::addrPrefix` is unused now and can be removed.
Other than this, tested ACK 43af2794dd0b24c1fd07321aad55280ff0bb92b2

**Comment by furszy** [comment]
good, removed the unused member. Squashed in 222a5113

**Review by random-zebra — APPROVED** [review]
re-ACK efc21988e309daf7ab949b13bbd720669dc2aa61

**Review by Fuzzbawls — APPROVED** [review]
ACK efc21988e309daf7ab949b13bbd720669dc2aa61

**Pull request merged**
