### PR TITLE
[Refactoring] Completed migration of uint* classes to blob

### PR DESCRIPTION
**Pull request by random-zebra**
Finally out of an old rabbit hole, started with #1395, #1414, and #2092.
As per title, complete the migration:
- use `arith_uint*` classes whenever the uint is interpreted as a number
- make `uint*` classes child of `base_blob`, and use it everywhere else
- remove `blob_uint*` temporary class
- update tests

### CODE REVIEW

**Review by furszy — COMMENTED** [review]
Great work conclusion!
Code review ACK 90059b4829e530cf09eb5c74082afe3ad4260e55

Will run it some time on mainnet before giving the final approval.

**Comment by random-zebra** [comment]
Rebased on master fixing minor conflicts with #2288 and #2273 just merged.
I've been running this changeset no-stop on main net and testnet for the past 10 days without issue. Think it can be considered for merging.

**Comment by random-zebra** [comment]
Rebased again.

**Review by furszy — APPROVED** [review]
Have been running this since the last rebase and all good, ACK 722759d258df6863a71c0639ad6ba59a87a02622

**Comment by random-zebra** [comment]
This will have few conflicts with #2352. They are both a pain to rebase / re-review / re-test, so am not sure which one we want to merge first. Pinging @Fuzzbawls

**Comment by Fuzzbawls** [comment]
I'm ok with prioritizing this over #2352 and did some initial code review already, will finish my review later today but looking good so far.

**Review by Fuzzbawls — APPROVED** [review]
ACK 722759d258df6863a71c0639ad6ba59a87a02622

**Pull request merged**
