### PR TITLE
[Wallet] Update checkpoints with v2.2 chain

### PR DESCRIPTION
**Pull request by presstab**

### CODE REVIEW

**Comment by Mrs-X** [comment]
ACK https://github.com/PIVX-Project/PIVX/pull/168/commits/be977dc41d1c6b4df7d64133af44c4df5506452c

The only thing I've not checked is the total number of transactions. Is there an easy way to get this info without a block-explorer?

**Comment by presstab** [comment]
@Mrs-X search the block hash in your `debug.log`, the transaction count should show up right next to the connect block message.

**Comment by jonspock** [comment]
utACK

**Comment by Fuzzbawls** [comment]
utACK be977dc

Will try to do complete sync testing tomorrow

**Comment by Fuzzbawls** [comment]
ACK be977dc

**Pull request merged**
