### PR TITLE
[Trivial] Update unlock description in GUI and CLI

### PR DESCRIPTION
**Pull request by turtleflax**
Update from Obfuscation in CLI, include automint in GUI and CLI, and fix spelling of anonymization

### CODE REVIEW

**Comment by presstab** [comment]
This should be squashed down to a single commit.

**Comment by Fuzzbawls** [comment]
the `*.ts` files should actually not be changed manually as there is a separate process for that, so you can exclude commits `1f83447` and `979162b`

**Comment by rejectedpromise** [comment]
still needing squash

**Comment by Fuzzbawls** [comment]
@turtleflax are you planning to continue/finish this?

**Comment by Fuzzbawls** [comment]
After conferring with @turtleflax, i'm going to see if I can possibly clean/squash this as is instead of opening up a fresh PR.

**Comment by Fuzzbawls** [comment]
Squashed, removed the manual edits to the `.ts` files.

**Comment by Mrs-X** [comment]
utACK

I'm surprised just HOW long the wrong paths in `masternode_conf.md` stayed unnoticed....

**Comment by Mrs-X** [comment]
ACK that the paths in the description indeed match the changed documentation.

The reset is just docu/output change, so I'll merge it now...

**Pull request merged**
