### PR TITLE
[Core] CBlockIndex cleanup - Bump client version to 4.0.99.1

### PR DESCRIPTION
**Pull request by random-zebra**
Removes a number of (unused or barely used) class variables/methods in CBlockIndex, and introduces a way to use a single variable to store either v1 or v2 stake modifiers.

Since `CDiskBlockIndex` serialization starts with CLIENT_VERSION, this pr bumps the CLIENT_VERSION_BUILD in order to introduce a new serialization without requiring reindex.

This is a first (tiny) step towards reducing our memory usage.
On a quick test (x86_64 linux) average RAM usage on (fully synced) Mainet is reduced from 2.486 Gb to 2.190 Gb, and from 1.776 Gb to 1.566 Gb on Testnet.

Future work:
Remove mapZerocoinSupply and nMoneySupply from the blockindex as well.

### CODE REVIEW

**Comment by furszy** [comment]
Human DrahtBot: conflicts after merging 1328. Need rebase.

**Comment by random-zebra** [comment]
Rebased, and moved block version before stake modifier in CDiskBlockIndex serialization, as per @furszy 's suggestion

**Comment by Fuzzbawls** [comment]
needs rebase

**Comment by random-zebra** [comment]
Rebased

**Comment by random-zebra** [comment]
Merging...

**Pull request merged**
