### PR TITLE
[Cleanup] Small main.cpp cleanup 

### PR DESCRIPTION
**Pull request by furszy**
Three changes:
1) Clean a not used CInv in ConnectTip.
2) Move CBlock to const where was possible.
3) ~~Remove obsolete upgrade signal based on last 100 block version check.~~

### CODE REVIEW

**Comment by random-zebra** [comment]
I don't think we should consider "obsolete" the alert signal.
A peer can still receive (and process) blocks with version higher than `CURRENT_VERSION`, makes sense to alert the user if such blocks are predominant (>50% in the latest 100).

Anyway, if we decide to remove this, the functional test `feature_notifications` needs to be updated accordingly.

**Comment by furszy** [comment]
It would make sense if we wouldn't be using spork 14/15 in the upgrade process. Non updated peers will never receive the new version blocks. Them will only see peers with a newer protocol closing the socket (we could code a signal for this and notify the user about it if surpass a certain threshold).

**Comment by random-zebra** [comment]
There is not necessarily a protocol upgrade with a block version bump.
Sporks are only for the ActiveProtocol version, not the block version.
We reject outdated versions but not unknown block versions.

**Comment by furszy** [comment]
If updated peers reject old protocol versions, the new blocks will never be sent to the non upgraded peers.

> There is not necessarily a protocol upgrade with a block version bump.

Is true conceptually but it's not taking into account the last two years of upgrades. We have never bumped the block version only. It always came attached to the active protocol bump too.
i don't see us changing the process in the future, it's a safer upgrade mechanism.

But well, for me it's not really a big topic and i'm actually in the middle here. If we are not using it, nor have any plan to use it in the future and is merely wasting processing time, then we should remove it. In the contraire, if there are more pros having it than the cons, I'm fine on keep it too.

**Comment by Fuzzbawls** [comment]
I'm with Zebra on the issue of block versions. Until such time that we implement BIP9 versionbits, I don't think it would be a good idea to, even conceptually, mandate that block versions are directly tied/dependent on protocol versions, nor remove the check that alerts a user that the majority of recent blocks are of a greater version.

We did have a block version softfork last year, which was coincidentally also released at the same time as a protocol version bump, but there was a stark difference in allowed code pathways between the protocol version, and the block version supermajority.

**Comment by furszy** [comment]
Updated, version block signal commit dropped.

**Comment by random-zebra** [comment]
Needs rebase.

**Comment by furszy** [comment]
rebased

**Pull request merged**
