### PR TITLE
[Refactor] Add LookupBlockIndex

### PR DESCRIPTION
**Pull request by furszy**
Adaptation of 92fabcd for our sources.

> Replacing all mapBlockIndex lookups with a new `LookupBlockIndex()`. In some cases it avoids a second lookup.

### CODE REVIEW

**Review by random-zebra — APPROVED** [review]
Nice. ACK 58779a0fc94997aee1e005a57f74bd043cd132b3

**Comment by furszy** [comment]
nits tackled, moved `NULL` to `nullptr` keyword usage.

**Review by random-zebra — APPROVED** [review]
utACK dc930d45d590ab333112f063e2914cbd01aba89f

**Review by Fuzzbawls — APPROVED** [review]
ACK dc930d45d590ab333112f063e2914cbd01aba89f

**Pull request merged**
