### PR TITLE
[UI] Add proposal monitoring and voting tab

### LINKED ISSUE #360: In-Wallet Voting Tab

### PR DESCRIPTION
**Pull request by Warrows**
These changes introduce a new tab to the wallet allowing users to see the list of running proposals and vote directly with their masternodes.
Right click on a proposal allows to copy its URL.

capture d ecran de 2018-12-02 20-11-01

By the way: closes #360

### CODE REVIEW

**Comment by PIVXStrontium** [comment]
Oh, hello!

**Comment by Mrs-X** [comment]
@Warrows I know @Fuzzbawls is/was working on something like this a while a go.

Did you align with each other to avoid double work?

**Comment by tohsnoom** [comment]
I guess we beat @Fuzzbawls to it. I'm glad you found it useful! We'll be adding a similar GUI for masternode setup soon, you might want to check that out too.

**Comment by tohsnoom** [comment]
If you don't mind, I'd appreciate it if you would include the Phore developer copyright in the headers when you pull this in. Our latest code on the master branch has those.

**Comment by mrmetech** [comment]
This took me 60 hours lol first ever thing i did and honestly not my best work lol

**Comment by mrmetech** [comment]
@Mrs-X really just pulled the proposal tab you guys ignored me about that is as simple as it gets lol.

**Comment by mrmetech** [comment]
He just cherry picked it lol.

**Comment by mrmetech** [comment]
And awwwwwwww all he did was change three lines so if i could be added to contributions that would mean a lot to a 15 year old :P just saying and kinda sucks being banned from your discord but whatever

**Comment by Warrows** [comment]
@mrmetech I am the one who pulled those changes and I have nothing to do with you being banned from discord. Nor was I aware of it.
If you check the diff, you'll notice that the first commit is not a simple cherry-pick, it includes several differences from yours (actually more than the following commits I believe), I just squashed them for ease of review and out of respect.
@tohsnoom The code I picked up did not include such headers. But it seems only normal that we add them. Will do.
@Mrs-X At some point I talked with Fuzzbawls about it but I did not check his old implementation since this one was almost ready to go.

**Comment by mrmetech** [comment]
Ya sorry about that anyways hmmmmmmmmmmmm (thinking about database design.) It was just a little irratiting as i was being ignored about it lol but i guess Seven is like no now anyways.

**Comment by Fuzzbawls** [comment]
NACK

While the concept is sound, the presentation (i feel) is underwhelming.

**Comment by mrmetech** [comment]
BTW The Abstain size issue is because the size of the column is set before it is none initializing if anyone was wondering a horrible but working fix would be to set a value as zero and on the first refresh do the resize and set it to one and have a check but that is honestly a really shitty solution probably but i mean it would work so idk but ya.

**Comment by Warrows** [comment]
Closing this in favor of #792

**Pull request closed without merging**
