### PR TITLE
[Utils] updated netmagic/port for linearize script 

### PR DESCRIPTION
**Pull request by satoshi-ninja**

### CODE REVIEW

**Comment by presstab** [comment]
Our port is 51472, is this intentionally set to 51470 in the commit?

**Comment by satoshi-ninja** [comment]
Yes. I think it should be the rpc-port.

**Comment by Fuzzbawls** [comment]
ACK 25d4a34

Doesn't complete the script for use with the PIVX chain, but does polish the example cfg file

**Comment by Mrs-X** [comment]
Why the change of `netmagic`?

**Comment by Fuzzbawls** [comment]
@Mrs-X verification of message start strings that are written the block files

**Comment by PIVX-Project** [comment]
utACK

**Pull request merged**
