### PR TITLE
[Depends] Fix archs (fixes s390x and ppc64el builds on snap)

### PR DESCRIPTION
**Pull request by cevap**
Fix building from depends for s390x, ppc64el and powerpc. 
- additionaly fixes for m68k and alpha (boost, openssl and qt)

### CODE REVIEW

**Comment by cevap** [comment]
Built on snap with depends folder, PR fixed it:
grafik

it fixed also powerpc if you build it on launchpad, I am to lazy to create it just for demo purpose, you can check current pivx builds with snap here out (it is only edge channel, other channels are older builds with shared libs): https://snapcraft.io/pivx

**Comment by cevap** [comment]
this pull should also fix #786  building for RISC-V, please test it.

**Comment by Fuzzbawls** [comment]
Concept ACK

Don't have any of these types of processors on-hand personally, and it is unlikely that we will "officially" support them, but this doesn't hurt.

**Comment by cevap** [comment]
At the same time, if pivx merges #782 and runs it officially, I guess then some of them could/would be official.

**Pull request merged**
