### PR TITLE
[Cleanup] guiutils cleanup + fix memory mismanagement

### PR DESCRIPTION
**Pull request by furszy**
Straightforward update for the `guiutil` files.
First commit removes unused `TableViewLastColumnResizingFixer` and `DHMSTableWidgetItem` from `guiutil.h/cpp`.
Second and third commit comes from #15208.
Fourth commit comes from #14801.

### CODE REVIEW

**Comment by random-zebra** [comment]
Shouldn't we also hide `SettingsMainOptionsWidget::ui::pushSwitchStart` when macOS > 10.11?

Other than this, concept ACK. Needs rebase for conflict in the release notes file.

**Comment by furszy** [comment]
yeah, plus now that #2272 was merged, i can removed every macOS <= 10.11 check.

**Comment by furszy** [comment]
Done, updated. Added more cleanup. Purely negative PR.

**Review by random-zebra — DISMISSED** [review]
utACK 20fb08307fd14dbb171cd1ecfde5e30dbab89eb9

**Comment by furszy** [comment]
Had to rebase it again due conflicts with the release-notes. Let's merge this one.

**Review by random-zebra — APPROVED** [review]
re-utACK 2896a480b1b6620c7e9d19d96db463efced3e7a0

**Review by Fuzzbawls — APPROVED** [review]
utACK 2896a480b1b6620c7e9d19d96db463efced3e7a0

**Pull request merged**
