### PR TITLE
[Backport] 5.1.0 backports

### PR DESCRIPTION
**Pull request by furszy**
Backport the following PRs to the 5.1 branch:

* #2237 
* #2247
* #2249
* #2254
* #2262
* #2284
* #2290

Missing open PRs that need to get merged to move forward with v5.1.0:

* [x] #2215
* [x] #2283
* [x] #2295
* [x] #2306

When every PR get merged, we can move forward with a new release candidate for the v5.1.0 release (rc3). Then one or two weeks of testing (depending on how many testers join the efforts) and we are ready for the production release.

The heart of v5.1.0 has been already battle tested this past month with the v5.1.0rc2 testing phase. The only remaining point that needs a more broadly usage/testing is #2290 that it's solving a reported issue in the recent release candidate.

### CODE REVIEW

**Comment by furszy** [comment]
Added #2215, #2283, #2295 and #2306 (this last one hasn't been merged yet).

**Comment by furszy** [comment]
#2306 was merged, this is ready to go.

**Review by random-zebra — APPROVED** [review]
utACK 50a5e841c93fcfbd02ad288a936f19b1a500dcc7

**Review by Fuzzbawls — APPROVED** [review]
ACK 50a5e841c93fcfbd02ad288a936f19b1a500dcc7

**Pull request merged**
