### PR TITLE
[RPC] Add `importmulti` RPC command and functional test

### PR DESCRIPTION
**Pull request by random-zebra**
Based on top of:
- [x] #2240 

Essentially backport bitcoin#7551 and bitcoin#9490, with more recent changes to adapt to the current sources.
Fix and re-enable the `wallet_importmulti.py` functional test.

### CODE REVIEW

**Comment by random-zebra** [comment]
Rebased on master after #2240 merge.

**Comment by Fuzzbawls** [comment]
Functionally good. Looking at the upstream PR 7551, I did see that it was requested to change the second (optional) argument from `bool` to a JSON object so more options could be added in the future, but it looks like more options have not been added since.

Maybe it would be better for us to revert that argument back to a `bool` to simplify the command input? Could be done here, in a follow-up, or not at all, since this command is likely only ever going to be used by advanced users who wouldn't have an issue writing a JSON object for the single option.

Also, the help output for this is as-written at the time of the upstream PR is a bit messy and was ultimately cleaned up. This commit (https://github.com/Fuzzbawls/PIVX/commit/80d160a81da9e016f7b4b803f45f981539ccdcef) can be cherry-picked on top of this to take care of such cleanup while assuming that the input arguments will stay as-is.

**Comment by random-zebra** [comment]
Help text cleanup cherry-picked.
I would rather not simplify the second argument for now. As you said,  this command is intended mostly for power-users and scripts.

**Review by Fuzzbawls — APPROVED** [review]
ACK 7e0c70922a68a83d0a4ec1e739f206d4ba5538f0

**Review by furszy — APPROVED** [review]
ACK 7e0c709 and merging..

**Pull request merged**
