### PR TITLE
[Utils] Use xz instead gzip for  MacOS SDK and update README_osx.md

### PR DESCRIPTION
**Pull request by cevap**
- Ref #786 

To be done : 
- [x] - Update travis.yml (_optional_)

### CODE REVIEW

**Comment by Mrs-X** [comment]
Same as https://github.com/PIVX-Project/PIVX/pull/786, will give it a try as soon as time allows first week 2019.

**Comment by cevap** [comment]
I wish your team good luck for 2019 and Merry Christmas for those who celebrate it

**Comment by Mrs-X** [comment]
Same to you and your team, @cevap
 :champagne: :beers:

**Comment by cevap** [comment]
Build with qt5.9.7 and sdk.tar.xz: https://github.com/cevap/PIVX/releases/tag/v3.1.99-qt597
refference: #786

**Comment by cevap** [comment]
https://github.com/PIVX-Project/PIVX/pull/787/commits/0953c828e8a6984983c5b330e2a0f6023406354f https://github.com/PIVX-Project/PIVX/pull/787/commits/ab32c8afbfe41e5f3dc38c1104897fd4bcb04b13 https://github.com/PIVX-Project/PIVX/pull/787/commits/fd20f7f6e7339dd1c3eb1482653604b07fd4b5ef https://github.com/PIVX-Project/PIVX/pull/787/commits/8af1987fe72b8b0a74d78ed1e3233198f56344d8 ref https://github.com/PIVX-Project/PIVX/pull/786#issuecomment-452524995

https://github.com/PIVX-Project/PIVX/pull/787/commits/42a590b84798df9f03db91fbd6b5f5586fb92444 was only resolving conflict for applying https://github.com/PIVX-Project/PIVX/pull/787/commits/8af1987fe72b8b0a74d78ed1e3233198f56344d8

**Comment by cevap** [comment]
if you do not want to reduce size with tar.xz, then this PR should be closed, otherwise I can finalize this PR, would be wasted time if there is no plan to switch to tar.xz

**Comment by Warrows** [comment]
NACK for me: I think it's more important to keep interoperability as much as possible and avoid importing unwarranted copyrights  and licensing complications. The gain here is not worth it in my opinion.

**Pull request closed without merging**
