### PR TITLE
[Build] Bump master to 5.5.99 (pre-6.0)

### PR DESCRIPTION
**Pull request by Fuzzbawls**
Simply bumps the version for `master` branch. Gitian descriptor versions for `master` were already at 6.0, so didn't need to be updated here.

### CODE REVIEW

**Review by PeterL73 — CHANGES_REQUESTED** [review]
Shouldn't the _COPYRIGHT_YEAR also be bumped to 2022 or 2023?

**Comment by Fuzzbawls** [comment]
> Shouldn't the _COPYRIGHT_YEAR also be bumped to 2022 or 2023?

not in this PR as that would be out-of-scope (updating the copyright year involves a specific process unrelated to the build version). I'll do a separate PR to update the copyright year.

**Review by yenachar — APPROVED** [review]
utACK a79e456ffd9df3db0936a24da64af681902b06ab

**Review by panleone — APPROVED** [review]
utACK a79e456ffd9df3db0936a24da64af681902b06ab

**Pull request merged**
