### PR TITLE
[GUI] Upgrade to HD wallet functionality.

### PR DESCRIPTION
**Pull request by furszy**
This was built on top of #1399. 

Essentially connecting the HD wallet upgrade to the GUI as it was defined in the release-notes in #1327.

### CODE REVIEW

**Comment by Fuzzbawls** [comment]
needs rebase now that #1399 has been merged

**Comment by furszy** [comment]
Done, PR rebased.

**Comment by furszy** [comment]
PR updated.

Answering the observations:

1) yep, just included it.
2) There is a notification coded already, just fixed the issue. The method was not being called properly.
3) Same issue as 2, fixed.

And added the jump lines to the method brackets.

**Comment by furszy** [comment]
The idea behind the 10 seconds delay was to have the wallet running properly before the notification gets launched (sometimes the first window show is not so smooth -- varies over the different OS and machine resources --). But sure, we can decrease it to possibly 4 seconds.

And about the unlock context point, agree. Would merge this and create a new PR once #1387 gets merged.

**Pull request merged**
