### PR TITLE
[Test] Wallet testing setup.

### PR DESCRIPTION
**Pull request by furszy**
Created a new testing setup for unit tests that requires the wallet. 

Removing the dependency from the ones that don't need it.

### CODE REVIEW

**Comment by furszy** [comment]
rebased now that 1445 was merged.

**Comment by random-zebra** [comment]
@furszy , this seems to be only partially porting bitcoin#7905.
Is there a particular reason why some changes (e.g. move accounting_tests and rpc_wallet_tests to wallet/test, move wallet_ismine, etc) weren't included?

**Comment by furszy** [comment]
No particular reason, was a back ported directly from latest upstream and not from the PR.

**Comment by random-zebra** [comment]
Shouldn't we use this new fixture on other tests too?
E.g. `wallet_tests`, `transactions_tests`, `zerocoin_transactions_tests` .
Btw, some of them are currently erroring out on Win.

**Comment by furszy** [comment]
We don't have any `transactions_tests`. The other two, yes. Can be applied to those.

**Comment by random-zebra** [comment]
Of course we have one, instead.
It is called `transaction_tests` (not "transactions").
We have script tests as well.

**Comment by furszy** [comment]
In that test, there is no CWallet class initialization. It's not using the wallet.

**Comment by furszy** [comment]
Updated following feedback 👍 .

**Pull request merged**
