### PR TITLE
[zerocoin] Use existing lib function for bignum hex import

### PR DESCRIPTION
**Pull request by Warrows**
This replaces custom code with an underlying lib function for bignum hex import. Improves readability and consistency with comparable functions.

### CODE REVIEW

**Comment by Fuzzbawls** [comment]
If our long-term intention is to eliminate the dependency on OpenSSL, doesn't this kind of do the opposite?

**Comment by Mrs-X** [comment]
PR #666, created 6 days ago. The pull-request of the beast I guess ;-)

Like Fuzzbawls I'm a bit undecided on this one.
If we _really_ want to get rid of OpenSSL in the long term we should keep the old code, it seems to work fine and _"if it ain't broken, don't fix it"_

On the other side, we most probably won't replace the various flavors of OpenSSL rand() functions, and if we keep OpenSSL anyway for other reasons we should use it and let them fix probably issues.

@Warrows Did you check side by side if both implementations return exactly the same value with each call?
ewr

**Comment by Warrows** [comment]
I have to confess I didn't test it thoroughly but assumed that any change would be covered by existing unit tests.
I'm currently working toward a different implementation of `CBigNum` using gmp instead of OpenSSL. I hope it will bring performance improvements, but I'm not sure yet. 
We might want to let self-compilers choose their implementation (even if we specify one of them as discouraged/unsafe). In this case, I think it's better to improve this code anyway.

**Comment by Mrs-X** [comment]
Just ran a little test and the results were all identical, so at least from this side everything's fine.
Will compare the GMP implementation once you've completed it.

**Comment by Warrows** [comment]
Closing this by virtue of "if it ain't broken, don't fix it".

**Pull request closed without merging**
