### PR TITLE
[Wallet] HD wallets automatic upgrade to sapling features.

### PR DESCRIPTION
**Pull request by furszy**
HD wallets (`FEATURE_PRE_SPLIT_KEYPOOL`) automatic upgrade to `FEATURE_SAPLING` to support shielded functionality by default.

This is an straightforward version bump because only the seed is needed to generate the sapling keys tree. More info in #1553.

Plus added a version guard in the shielded addresses generation method, so pre-HD wallets show the proper error when they cannot generate shielded addresses (essentially, will notify the user that he/she needs to upgrade their wallet to support shielded operations).

As an extra information, pre-HD wallets who upgrade to HD running v5, will automatically be upgraded to support sapling features. This was done in #1553 as well.

### CODE REVIEW

**Comment by furszy** [comment]
Added a second commit covering locked wallets that require a visual upgrade flow (unlocking the wallet in the process) and the startup reminder dialog.

**Comment by furszy** [comment]
Updated solving GA issue, ready to be merged.

**Review by random-zebra — APPROVED** [review]
ACK 22a5f4fb0ef243f096a074441701976ac83c6a44

**Review by Fuzzbawls — APPROVED** [review]
ACK 22a5f4fb0ef243f096a074441701976ac83c6a44

**Pull request merged**
