### PR TITLE
[Utils] Gitian: add gitian build python script

### PR DESCRIPTION
**Pull request by cevap**
### Releases built with gitian-build.py

release | tag version/branch | Gitian signatures | Built on OS |
----------:|:--------------------------|:------------------------|:----------------|
[Release v3.1.1](https://github.com/cevap/PIVX/releases/tag/v3.1.1) | [v3.1.1](https://github.com/cevap/PIVX/releases/tag/v3.1.1) | [gitianbuild log](https://github.com/PIVX-Project/PIVX/files/2709670/gitianbuild-ubuntu-bionic.log) <br><br>[Linux](https://github.com/cevap/gitian.sigs-1/tree/3.1.1-bionic/3.1.1-linux/49464B32BA6683BA)<br>[Mac OS](https://github.com/cevap/gitian.sigs-1/tree/3.1.1-bionic/3.1.1-osx-unsigned/49464B32BA6683BA)<br>[Windows](https://github.com/cevap/gitian.sigs-1/tree/3.1.1-bionic/3.1.1-win-unsigned/49464B32BA6683BA) | Distributor ID:	`Ubuntu`<br>Description:	`Ubuntu 18.04.1 LTS`<br>Release:	`18.04`<br>Codename:	`bionic`
Master branch<br>([3.1.99-qt596](https://github.com/cevap/PIVX/releases/tag/3.1.99-qt596)) | [v3.1.99-qt596](https://github.com/cevap/PIVX/releases/tag/3.1.99-qt596) | [Linux](https://github.com/cevap/gitian.sigs-1/tree/master/master-linux)<br>[Mac OS](https://github.com/cevap/gitian.sigs-1/tree/master/master-osx-unsigned)<br>[Windows](https://github.com/cevap/gitian.sigs-1/tree/master/master-win-unsigned) | Distributor ID:	`Ubuntu`<br>Description:	`Ubuntu 18.04.1 LTS`<br>Release:	`18.04`<br>Codename:	`bionic`
master branch<br>([3.1.99-qt597](https://github.com/cevap/PIVX/releases/tag/v3.1.99-qt597))<br>_(with qt5.9.7)_ <br>with [MacOSX10.11.sdk.tar.xz](https://github.com/gitianuser/MacOSX-SDKs/releases/download/MacOSX10.11.sdk/MacOSX10.11.sdk.tar.xz)| [v3.1.99-qt597](https://github.com/cevap/PIVX/releases/tag/v3.1.99-qt597) | [gitianbuild log](https://github.com/cevap/PIVX/releases/download/v3.1.99-qt597/gitian-build.log) <br><br>[Linux](https://github.com/cevap/gitian.sigs-1/tree/qt5.9.7/3.1.99-qt597-linux)<br>[Mac OS](https://github.com/cevap/gitian.sigs-1/tree/qt5.9.7/3.1.99-qt597-osx-unsigned)<br>[Windows](https://github.com/cevap/gitian.sigs-1/tree/qt5.9.7/3.1.99-qt597-win-unsigned) | Distributor ID:	`Ubuntu`<br>Description:	`Ubuntu 18.04.1 LTS`<br>Release:	`18.04`<br>Codename:	`bionic`

**This script is used with bionic or debian 9.x** but can be adapted
for usage with trusty. Current script works for current master and
releases after 3.1.1.

Script works with debian 8 and trusty but would require some adaption,
I compiled release 3.1.1 with gitian-descriptors from current
master.

Script works also *with docker* for those who want to try something different than LXC. ***You can not build on bionic with KVM, latest supported by KVM is xenial***

### Script build info
Bulding for current master/newer releases (bionic)
- [debian 9 Stretch or later](https://www.debian.org/distrib/netinst)
- [Ubuntu 18.04 (bionic)](http://cdimage.ubuntu.com/netboot/18.04.1/)
- [Fedora 29](https://getfedora.org/en/workstation/download/)
- [Opensuse LEAP/Thumbleweed](https://software.opensuse.org/)

Building for 3.1.1 or earlier (trusty)
- debian 8.10
- ubuntu trusty

More info and refference:
https://github.com/bitcoin-core/docs/blob/master/gitian-building.md

### How to setup gitian
1. download latest ubuntu bionic netinstall
    _([Ubuntu 18.04 LTS (Bionic Beaver) Netboot](http://archive.ubuntu.com/ubuntu/dists/bionic-updates/main/installer-amd64/current/images/netboot/))_
1. install from Ubuntu Netbook (_probably everybody uses here VM's, please check [this part for connecting over ssh](https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-create-vm-debian.md#connecting-to-the-vm), if you did not set port forwarding to 22222, use please default port whihc is 22_)
    _During installation, when you choose software packages, mark checkbox [x] only for SSH_ 
1. Install dependencies
    `sudo apt-get install git ruby apt-cacher-ng qemu-utils debootstrap lxc python-cheetah parted kpartx bridge-utils make curl firewalld`
1. configure LXC and reboot
    set up LXC and the rest with the following, which is a complex jumble of settings and workarounds:
    ```
    sudo -s
    # the version of lxc-start in Debian needs to run as root, so make sure
    # that the build script can execute it without providing a password
    echo "%sudo ALL=NOPASSWD: /usr/bin/lxc-start" > /etc/sudoers.d/gitian-lxc
    echo "%sudo ALL=NOPASSWD: /usr/bin/lxc-execute" >> /etc/sudoers.d/gitian-lxc
    # make /etc/rc.local script that sets up bridge between guest and host
    echo '#!/bin/sh -e' > /etc/rc.local
    echo 'brctl addbr br0' >> /etc/rc.local
    echo 'ip addr add 10.0.3.1/24 broadcast 10.0.3.255 dev br0' >> /etc/rc.local
    echo 'ip link set br0 up' >> /etc/rc.local
    echo 'firewall-cmd --zone=trusted --add-interface=br0' >> /etc/rc.local
    echo 'exit 0' >> /etc/rc.local
    chmod +x /etc/rc.local
    # make sure that USE_LXC is always set when logging in as gitianuser,
    # and configure LXC IP addresses
    echo 'export USE_LXC=1' >> /home/gitianuser/.profile
    echo 'export GITIAN_HOST_IP=10.0.3.1' >> /home/gitianuser/.profile
    echo 'export LXC_GUEST_IP=10.0.3.5' >> /home/gitianuser/.profile
    reboot
    ```
    
    You can install vm builder from repository or use the same which is used on debian
    ```
    wget http://archive.ubuntu.com/ubuntu/pool/universe/v/vm-builder/vm-builder_0.12.4+bzr494.orig.tar.gz
    echo "76cbf8c52c391160b2641e7120dbade5afded713afaa6032f733a261f13e6a8e  vm-builder_0.12.4+bzr494.orig.tar.gz" | sha256sum -c
    # (verification -- must return OK)
    tar -zxvf vm-builder_0.12.4+bzr494.orig.tar.gz
    cd vm-builder-0.12.4+bzr494
    sudo python setup.py install
    cd ..
    ``` 
    **Note**: When sudo asks for a password, enter the password for the user `gitianuser` not for `root`.

1. Clone the git repositories for pivx and Gitian.
    ```
    git clone https://github.com/devrandom/gitian-builder.git
    git clone https://github.com/PIVX-Project/PIVX.git
    git clone https://github.com/PIVX-Project/gitian.sigs.git
    git clone https://github.com/PIVX-Project/pivx-detached-sigs.git
    ```
1. Copy gitian-build.py script and make it executable
    ```
    cp ./PIVX/contrib/gitian-build.py ../gitian-build.py
    chmod +x ./gitian-build.py
    ```

1. Prepare gitian with gitian-build.py
    ```
    export VERSION=TagVersionOrBranch
    export SIGNER=YOURGPGID
    ./gitian-build.py --setup $SIGNER $VERSION    
    ```

#### How to build version 3.1.1 with this python-build.py script:

https://gist.github.com/cevap/66abfd69d47a8ac68c20b4ea7525d63f

_(for automatic/signed commit, remove `--no-commit`)_
```bash
export VERSION=3.1.1
export SIGNER=YOURGPGID
cd ./PIVX
wget https://gist.githubusercontent.com/cevap/66abfd69d47a8ac68c20b4ea7525d63f/raw/1ade0d0d237e51f08b7316011ae58f186858bec1/0001-Patch-gitian-descriptors-for-use-on-bionic-with-giti.patch
git apply 0001-Patch-gitian-descriptors-for-use-on-bionic-with-giti.patch
cp ./contrib/gitian-build.py ../gitian-build.py
chmod +x ../gitian-build.py
cd ..

./gitian-build.py --build --no-commit -j 2 -m 3071 $SIGNER $VERSION
```

#### How to build from branch/commit
_(for automatic/signed commit, remove `--no-commit`)_
```bash
export VERSION=master
export SIGNER=YOURGPGID
cd ./PIVX
wget https://gist.githubusercontent.com/cevap/66abfd69d47a8ac68c20b4ea7525d63f/raw/1ade0d0d237e51f08b7316011ae58f186858bec1/0001-Patch-gitian-descriptors-for-use-on-bionic-with-giti.patch
git apply 0001-Patch-gitian-descriptors-for-use-on-bionic-with-giti.patch
cp ./contrib/gitian-build.py ../gitian-build.py
chmod +x ../gitian-build.py
cd ..

./gitian-build.py --build --no-commit --commit -j 2 -m 3071 $SIGNER $VERSION
```

### Connected to other pulls

Builds with following pulls:
- [x] https://github.com/PIVX-Project/PIVX/pull/782 (_not related to gitian building process_)
- [x] https://github.com/PIVX-Project/PIVX/pull/783
- [x] https://github.com/PIVX-Project/PIVX/pull/786
- [x] https://github.com/PIVX-Project/PIVX/pull/787

### CODE REVIEW

**Comment by cevap** [comment]
you might want to change
- the folder for binaries from `PIVX-binaries` to `pivx-binaries`
- create MacOS SDK 10.11.tar.xz
  - [register apple developer account](https://developer.apple.com/register/) 
  - [download MacOS SDK 10.11 from apple](https://developer.apple.com/devcenter/download.action?path=/Developer_Tools/Xcode_7.3.1/Xcode_7.3.1.dmg)
  - Create own sdk.tar.xz instead of sdk.tar.gz (_smaller size => faster download_)
    - Change [extract SDK script to create tar.xz instead of tar.gz](https://github.com/bitcoin/bitcoin/blob/master/contrib/macdeploy/extract-osx-sdk.sh)
    ```
    find "${SDKNAME}" | sort | tar --no-recursion --mtime="${MTIME}" --mode='u+rw,go+r-w,a+X' --owner=0 --group=0 -c -T - | xz -e9 > "${SDKNAME}.tar.xz"
    ```
    - Change filename to `MacOSX10.11.sdk.tar.xz` in in gitian descriptors 
    - Change extract command for `MacOSX10.11.sdk.tar.xz` to:
    ```
    tar -C ${BASEPREFIX}/SDKs -xvf ${BUILD_DIR}/MacOSX10.11.sdk.tar.xz
    ```
    - Adapt travis for tar.xz
    - Check [documentation and other refferences to SDK](https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-mac-os-sdk.md)

**Comment by cevap** [comment]
@Mrs-X I splitted pulls but actually they (#782 #786 #787 ) could be taken into one together with snapcraft as part of build and release process upgrade.

**Comment by cevap** [comment]
Build with QT5.9.7 and [MacOSX10.11.sdk.tar.xz](https://github.com/gitianuser/MacOSX-SDKs/releases/download/MacOSX10.11.sdk/MacOSX10.11.sdk.tar.xz) on ubuntu bionic
- binaries: https://github.com/cevap/PIVX/releases/tag/v3.1.99-qt597
- gitian sigs: https://github.com/cevap/gitian.sigs-1/tree/qt5.9.7

**Comment by Fuzzbawls** [comment]
I think this should be rolled back to 571b8e3. The marginal gains that come from using xz archives instead of gz archives isn't really worth changing the download URLs. Also, re-distributing the OSX SDK in this way is in violation of Apple's license terms.

**Comment by cevap** [comment]
*Note: [this pull](https://github.com/bitcoin-core/docs/pull/46) misses 1,2 screenshots and minor changes, but in general, this would be updated guide: https://github.com/bitcoin-core/docs/pull/46 , you can check it out [here](https://github.com/cevap/docs)*

**Comment by cevap** [comment]
seems that changes applied on the folder names was applie after 571b8e3cd33a9bfe9f89ff294038a32fd89cf0d5 and I forgot to readd them, in https://github.com/PIVX-Project/PIVX/pull/786/commits/bccd2df60cd40b915d55a409c0d9e74795bc8f58 I changed name back but forgot that pivx is in capitals. If you want to have it clean, I could revert it it once again back and reapply last 3 commits in one.

**Pull request merged**
