### PR TITLE
[UI] Show path to wallet.dat in wallet-repair tab

### PR DESCRIPTION
**Pull request by Mrs-X**
wallet-dir

### CODE REVIEW

**Comment by Fuzzbawls** [comment]
Concept ACK, though may become redundant when upstream changes are synced more. Still won't hurt anything.

**Comment by presstab** [comment]
utACK

**Comment by jonspock** [comment]
utACK

**Comment by PIVX-Project** [comment]
Ack

**Comment by PIVX-Project** [comment]
Maybe add a button to open the directory??

**Pull request merged**
