### PR TITLE
[MoveOnly] Remove zPIV code from main.cpp

### PR DESCRIPTION
**Pull request by presstab**

### CODE REVIEW

**Comment by Fuzzbawls** [comment]
Concept ACK.

I was already looking at moving the `-reindexzerocoin` code in init elsewhere

**Comment by presstab** [comment]
@Fuzzbawls thanks for the quick review. Styling changes have been fixed and pushed.

**Comment by Warrows** [comment]
I've been testing this before the changes proposed by fuzzbawls and ended up getting deadlocks crashes. The issue was appearing upon unlocking the wallet on a Debian 9 x64. I was unable to reproduce the issue on Windows so far.
I didn't have time to investigate further and I'm not sure I'll have it before next week. I'll try to test with the latest changes ASAP though.

**Comment by Fuzzbawls** [comment]
ACK 873ef19

@Warrows any further update on your deadlock issue? if it isn't directly related to this code move, then this should be good to go.

**Comment by Warrows** [comment]
I won't be able to test further before Monday. I don't know how the issue could be related but it appeared with this pr.

**Pull request merged**
