### PR TITLE
[Bug][Refactoring] Miscellaneous fixes

### PR DESCRIPTION
**Pull request by random-zebra**
This is a collection of small fixes for the following issues/defects (discovered with the coverity tool):

- Big parameters passed by value
- calls to rand() function
- Dereference before/after null-pointer check
- Pointer to local variable out of scope
- Resource leak with call to ConnectNode
- Non-floating point result - unintended integer division (bitcoin/bitcoin#9288)
- String not-null-terminated (bitcoin/bitcoin#11193)
- Structurally dead code (bitcoin/bitcoin#9575)
- Unchecked boolean return value of functions (GetOp, GetTransaction, TxOutToPublicCoin)
- Unitialized pointers and scalar fields
- Illegal memory access (bitcoin/bitcoin#13159)
- Useless call to pubkey.IsCompressed()
- Wrong `sizeof` argument (bitcoin/bitcoin#11024 + revert #494)

### CODE REVIEW

**Comment by random-zebra** [comment]
Rebased.

**Comment by random-zebra** [comment]
Rebased.

**Review by furszy — APPROVED** [review]
Looking good, ACK 84b418534cfdadc09b7a2e4c64134a76aa342916

**Review by Fuzzbawls — APPROVED** [review]
ACK 84b418534cfdadc09b7a2e4c64134a76aa342916

**Pull request merged**
