### PR TITLE
[TierTwo] Fix more circular dependencies.

### PR DESCRIPTION
**Pull request by furszy**
Fixed some circular dependencies over the tier two and net_processing due the cs_main/Misbehaving calls.

Making this now, and not waiting to post-v6.0 (where we can directly remove the entire masternode manager file) because it affects the `mnauth` workflow introduced in #2647 which adds other circular dependencies.

### CODE REVIEW

**Comment by random-zebra** [comment]
There's a couple of bugs making the various `Misbehaving` calls unreachable.
The semantic for the boolean return value of the `*::ProcessMessage` functions is switched:  `true` should mean "all good", which would be  `dosScore == 0`.
Also, if you check its return value, there's no need to double check `dosScore > 0` outside of ProcessMessage.

**Comment by furszy** [comment]
done, and rebased on master. Nice quick feedback zebra.

**Comment by furszy** [comment]
rebased, conflicts solved.

**Comment by furszy** [comment]
rebased, conflicts solved, ready to go.

**Comment by random-zebra** [comment]
Code ACK. Although this is going to have a conflict with #2659. We probably want to merge that one before.

**Comment by furszy** [comment]
yeah, better to merge 2659 first so the 5.4 backport work is more straightforward.

**Comment by random-zebra** [comment]
This can be rebased now.

**Review by random-zebra — APPROVED** [review]
ACK a02faf01a2c573ba9fea948c6391afab3b91e3a8

For the future, as discussed, we should keep in mind the new interface between validation and net_processing in upstream (stop passing DoS scores around in the validation code, and just rely on `CValidationState`).

**Review by Fuzzbawls — APPROVED** [review]
ACK a02faf01a2c573ba9fea948c6391afab3b91e3a8

**Pull request merged**
