### PR TITLE
[Backport] Use static_cast instead of C-style casts for non-fundamental types

### PR DESCRIPTION
**Pull request by furszy**
Coming straight from #10498 with minimum adaptations.

### CODE REVIEW

**Comment by random-zebra** [comment]
Looking good. 
Could backport also bitcoin/bitcoin#12416 here (basically reverting the change in `qt/pivx.cpp` and `qt/winshutdownmonitor.cpp`) to fix the win issue.

**Comment by furszy** [comment]
done @random-zebra, added windows shutdown fix.

**Review by random-zebra — APPROVED** [review]
ACK ab6f1b6b05b1760d1e2b208386103163aa8a5515

**Review by Fuzzbawls — APPROVED** [review]
ACK ab6f1b6b05b1760d1e2b208386103163aa8a5515

**Pull request merged**
