### PR TITLE
main.cpp

### PR DESCRIPTION
**Pull request by Cr4shOv3rrid3**
DASH relations in the comments needs to be deleted this will fix the self corruption of blocks ;)

### CODE REVIEW

**Comment by Mrs-X** [comment]
Funny, but no, those copyright notes are there for a reason and stay there.
Without Dash, there wouldn't be PIVX.

**Comment by Fuzzbawls** [comment]
NACK: not only is this an incomplete PR, but the copyright header, as is, does need to include DASH.

**Comment by sabhiram** [comment]
:)  

copyright does not imply a right to copy, unless you follow the rules.

**Comment by Cr4shOv3rrid3** [comment]
fixed the issue in relation to the copyright. i placed Nick Szabo in front of it inside the amount.h and amount.cpp.

your argument is now invalid

**Pull request closed without merging**
