### PR TITLE
[Core] Optimize reindex

### PR DESCRIPTION
**Pull request by random-zebra**
Another attempt at backporting bitcoin/bitcoin#7917.
Previously in #1334, but put in stand-by few months ago due to some issue after reindex.

Tested both syncing from scratch and using `-reindex` flags. It seems all good now.
Reindex is still slower than resync for some reason, but at least not as much as in master (about 63% faster now).

### CODE REVIEW

**Comment by random-zebra** [comment]
Rebased.

**Review by furszy — COMMENTED** [review]
Initial review ACK 788564a, performing a reindex and will do a second final round.

**Review by furszy — APPROVED** [review]
ACK 788564a

**Comment by random-zebra** [comment]
Rebased on master, after #1872 merge

**Review by furszy — APPROVED** [review]
utACK 2d309330bc93a3e310a8f5cd4912cb80e5579046 after rebase

**Comment by Fuzzbawls** [comment]
This is going to need additional work in order to function as intended. The intention of this optimization was to do an initial first pass through the blk files to build the chain index, then do a second pass activating said chain index.

Given how our POS consensus works (validating the stake input), the first pass fails on the first POS block because, at this point, the blockIndex, `chainActive`, and the `txindex` have not been populated yet, leading to `AcceptBlock()` failing. At this point, the client falls back to network sync, or stalls in the event that there are no peer connections, making "offline reindexing" impossible.

-----------------------------

For reference purposes, here is a table with full reindex timings for both mainnet and testnet using the current `master` branch, which I will update once this PR is functioning in an offline environment:

<table>
<thead>
<tr>
<th colspan=5>Intel Core i9-9900K, 64GB DDR4 3200 RAM, 7200RPM HDD, Windows 10 (WSL), GUI Client, Empty wallet</th>
</tr>
<tr>
<th>Branch</th>
<th>Testnet Time</th>
<th>Testnet Height</th>
<th>Mainnet Time</th>
<th>Mainnet Height</th>
</tr>
</thead>
<tbody>
<tr>
<td>master</td>
<td align="center">~51m25s</td>
<td align="center">1777537</td>
<td align="center">~5hr10m</td>
<td align="center">2532969</td>
</tr>
<tr>
<td>pr-1864</td>
<td align="center">TBD</td>
<td align="center">1777537</td>
<td align="center">TBD</td>
<td align="center">2532969</td>
</tr>
</tbody>
</table>

<table>
<thead>
<tr>
<th colspan=5>Intel Core i9-9900K, 64GB DDR4 3200 RAM, NVME SSD, Windows 10 (WSL), GUI Client, Empty wallet</th>
</tr>
<tr>
<th>Branch</th>
<th>Testnet Time</th>
<th>Testnet Height</th>
<th>Mainnet Height</th>
<th>Mainnet Time</th>
</tr>
</thead>
<tbody>
<tr>
<td>master</td>
<td align="center">~45m</td>
<td align="center">1777537</td>
<td align="center">TBD</td>
<td align="center">2532969</td>
</tr>
<tr>
<td>pr-1864</td>
<td align="center">TBD</td>
<td align="center">1777537</td>
<td align="center">TBD</td>
<td align="center">2532969</td>
</tr>
</tbody>
</table>

**Comment by random-zebra** [comment]
Good finding. Closing for now... this will need more work that can only be done after 5.0

**Pull request closed without merging**
