### PR TITLE
[wallet] Reopen CDBEnv after encryption instead of shutting down

### PR DESCRIPTION
**Pull request by furszy**
An improvement for the wallet UX: Stop requiring a wallet shutdown after the initial encryption. Now the process can safely continue running without any fear of leaking unencrypted keys.

PRs backported from upstream:

* #12493.
* #13161.
* #14320.

### CODE REVIEW

**Comment by furszy** [comment]
Took me a while to find the problem, ready now.
Plus added another bug fix #14320 as well.

**Review by Fuzzbawls — APPROVED** [review]
ACK c5340ec4eb7044483f270fcd034ef3d5278c1ab0

maybe unrelated, but when doing this via the GUI with an already large wallet, the animation screen didn't fully load, so the wallet could be perceived as "frozen"/"unresponsive", but the process did eventually finish...so some follow-up may be needed. A smaller wallet did not display this issue.

**Comment by furszy** [comment]
yep, unrelated to this change. Could work on it on a follup-up work for sure.

**Review by random-zebra — APPROVED** [review]
ACK c5340ec4eb7044483f270fcd034ef3d5278c1ab0

**Pull request merged**
