### PR TITLE
[Minting] Better filtering of zPiv serials in miner.

### PR DESCRIPTION
**Pull request by presstab**
When the miner detects the same zPiv serial already including in the block it is creating, it was not correctly continuing to the next transaction, and therefore was ultimately adding the tx to the block, which would later be rejected as invalid.

### CODE REVIEW

**Comment by rejectedpromise** [comment]
utACK

**Comment by Fuzzbawls** [comment]
been running with this for over 24 hours without any noticeable issue(s), and the code looks sound, so...

ACK fc16763

**Comment by s3v3nh4cks** [comment]
Ack

**Comment by Mrs-X** [comment]
utACK and merged...

**Pull request merged**
