### PR TITLE
[Refactoring] Avoid dereference-of-casted-pointer

### PR DESCRIPTION
**Pull request by random-zebra**
Straightforward cleanup, from bitcoin/bitcoin#10760

### CODE REVIEW

**Review by furszy — DISMISSED** [review]
utACK 0a2b553a79185077f4cd540359ce530fe4f473de

**Comment by random-zebra** [comment]
Rebased.

**Review by furszy — APPROVED** [review]
re-utACK 206a6d694b1dc518893a7e9c171423b6dcad89ff

**Review by Fuzzbawls — APPROVED** [review]
utACK 206a6d694b1dc518893a7e9c171423b6dcad89ff

**Pull request merged**
