### PR TITLE
[Qt] Implement Ban Management in GUI Wallet

### PR DESCRIPTION
**Pull request by Fuzzbawls**
This is based on the previous CLI/RPC functionality introduced in #381

Extends the RPC console UI to allow for disconnecting and banning/unbanning of peers directly from the UI. The ban sweep function has been updated to take into account the link between the core and the UI.

Screenshots:
screen shot 2018-01-06 at 1 42 27 am
screen shot 2018-01-06 at 1 42 40 am

### CODE REVIEW

**Comment by rejectedpromise** [comment]
utACK

**Comment by Fuzzbawls** [comment]
@Mrs-X i don't plan to squash any further than what I already did (the upstream PR(s) for this were well over 30 commits in total).

**Comment by Mrs-X** [comment]
Since this passes the netbase tests for IPv6 and works upstream I'll merge.

**Comment by Sieres** [comment]
ACK

**Pull request merged**
