### PR TITLE
[UI] Fixed Dynamic Screen Elements Issue for Multisig

### PR DESCRIPTION
**Pull request by blondfrogs**
Fixed a known bug for the dynamic list labels for multisig
Realigned the lines of code to use tabs

### CODE REVIEW

**Comment by rejectedpromise** [comment]
utACK
will hopefully get to testing this tonight while working on #371

**Comment by rejectedpromise** [comment]
ACK. All working on Linux Mint 18.3

**Comment by rejectedpromise** [comment]
@Mrs-X I will work on this today and try to get it up. It may have been from the original design of the form, and I was very unaware of that. 
@blondfrogs let me know if you by chance have time to do this today, since I am crunching to get ezPIV done

**Comment by Mrs-X** [comment]
No need to hurry, do it whenever you find the time for it.

**Comment by blondfrogs** [comment]
@Mrs-X Removed HTML and font declaration. Let me know if you find anything else that needs to be changed.

**Comment by Mrs-X** [comment]
There's still some color information at some places, but I'd say we leave it as it is for now and postpone it to a general .ui file cleanup PR.
Merging...

**Pull request merged**
