### PR TITLE
[UI] Improve staking chart workflow

### LINKED ISSUE #1037: Improve staking chart workflow
See discussion in https://github.com/PIVX-Project/PIVX/pull/1009

### PR DESCRIPTION
**Pull request by akshaynexus**
Implements the following requirements
- Be locked to the current date (no displaying tomorrow or the day after).
- Change to the previous month when going before the 1st.
- Change to the next month when going after the last day.

Tested locally on machine on regtest.
Closes #1037

### CODE REVIEW

**Comment by furszy** [comment]
Hmm, reviewed it and honestly, I'm not a fan of how it was coded.
Plus, it's not taking into account the year change.


Would prefer something much clear visually and less error pruning code to follow like this: 

```
void DashboardWidget::onChartArrowClicked(bool goLeft) {
    bool updateMonth = false;
    bool updateYear = false;

    // First update date filter
    if (goLeft) {
        dayStart--;
        if (dayStart == 0) {
            updateMonth = true;
            if (monthFilter == 1) {
                // Prev year
                monthFilter = 12;
                yearFilter--;
                updateYear = true;
            } else {
                monthFilter--; // Prev month
            }
            dayStart = QDate(yearFilter, monthFilter, 1).daysInMonth();
        }
    } else {
        int dayInMonth = QDate(yearFilter, monthFilter, dayStart).daysInMonth();
        dayStart++;
        if (dayStart > dayInMonth) {
            dayStart = 1;
            updateMonth = true;
            if (monthFilter == 12) {
                // Next year
                monthFilter = 1;
                yearFilter++;
                updateYear = true;
            } else {
                monthFilter++; // Next month
            }
        }
    }

    refreshChart();

    if (updateMonth) 
         // todo Update comboBoxMonths

   if (updateYear)
        // todo Update comboBoxYears

   // todo: Finally, check if the current showed date range is the last one and should
   // enable/disable the pushButtonChartRight.

}
```

**Comment by akshaynexus** [comment]
Edit with your suggested improvements.

**Comment by Fuzzbawls** [comment]
Needs to be rebased to resolve conflicts

**Comment by akshaynexus** [comment]
Ok, will do

**Comment by akshaynexus** [comment]
Rebased

**Pull request merged**
