### PR TITLE
[GUI] Fix Passing Not Funded logic

### PR DESCRIPTION
**Pull request by Fuzzbawls**
Followup to #2717 which was incorrectly marking proposals as Over Budget
 instead of Not Passing

### CODE REVIEW

**Review by DeanSparrow — DISMISSED** [review]
I have reviewed this change

**Comment by yenachar** [comment]
My reading is that (all other conditions equal) now if allocatedAmount + prop->GetAmount() <= getMaxAvailableBudgetAmount() the proposal status is NOT_PASSING while before it was PASSING_NOT_FUNDED. That seems strange to me and might merit a double check.

**Comment by Fuzzbawls** [comment]
Here are screenshots to show how this logic change is effective
5.4.0 (does not actually have the `PASSING_NOT_FUNDED` flag):
Image 120

master branch:
Image 121

this PR:
Image 123

Note: I did add an additional commit to start the MN update timer at launch, and when activating the DAO page of the UI. Without that, the cached MN count would only be updated when activating the Settings -> Debug -> Info page or the RPCConsole UI window.

**Comment by yenachar** [comment]
ACK a450ea2e65a12d85fcafc953762e6b871ef591f3

Good check. My reading is that the isPassing variable in the if/else enables the desired logic..

**Review by yenachar — APPROVED** [review]

**Review by DeanSparrow — APPROVED** [review]
utACK 2ba665c39778d33ec34ff1464bf65222ecc6735b

**Pull request merged**
