### PR TITLE
[RPC/REST] Migrate to libevent based httpd server

### PR DESCRIPTION
**Pull request by Fuzzbawls**
This is a collection of upstream changes/improvements to the RPC/REST server. Most notably is that it replaces the antiquated pseudo-httpd server with a libevent2 based solution.

- *Replace spit-and-duct-tape http server with evhttp*. Front-end http
  handling is handled by libevent, a work queue (with configurable depth and
  parallelism) is used to handle application requests.

- *Refactor RPC to move all http-specific code to a separate file*.

- *HTTP dispatch mechanism*; services (e.g., RPC, REST) register which
  URL paths they want to handle.

- *Replace usage of boost::asio with [libevent2](http://libevent.org/)*.
  boost::asio is not part of C++11, so unlike other boost there is no
  forwards-compatibility reason to stick with it.

Commits have been individualized where possible, though the first commit is admittedly large as that is where the bulk of the changeover occurs.

### CODE REVIEW

**Comment by presstab** [comment]
So anything RPC related would be testing this PR? Are there any specific functionalities that I should be testing?

**Comment by Fuzzbawls** [comment]
Rebased on top of current master.

@presstab this doesn't really change much functionality with individual RPC calls, but it does change the handling system for them. Two exceptions are `getblockheader` and `getmempoolinfo`, which are now routed through helper functions instead of direct output.

What I've already tested is that CLI and GUI RPC still handles requests as expected, that running the GUI with `server=0` doesn't break the RPC Console UI, and that the REST endpoints all function as expected (when enabled).

**Comment by Fuzzbawls** [comment]
Could use some more testing on this...or at least more eyes on this. Some of this is blocking other changes from upstream, and this PR itself is mostly from upstream.

**Comment by Mrs-X** [comment]
As expected this breaks the automatic restart of the wallet-repair functions.
Since I can't push to your repository (or create a PR there) you have to include https://github.com/Mrs-X/PIVX/commit/fcdf4ce2a1292cade861303cc0db652ecb2b9457 into your changes.

While I was at it I also added some exception handling when deleting pivxd.pid

**Comment by Mrs-X** [comment]
Couldn't crash the automatic restart of the wallet-repair functions any more, so ACK and merging.

**Pull request merged**
