### PR TITLE
[GUI][Bug] Cold staking screen, total amount was not being updated.

### PR DESCRIPTION
**Pull request by furszy**
The total amount in the cold staking screen (delegations list section) was not being updated. This solves the issue + re organize the UI form to present it aligned to the texts in the left.

### CODE REVIEW

**Comment by random-zebra** [comment]
This is good (total amount there looks nice) but still is not solving the issue.
The problem, I think, is that `tryRefreshDelegations` is called by `onTxArrived`.

When a new delegation is sent, the function is called but, since the utxo is still unconfirmed, the model is not reflecting it yet.
The delegation list is then updated only when a successive call to `tryRefreshDelegations` is made (either a new delegation arrived or a cold stake happened).

**Comment by furszy** [comment]
The issue that you are stating is not from this PR. This was only supposed to solve the total staking amount visibility/update.

Side from that, good catch. Pushed that second issue fixed here too. Showing unconfirmed delegations in the list.

As we are in a freeze period, something for 4.1 is divide the confirmed and unconfirmed amounts in the delegation row.

**Comment by random-zebra** [comment]
Yes, this fixes the issue at hand.
We should remove the "Unconfirmed balance will not be shown" label now though.

**Comment by furszy** [comment]
yeah, removing it

**Pull request merged**
