### PR TITLE
[RPC] shielded_sendmany from multiple sources + raw_shielded_sendmany

### PR DESCRIPTION
**Pull request by random-zebra**
Add the option to `shielded_sendmany` to automatically select the inputs from any transparent or sapling address (inserting the string `"from_transparent"`/`"from_shielded"` instead of  the from-address)

Create new  rpc `raw_shielded_sendmany` which creates (without committing) the shielded transaction and returns a json object.

Update the functional tests.

Based on top of:
- [x] #1961 

Starts with `[Refactor] Introduce CreateShieldedTransaction auxiliary fun for RPC` (e014ff32c2f1ac20aa35f8f8cbc4fd588c74c2af)

### CODE REVIEW

**Comment by random-zebra** [comment]
Rebased on master. Ready for review.

**Review by Fuzzbawls — DISMISSED** [review]
utACK c14e1528e7693a7143e2a15c938feaed22210035

**Review by furszy — COMMENTED** [review]
nice work ☕ , code review till b8e28f86 ACK non-inclusive.

**Review by furszy — APPROVED** [review]
ACK 634ddbf and merging..

**Pull request merged**
