### PR TITLE
[Trivial] [GUI] Customize Fee Dialog text change

### PR DESCRIPTION
**Pull request by NoobieDev12**
"Customize the transaction fee **at your to your liking**,"

Changed to:
"Customize the transaction fee **as per your wish**,"

### CODE REVIEW

**Comment by random-zebra** [comment]
can't we make it simply "Customize the transaction fee"?

**Comment by furszy** [comment]
agree.

**Comment by NoobieDev12** [comment]
Makes sense. Edited.

**Comment by random-zebra** [comment]
Thanks @NoobieDev12 .
Are you familiar with the process of "squashing commits"?
If yes, could you please squash these two?
If not, no worries, I can do it for you.

**Comment by NoobieDev12** [comment]
Still a beginner and learning, so please do it for me to avoid complications. Thank you!

**Pull request merged**
