### PR TITLE
[RPC] Refactor & JSONify results from masternode command(s)

### PR DESCRIPTION
**Pull request by Fuzzbawls**
Refactor the masternode RPC commands to return valid JSON in most cases.

Still a work in progress, but can be tested.

### CODE REVIEW

**Comment by jonspock** [comment]
There seems to be more than just jsonifying going on here. What are the reasons for the other changes?

**Comment by Fuzzbawls** [comment]
updated the title to be more specific. 

A lot of the functionality in rpcmasternode was redundant, confusing, and not at all consistent with other RPC functions. The various "modes" for `masternodelist` for example were easily combined, removing the need for any modes completely, which allowed the help description to outline the exact response specification. 

That said, an unintended change to masternodeman.* did slip in here and will be fixed when I rebase this.

**Comment by Fuzzbawls** [comment]
Rebased

Added a refactoring of the `masternode winners` command/results

**Comment by Mrs-X** [comment]
Is it ready to test?

**Comment by Fuzzbawls** [comment]
@Mrs-X yes, ready to test

**Comment by Fuzzbawls** [comment]
@Mrs-X good catch, added a commit that rewords the help text

**Comment by Mrs-X** [comment]
ACK

**Pull request merged**
