### PR TITLE
Finish address encoding cleanup

### PR DESCRIPTION
**Pull request by furszy**
Decoupled from #2411 Tor's v3 addr support, built on top of #2359.

This PR finishes the address encoding cleanup, removing the `CBase58`, `CBitcoinSecret`, `CBitcoinExtKey`, and `CBitcoinExtPubKey` classes, in favor of using the KeyIO::Encode/Decode functions. Furthermore, all PIVX-specific address logic is moved to key_io.{h,cpp}, leaving base58.{h,cpp} as a pure utility that implements the base58 encoding/decoding logic.
Plus, includes some general utility functions for std::vector and std::string.

Adaptation of the following PRs:

*  #11372.
* #16670. (without faebf62)
*  #16889.
*  #17511.
*  #17721.

### CODE REVIEW

**Comment by furszy** [comment]
Rebased after #2359 merge, ready to go.

**Review by random-zebra — APPROVED** [review]
ACK 5c39626da8695a46a7d71e65ce9f1f0f50103eda

**Comment by furszy** [comment]
Rebased on master, conflicts solved.

**Review by random-zebra — APPROVED** [review]
rebase utACK a470c3421a35251688e9d61807069b5587309868

**Review by Fuzzbawls — APPROVED** [review]
ACK a470c3421a35251688e9d61807069b5587309868

**Pull request merged**
