### PR TITLE
[Util] Add validation interface logging

### PR DESCRIPTION
**Pull request by random-zebra**
Backports bitcoin#16688 [jkczyz], which should help us debug some intermittent failures on GA (e.g. for `feature_reindex` or `wallet_basic` tests).

> Add logging of CValidationInterface callbacks using a new VALIDATION log flag (see 12994). A separate flag is desirable as the logging can be noisy and thus may need to be disabled without affecting other logging.
>
> This could help debug issues where there may be race conditions at play, such as 12978.

Based on top of 
- [x] #2547

### CODE REVIEW

**Comment by random-zebra** [comment]
Rebased on master.

**Review by furszy — DISMISSED** [review]
Nice logging, ACK 74ad1bf31f6ab69f8f8eddce600905627e1efc89

There is a dangling `strMessageMagic` extern definition in `messagesigner.h` that can be removed as well.

**Comment by random-zebra** [comment]
removed extra `strMessageMagic` definition.

**Review by furszy — APPROVED** [review]
utACK d6fe1503 after squash.

**Pull request merged**
