### PR TITLE
Merge dash issue #978

### LINKED ISSUE #82: pivxd segfault on FreeBSD
After staking for about 20 hours, pivxd died with signal 11.

The backtrace from the core dump is below:

```
#0  0x0000000000ca31f9 in CMasternodePayments::CleanPaymentList (this=0x131d028) at masternode-payments.cpp:626

#1  0x0000000000beef69 in ThreadCheckObfuScationPool () at obfuscation.cpp:2270
#2  0x000000000054c698 in boost::_bi::list0::operator()<void (*)(), boost::_bi::list0> () at bind.hpp:198
#3  0x000000000054c638 in boost::_bi::bind_t<void, void (*)(), boost::_bi::list0>::operator() () at bind.hpp:1294
#4  0x000000000054c5cc in boost::detail::thread_data<boost::_bi::bind_t<void, void (*)(), boost::_bi::list0> >::run () at thread.hpp:116
#5  0x0000000801b70e94 in boost::thread::start_thread_noexcept () from /usr/local/lib/libboost_thread.so.1.63.0
#6  0x00000008032a6b55 in pthread_create () from /lib/libthr.so.3
#7  0x0000000000000000 in ?? ()
(gdb) 
#0  0x0000000000ca31f9 in CMasternodePayments::CleanPaymentList (this=0x131d028) at masternode-payments.cpp:626
#1  0x0000000000beef69 in ThreadCheckObfuScationPool () at obfuscation.cpp:2270
#2  0x000000000054c698 in boost::_bi::list0::operator()<void (*)(), boost::_bi::list0> () at bind.hpp:198
#3  0x000000000054c638 in boost::_bi::bind_t<void, void (*)(), boost::_bi::list0>::operator() () at bind.hpp:1294
#4  0x000000000054c5cc in boost::detail::thread_data<boost::_bi::bind_t<void, void (*)(), boost::_bi::list0> >::run () at thread.hpp:116
#5  0x0000000801b70e94 in boost::thread::start_thread_noexcept () from /usr/local/lib/libboost_thread.so.1.63.0
#6  0x00000008032a6b55 in pthread_create () from /lib/libthr.so.3
#7  0x0000000000000000 in ?? ()
```

This binary was built from  v2.1.6 (25bad68) with the patch in #73 applied.

### PR DESCRIPTION
**Pull request by clinta**
Merges dash [#978](https://github.com/dashpay/dash/pull/978).

Appears to fix #82.

### CODE REVIEW

**Comment by Fuzzbawls** [comment]
utACK

**Comment by presstab** [comment]
utack

**Comment by PIVX-Project** [comment]
utAck

**Comment by Mrs-X** [comment]
utACK (nice find BTW :+1: )

**Pull request merged**
