### PR TITLE
[Core] Say "Goodbye" to SwiftTX

### PR DESCRIPTION
**Pull request by random-zebra**
SwiftTX has been disabled via spork ages ago, and no work has been done on it since.
It will never be re-introduced in its current form. 
Later on (after the introduction of deterministic masternodes and LLMQ), we should work on a [DIP10](https://github.com/dashpay/dips/blob/master/dip-0010.md)-style design, implemented from scratch.

So... better not to have all this dead-code spread around, only providing another place for bugs to hide.
It's time to say "goodbye".

### CODE REVIEW

**Comment by furszy** [comment]
Nice cleanup!, concept ACK, needs rebase.

**Review by furszy — APPROVED** [review]
Goodbye, see you when you grow up! Code review ACK 8e319f56

**Comment by Fuzzbawls** [comment]
needs rebase

**Comment by random-zebra** [comment]
Rebased.

**Review by furszy — DISMISSED** [review]
utACK 7d72dd3 after rebase, but it will conflict with 1798 in more than one place. Better to merge that one first.

**Comment by random-zebra** [comment]
Rebased, now that  #1798 is merged.

**Review by furszy — APPROVED** [review]
utACK 98218c6 after rebase.

**Review by Fuzzbawls — APPROVED** [review]
utACK 98218c6549e9ab225e17979b1aa9492f945f280e

**Pull request merged**
