### PR TITLE
[Tests] Resurrect feature_block and kill the p2p comparison test framework

### PR DESCRIPTION
**Pull request by random-zebra**
Follow-up to #2346.

The original goal here was to remove the `ComparisonTestFramework`, following bitcoin#11818.

But, before doing that, had to update the old `feature_block` test, which was still using the framework, even though the test was disabled. 
This is one of the most important functional tests, as it checks all block-related consensus rules, so, just keeping it disabled was not an option.

Aside from being very long (1200+ lines), the test was taking ages to mine any single block.
This is because it relies on `next_block` doing the actual proof of work (`CBlock::solve`), given the regtest nBits (difficulty is fixed on regtest).

Now, since all networks (mainnet/testnet/regtest) share the same genesis block, the regtest difficulty was way higher than it should have been. We never had issues with this, because we are bailing out early in `CheckProofOfWork`, essentially not performing any proof of work check on regtest.
 
So, in order to fix `feature_block.py`, there were two options: either modify `next_block` to keep a fixed nonce, or update the regtest chain parameters, creating a new genesis block with low-diff nBits, and actually checking the proof of work. 
I chose the latter.

This triggered the need to refactor some unit-tests that were changing chain params (from `MAIN` to `REGTEST`) without reloading the genesis block in the block index (which wasn't needed before, because, as explained, all networks had the same genesis).

After this PR, the chain is set only inside the test fixtures, and is never changed inside the single test cases (so there is no need to reload the chain index during execution).

### CODE REVIEW

**Comment by furszy** [comment]
You deserve some beers! 🍻 🍻

**Comment by random-zebra** [comment]
Rebased on master, adding some more refactoring to address https://github.com/PIVX-Project/PIVX/pull/2364#pullrequestreview-652492233

**Comment by random-zebra** [comment]
Rebased.

**Review by furszy — APPROVED** [review]
Awesome work! 🍻 
ACK 48e5d54b5533404e29952f09e53275b2a4d2abde .

what a long long test..

**Review by Fuzzbawls — APPROVED** [review]
ACK 48e5d54b5533404e29952f09e53275b2a4d2abde

**Pull request merged**
