### PR TITLE
[Depends] Use latest config guess/sub

### PR DESCRIPTION
**Pull request by Fuzzbawls**
Allows the depends system to properly identify M1 Mac systems as `aarch64-apple-darwin`.

### CODE REVIEW

**Comment by random-zebra** [comment]
Have checked with:
```sh
git clone git://git.savannah.gnu.org/config.git
cd config && git checkout 4550d2f15b3a7ce2451c1f29500b9339430c877f # last commit of 2021-05-24
cp config.guess config.sub ../PIVX/depends/ && cd ../PIVX
git update-index --assume-unchanged src/chiabls/contrib/relic/include/relic_conf.h.in
git diff
```

The only difference is that we have no newline at the end of the files.
```diff
diff --git a/depends/config.guess b/depends/config.guess
index 57df1f391d..dc0a6b2997 100755
--- a/depends/config.guess
+++ b/depends/config.guess
@@ -1699,4 +1699,4 @@ exit 1
 # time-stamp-start: "timestamp='"
 # time-stamp-format: "%:y-%02m-%02d"
 # time-stamp-end: "'"
-# End:
\ No newline at end of file
+# End:
diff --git a/depends/config.sub b/depends/config.sub
index bb089f1435..7384e9198b 100755
--- a/depends/config.sub
+++ b/depends/config.sub
@@ -1861,4 +1861,4 @@ exit
 # time-stamp-start: "timestamp='"
 # time-stamp-format: "%:y-%02m-%02d"
 # time-stamp-end: "'"
-# End:
\ No newline at end of file
+# End:
```

**Comment by random-zebra** [comment]
Btw... we could pull the actual [latest (as of 2021-08-14)](https://git.savannah.gnu.org/cgit/config.git/commit/?id=191bcb948f7191c36eefe634336f5fc5c0c4c2be) version of these files.

**Review by furszy — APPROVED** [review]
Pulled the latest config files from the gnu repo and the only difference is that still misses the newline at the end of the files.

Other than that, have completed a gitian run with it. So, ACK 8f8d5c0a for me.

**Review by random-zebra — APPROVED** [review]
utACK 8f8d5c0ad25ef39ff8998c7f6299758301696810 and merging...

**Pull request merged**
