### PR TITLE
[Test] BIP62 rule 6 added + script tests updates

### PR DESCRIPTION
**Pull request by furszy**
We are way too behind in terms of the script unit tests, this PR pushes us further into upstream's direction.

Back ported PRs:
* #5143
* #5617
* #5784
* #5952 (de236f57c68c2c29d148a2df9e019f431cee3cb7 only)
* #6075
* #7387
* #7517
* #7818
* #8090
* #11284
* And 4fb789e9b2ffdf48fd50293b3982b3fce4d5fbdf

### CODE REVIEW

**Comment by furszy** [comment]
Ended up adding btc#7387 and a zc txs standardness policy cleanup as well. More changes over the area will come in a follow-up PR, it is a long rabbit hole.

**Review by random-zebra — COMMENTED** [review]
Just a nit for the documentation of `ExtractDestinations`. Otherwise ACK.

**Comment by furszy** [comment]
Added the `ExtractDestinations` documentation for P2CS scripts in 395ecb13.

**Review by random-zebra — APPROVED** [review]
utACK a6d09a982b96e73a1bcfe9ee383167d6c0717ceb

**Review by Fuzzbawls — APPROVED** [review]
ACK a6d09a982b96e73a1bcfe9ee383167d6c0717ceb

**Pull request merged**
