### PR TITLE
[Tier Two] Pre dip7 upgrade

### PR DESCRIPTION
**Pull request by panleone**
Abstract:
The aim of this PR is adding all the background needed to implement Signing Requests (dip7). Two new classes are added that will help: storing/fetching/make sure we are connected to the latest k quorums

### CODE REVIEW

**Comment by panleone** [comment]
PR should be ready to review: In order to test run some quorums on regtest and check that all new rpc commands are giving the expected result

**Review by Liquid369 — DISMISSED** [review]
tACK 4f889737db2b31dfe42035118b3b40a89b239b44

I like this as a precursor and after running and testing were getting proper quorums and validation/commitments/contributions!

great stuff.

**Review by Liquid369 — APPROVED** [review]
Fixed some comments by @Fuzzbawls over readability and CMake
Adjusted per feedback

**Review by DeanSparrow — APPROVED** [review]
utACK https://github.com/PIVX-Project/PIVX/commit/4f889737db2b31dfe42035118b3b40a89b239b44

I have not tested but I have been watching the progress and monitoring the regtest network.

**Review by Fuzzbawls — CHANGES_REQUESTED** [review]
More in-depth review; most comments are stylistic/standards compliance. All unit/functional tests passed with the suggested changes locally for me.

**Comment by panleone** [comment]
Thanks for the in depth review, all suggested changes should have been implemented

**Comment by panleone** [comment]
Updated on master

**Comment by Fuzzbawls** [comment]
This needs some general tidying up / squashing in terms of what each commit does and to remove the recently added merge commit. Merge commits in PRs should be avoided unless they are absolutely necessary (ex: when updating a git subtree). Use git rebase instead (`git pull --rebase origin master`) if you need to pull in newer changes from `master` branch.

**Comment by panleone** [comment]
> This needs some general tidying up / squashing in terms of what each commit does and to remove the recently added merge commit. Merge commits in PRs should be avoided unless they are absolutely necessary (ex: when updating a git subtree). Use git rebase instead (`git pull --rebase origin master`) if you need to pull in newer changes from `master` branch.

Ok I will try to avoid merging from master, I removed the merge commit and squashed the last 8 (which were linting + different suggested changes)

**Review by Liquid369 — APPROVED** [review]
ACK 3007354b98f19683ae6b196bf8e44b37db1f9042

**Review by Fuzzbawls — APPROVED** [review]
ACK 3007354b98f19683ae6b196bf8e44b37db1f9042

**Pull request merged**
