### PR TITLE
[QT] add info to titlebar when zPIV is in maintainence

### PR DESCRIPTION
**Pull request by akshaynexus**
This PR adds a new widget to the titlebar,to show when zPIV is undergoing maintenance

This is the preview for the ui addition
Screen Shot 2019-03-09 at 8 20 24 PM

### CODE REVIEW

**Comment by Fuzzbawls** [comment]
Linter error:
```
This diff appears to have added new lines with trailing whitespace.
The following changes were suspected:
diff --git a/src/qt/privacydialog.cpp b/src/qt/privacydialog.cpp
@@ -61,0 +62,6 @@ PrivacyDialog::PrivacyDialog(QWidget* parent) : QDialog(parent, Qt::WindowSystem
+
@@ -143,0 +150 @@ void PrivacyDialog::setModel(WalletModel* walletModel)
+
```

**Comment by akshaynexus** [comment]
ok, ill fix that

**Comment by Warrows** [comment]
You still have a linter error:
`This diff appears to have added new lines with trailing whitespace.
The following changes were suspected:
diff --git a/src/qt/privacydialog.cpp b/src/qt/privacydialog.cpp
@@ -143,0 +148 @@ void PrivacyDialog::setModel(WalletModel* walletModel)
+`

**Comment by akshaynexus** [comment]
looking into that error,atm

**Comment by akshaynexus** [comment]
fixed the the linting issues

**Comment by Mrs-X** [comment]
Concept ACK, will test tomorrow.

**Comment by akshaynexus** [comment]
ok,will do

**Comment by Mrs-X** [comment]
@akshaynexus Do you still plan to finish this pull-request?

If not I would take over....

**Comment by akshaynexus** [comment]
Will complete the pr in mostly 2 to 3 days,hope thats not a issue

**Comment by Mrs-X** [comment]
Hi @akshaynexus ,
I just played around a bit with your change, even when properly placed in the frame with the PIVX-logo image the logo itself jumps around when you click through the different tabs, this doesn't look nice.

What about placing it where "Zerocoin Actions" is displayed?
zPIV-Warning-Placement
There's still not much more place for text there (this region gets smaller when you have ZPIV in your wallet), but it wouldn't move other UI-elements around.

What do you think?
In case you shouldn't find the time do it next week I'll have a go at it next weekend to get your idea  merged as long as zPIV actually is still in maintenance mode....

**Comment by akshaynexus** [comment]
sure,ill replace it there instead,forgot there was empty space there

**Pull request closed without merging**
