### PR TITLE
Split main.cpp into net_processing/validation as per upstream

### PR DESCRIPTION
**Pull request by barrystyle**
This won't be able to be used directly owing to the upcoming 4.0 release and associated change freeze (also work that has taken place in the meantime), however this will allow future upstream porting to be done with ease. Enjoy.

### CODE REVIEW

**Comment by furszy** [comment]
This was unexpected, effort really appreciated 👌  .

Yeah, it will need some cleanup and updates but great man 👍 . Will review it properly and most likely give you a hand with the updates after 4.0.

**Comment by furszy** [comment]
Hi, now that 4.0 is just about to be released, can continue moving forward with this 🤘 .

First step would be plan this big PR division into a subset of smaller and focalized PRs on top of 4.0, and slowly grow from there to this point, otherwise this will hardly pass the review process.

**Comment by barrystyle** [comment]
Agreed.

I think the way forward would be creating a skeleton set of 
source/headers for validation/net_processing, then using my PR as a 
loose guide as we bring the appropriate functions across.. although feel 
free to suggest as well..

james

**Comment by furszy** [comment]
Hmm, that would most likely end up being still pretty big. Would start porting/moving the isolated code (class by class, method by method). The one who have no modifications and possibly just a single call. Each of them in a separated PR.

A quick example is the `CBlockFileInfo`, which just need to be moved from `main.h` to `chain.h`.

Slowly but steady cleaning the `main.h/cpp` file. Once we get rid off all of the isolated code, can move to the code that require further modifications and/or connections and start moving method by method to the net_processing file.

In this way, we will be able to always move forward merging PR by PR. Doing baby, well reviewed, steps.

**Comment by barrystyle** [comment]
Have prepared a PR, mainly to check if this is headed in the right direction:
https://github.com/PIVX-Project/PIVX/pull/1208

Using Bitcoin 0.14 to 'steer' where required.

**Comment by furszy** [comment]
Anyone opposing to close this? No advances for a long period of time.

**Comment by random-zebra** [comment]
Yep. closing...

**Pull request closed without merging**
