### PR TITLE
[WIP] Miner code reworked from upstream 6898

### PR DESCRIPTION
**Pull request by furszy**
Follow up for #1725.

Finishing the last commit back port of bitcoin#6898 and added bitcoin#7539 on top.

### CODE REVIEW

**Comment by random-zebra** [comment]
This can be rebased now

**Comment by furszy** [comment]
let's merge #1809 first. It will make the rebase a little bit simpler.

**Comment by random-zebra** [comment]
Needs rebase.

**Comment by Fuzzbawls** [comment]
We've discussed this PR a couple times in meetings, and it is largely un-necessary (or at most, non-essential), but I'd like to see it re-analyzed as upstream's work on this front ultimately led to the removal of the Boost `tuple` dependency. And, the more we remove 3rd party library dependencies, the better off in the long run, even if there is no substantial performance gain.

**Comment by furszy** [comment]
feel free of tackling it in another PR, all good for me. Can close this one at any time. Zero priority for me to continue with this work before v5.

**Comment by furszy** [comment]
Closing this, can be revived after v5 if needed.

**Pull request closed without merging**
