### PR TITLE
[Tests][Scripts] Bump Python version to 3.8 and add more linting

### PR DESCRIPTION
**Pull request by Fuzzbawls**
This PR offers a bit of an overhaul to our python test suite and python standards. The high level information is that we:
- migrate from the EOL'd Python 3.5 to a more recent version (3.8)
- strip out some ancient workaround code that is no longer necessary
- add new linters that will provide an early warning if new python code is not up to standards

The bulk of the changes here are via scripted-diff commits, or adapted cherry-picks from upstream.

### CODE REVIEW

**Review by panleone — APPROVED** [review]
tACK 090874eeda5bf323fff976db5740486f565003bf,
good work just one thing: Can you also add __slots__ to the Masternode class?

**Comment by Fuzzbawls** [comment]
> tACK [090874e](https://github.com/PIVX-Project/PIVX/commit/090874eeda5bf323fff976db5740486f565003bf), good work just one thing: Can you also add **slots** to the Masternode class?

Added slots to the MN class and rebased on master

**Review by Liquid369 — APPROVED** [review]
ACK c340533f152426106e33df9f3e78bd9c55b726bb

**Review by panleone — APPROVED** [review]
re tACK c340533f152426106e33df9f3e78bd9c55b726bb

**Pull request merged**
