### PR TITLE
[P2P] Enable Bloom filter and add new nService for light clients.

### PR DESCRIPTION
**Pull request by furszy**
As the title says:

- Bloom filter enabled by default.
- New nService for light clients added, NODE_BLOOM_WITHOUT_MN means that the node doesn't want to receive master nodes related messages (The amount of messages flood light client if it's not controlled and in some cases client doesn't need that information.)

### CODE REVIEW

**Comment by Fuzzbawls** [comment]
Will need to make a couple minor changes to the GUI to account for the new service bit, can be tacked on after this gets merged however.

Otherwise, ACK 45b90d9

**Comment by Mrs-X** [comment]
Will the new clients support SwiftTx and Obfuscation?

**Comment by furszy** [comment]
@Mrs-X yes thanks, it's 'continue' and not 'return'. I was testing the relay without MN messages on my nodes and didn't change that again, the MN messages flood the log and it's annoying for debugging.

And second,
The first version of the light clients doesn't include SwiftX and Obfuscation. Will be included on the second release.

**Comment by Mrs-X** [comment]
`And second,
The first version of the light clients doesn't include SwiftX and Obfuscation. Will be included on the second release.`

Okay, then please keep in mind that you have to re-enable "dstx" from the ppszTypeName[] structure again.

**Comment by Mrs-X** [comment]
utACK

**Comment by Fuzzbawls** [comment]
@Mrs-X good catch on the return/continue. 

@furszy any way you could rebase this down to a single commit?

**Comment by Mrs-X** [comment]
The merging script is running already...

**Comment by Fuzzbawls** [comment]
@Mrs-X lol ok. Typically I wouldn't want to merge a PR that has a superficial merge commit itself contained within, makes the commit history a bit confusing.

**Pull request merged**
