### PR TITLE
[Translations] `make translate`

### PR DESCRIPTION
**Pull request by Fuzzbawls**
Seed transifex with updated translation sources

### CODE REVIEW

**Comment by jonspock** [comment]
ACK

**Comment by Mrs-X** [comment]
NIT with the question is changing "PIVX Core" to "Pivx Core" really correct?

Besides this, ACK

**Comment by PIVX-Project** [comment]
Ack

**Comment by Fuzzbawls** [comment]
@Mrs-X rebased and added in a second commit that fixes a few instances of the coin name being referenced as `Pivx`

**Pull request merged**
