### PR TITLE
[Qt] Fix crash when inputting wrong port for network proxy

### LINKED ISSUE #507: [Wallet] Adding Proxy IP Address without a Port crashes the wallet
#### If so, please list the steps to reproduce below:
1. Open the Setting menu, press Options then select the Network tab.
2. Check the box for connect through SOCKS5 proxy
3. Delete the port number so that the port box is empty.
4. Press OK

### Expected behavior
Wallet should inform the user that a port is needed.

### Actual behavior
Wallet crashes and cannot be opened unless the registry key (\HKEY_CURRENT_USER\Software\PIVX\PIVX-Qt\addrProxy) is fixed

### Screenshots.
screenshot

### What version of PIVX Core are you using?
Official Binary 3.0.6

### PR DESCRIPTION
**Pull request by Warrows**
This PR aims to fix #507

### CODE REVIEW

**Comment by Warrows** [comment]
@Mrs-X I am not sure about that. In case of proxy misconfiguration, going without the proxy is most probably going to either not work or be something you absolutely don't want. Unless I am mistaken about what people use proxies for.

**Comment by Mrs-X** [comment]
Without proxy the wallet won't connect, or won't connect the right way, that's correct.
But when it doesn't start at all most users won't be able to correct the problem (editing the registry is NOT an option).
I'd add some explaining text to the popup (something like _"Invalid proxy settings, please review proxy settings when the wallet has started"_) and start the wallet with proxy disabled.
Not ideal, but usability wise the best compromise IMO.

**Comment by Warrows** [comment]
The problem here is that this code checks proxy settings in command-line as well as GUI.
IMO starting the wallet with proxy disabled when it's intended to be enabled is the real NOT an option. It's privacy and down the line safety which are at stake. 
If you are in a censored country or whatever with monitored network, you don't want your packets to go through an unintended routing path because you input a bad command-line argument.

I can see why we want to help people who got stuck before the fix. But I am not sure there is enough of them for this security trade-off to be worth it.

**Comment by Mrs-X** [comment]
I just thought a bit about changing the wrong proxy to something which is technically correct, but will never work (like 127.0.0.1:21), but you never know how people might have configured their computer.

So I have to agree, someone living in a censored country might not be happy if even one single packet is send via the wrong network.

There's one issue still, you can still enter an empty Proxy IP, or an invalid one like `255.255.255.255`.

`netbase.cpp` has several methodes to check IPs, so I would verify the IP as well.

**Comment by Warrows** [comment]
AFAIK IP is already checked against `netbase.cpp` `LookupNumeric` and you can't input an empty one.

**Comment by Mrs-X** [comment]
No idea how I managed to enter an empty IP, but at least `0.0.0.0` and `255.255.255.255` are possible, and it doesn't make sense to have a proxy server on a network or broadcast address.
I'd just use the same check as the one used during startup (which is `Lookup()` from netbase.cpp) and call it a day.

**Comment by Warrows** [comment]
I can't wrap my head around it but `Lookup()` does not do the job any better on my end. I tried 
`if (!(fProxyIpValid = Lookup(strAddrProxy.c_str(), addrProxy)))`
`if (!(fProxyIpValid = Lookup(strAddrProxy.c_str(), addrProxy, 0, true)))`
`if (!(fProxyIpValid = Lookup(strAddrProxy.c_str(), addrProxy, 9050, true)))` 
with no result so far. Maybe it's OS specific, I tried on debian, gotta test windows.

**Comment by Mrs-X** [comment]
I'll have a look...

**Comment by Mrs-X** [comment]
This works (and is basically the same test as in init.cpp). I've also changed the popup text in init.cpp so we can check which of the 2 tests is actually failing.

https://github.com/Mrs-X/PIVX/commit/c9ecf0237fce635731ccaf0e4c7169a0383bbd32

( BTW, there are still IPs possible which should NOT be possible, but that's out of scope for this PR )

**Comment by Warrows** [comment]
Nice catch, I missed the part about `proxyType `. Can you rebase your commit on top of mine without merging with current master? This way I'll be able to add it to this PR without changing your signature.

**Comment by Mrs-X** [comment]
> Can you rebase your commit on top of mine 

I have no idea how this can be done without write access to your repository. I'm not a  git expert unfortunately.

**Comment by Warrows** [comment]
That's not difficult:
1. On your end, checkout my branch. 
2. Cherry-pick your commit. 
3. Push this anywhere I can access it.

**Comment by Mrs-X** [comment]
Is this correct?
https://github.com/Mrs-X/PIVX/tree/Warrows-fix_507_add

**Comment by Warrows** [comment]
Nope. I guess at the first step you checked out your own branch. With the commands it would be something like this:
1. `git checkout warrows/fix_507` checkout my branch (supposing you have a remote pointing to my fork called by this name).
2. `git cherry-pick 573fb26` rebase or cherry pick your commit on top of it.
3. fix the few format things so I don't have to put a commit on top of yours when fuzzbawls OCD shows up.
4. `git commit --amend -S -a` commit the format changes.
5. `git branch -f Warrows-fix_507_add HEAD` and `git checkout Warrows-fix_507_add` move an existing branch to the current commit and checkout it. Alternatively you can checkout a new branch `git checkout -b push_warrows_507`
6. `git push -f` Force push the new commit on the existing branch on remote repo. Or push the new branch `git push --set-upstream mrs-x push_warrows_507` (supposing you called your own remote by your name.

**Comment by Fuzzbawls** [comment]
@Mrs-X you as a project maintainer can actually add commits to remote repositories. simply checking out `warrows/fix_507` and committing on top of it's head, then pushing to that same remote will add a commit to this PR.

This functionality is enabled any time a PR is made and the checkbox to allow maintainers to commit is checked. you'll see a message towards the bottom of the discussion page like
```
Add more commits by pushing to the fix_507 branch on Warrows/PIVX.
```

**Comment by Mrs-X** [comment]
@Fuzzbawls Only check out or also pulling it?

**Comment by Mrs-X** [comment]
> And please don't put in a merge commit.

This didn't work:
```
error: failed to push some refs to 'https://github.com/Warrows/PIVX.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
```
I had to merge/pull. 

The result is that we now have 11 commits instead of one, sorry. Hours wasted to add 5 minutes worth of code and the PR is a mess now.

Next time just copy and paste my code into your PR, I don't care if I show up in a PR or not.

**Comment by Warrows** [comment]
I am sorry if you feel like you lost your time. You are right, it may not be really worth it here. However if you learned something about git, that's still good to take :)
I did anyway. I actually learned one thing about git and another about github. 
And back to review we go.

**Comment by Mrs-X** [comment]
ACK and merging...

**Comment by Sieres** [comment]
ACK

**Pull request merged**
