### PR TITLE
[Doc] Remove assets-attribution.md file.

### PR DESCRIPTION
**Pull request by furszy**
Unneeded `doc/assets-attribution.md` file.

### CODE REVIEW

**Comment by random-zebra** [comment]
can remove the link in `doc/README.md` as well.

**Comment by furszy** [comment]
done, plus removed the BitcoinTalk link mention. No one is checking, nor has access, to the site anymore.

**Review by Fuzzbawls — APPROVED** [review]
ACK 2eb3d430a5106191d62347aefb2e05647b5c2727

**Review by random-zebra — APPROVED** [review]
ACK 2eb3d430a5106191d62347aefb2e05647b5c2727

**Pull request merged**
