### PR TITLE
Prepare for non-Base58 addresses [Step 3]

### PR DESCRIPTION
**Pull request by furszy**
Finished the complete removal of the base58 address class from the sources, migrated to the destination wrapper.

Plus includes bitcoin#11117 - last commit - and bitcoin#11259 as an extra.

### CODE REVIEW

**Comment by random-zebra** [comment]
Needs rebase.

**Comment by furszy** [comment]
rebased.

**Comment by random-zebra** [comment]
There is still a conflict in wallet.cpp

**Comment by furszy** [comment]
because #1663 was merged. Rebased again.

**Comment by furszy** [comment]
Updated per @random-zebra's feedback

**Comment by furszy** [comment]
good catch. no real explanation for that, just me being tired. None of those flows are used anyway.

**Comment by furszy** [comment]
Updated with last feedback solved.

**Comment by random-zebra** [comment]
merging...

**Pull request merged**
