### PR TITLE
Sapling Foundations (Build System + ZIP32)

### PR DESCRIPTION
**Pull request by furszy**
Foundational PR towards full Sapling integration. Covering, in a nutshell, the first two milestones:

#### 1) "Build & depend/deterministic system configuration support".

 Build system configuration basis for Sapling.
 Rust, libsodium,  librustzcash (Sapling rust library - up until version 0.2.0) + all of the needed crates dependencies (~34 libraries).

#### 2) "Wallet: Sapling keys & addresses management. Generation/storage/encryption following ZIP32 derivation linked to wallet's BIP44 master seed".

 New address format support, bech32 for Sapling payment addresses.
 Sapling keys deterministic derivation from the wallet's master seed (same as regular/staking addresses. wallet's seed will restore PIVs and Shielded PIVs equally).
 Sapling Keys/Addresses persistence on disk and encryption/decryption process connected to the wallet.
 Support for extended full viewing key, incoming viewing key, outgoing viewing key and spending key (Further explanation [here](https://github.com/zcash/zips/blob/master/zip-0032.rst)).

 New/Updated RPC method calls added:

 `getnewshieldedaddress` —> generating new bech32 Sapling address and adding it to the keystore encrypted/unencrypted.
 `listsaplingaddresses` —> listing wallet Sapling addresses.
 `validateaddress` → covering Sapling addresses support.

 Test Coverage.

 - Unit tests

 Sapling unit tests are under `/src/test/librust/` directory.

 - Functional tests

 Sapling functional tests are under `/test/functional/` directory following the new prefix `sapling_**.py` .

NOTE:

Remember to fetch the params using the script in util/fetch-params.sh

-----------------------

— Next PR will cover the Sapling wallet transactions' management (commits history will not be as incremental as this foundational PR, needed to do it in this way because of the substantial amount of work in the build system area. Aiming to get us directly up-to-date with the latest work in the area).

### CODE REVIEW

**Comment by furszy** [comment]
Following the team call convo, moved PR target to master.

**Comment by Fuzzbawls** [comment]
added a few new commits to flesh out issues with gitian builds and libc version requirements.

#1770 was submitted as it's own PR as I felt is was a significant enough change to warrant a dedicated PR.

**Comment by furszy** [comment]
Awesome! 🍺

**Comment by random-zebra** [comment]
Needs one last rebase, due to the changes in the CMakeLists from #1738 recently merged.
Otherwise tested (both with depends and system libs) ACK.
Really awesome job :beers:
Testing of Gitian builds will be done after #1770 is merged.

The changes to the build system and the additions to the RPC interface should be documented. Though we'll certainly add a big section for the Sapling upgrade later, so just tagging "NeedsReleaseNotes" for now.

**Pull request merged**
