### PR TITLE
[GUI] Update console widget text colors on theme change

### PR DESCRIPTION
**Pull request by dnchk**
**What does it do?**
Update text colors, clear the screen and reprint welcome message when the theme is changed. Remove misleading changeTheme call from clear, so that button named Clear only clears the screen and reprints welcome message, but doesn't change color of the text.

*Demonstation:*
https://user-images.githubusercontent.com/22178604/109415073-2fa52a80-79bf-11eb-95a3-aaea4fe6bb39.mp4

**What else do you need to know?**
We can't change the color of already printed text in QTextEdit - changes are applied only to newly displayed text. So, I considered several approaches to fix this issue:
- save all the text that will be displayed in console and reprint it on theme change;
- read all the printed text, clear the screen, change colors and then reprint the text;
- clear the screen on theme change and just print welcome message.

The last option seems to be the most reasonable. I also considered adding information message (informing that screen will be cleared) when user tries to change theme while settings console widget is open, but as the themeChanged signal is emitted starting from TopBar, it looks like not the best thing to make objects of TopBar or PIVXGUI know about visibility status of settingsConsoleWidget.

#fixes 1996

### CODE REVIEW

**Comment by random-zebra** [comment]
Hi @dnchk. Thanks for your contributions!
I agree that the third option is the most straightforward. I think it's ok to just clear the screen (without warnings, or repaint), but let's wait for other opinions.

Code wise, this looks good, and works as intended :+1:

**Comment by Fuzzbawls** [comment]
Functionality wise, I agree that this 3rd option is the most straight forward and acceptable. Would just squash the 3 commits into a single commit though.

**Comment by furszy** [comment]
hello, thanks for the contribution. Some feedback (results tested on macOS):

> We can't change the color of already printed text in QTextEdit - changes are applied only to newly displayed text

This initial assumption isn't right. We can, and we are changing `QTextEdit` texts styling in many areas of the sources on-demand.
The problem that have seen here is that we are using rich text inside the document for the styling and we aren't enabling the rich text support. So, the solution should be way simpler, just need to enable the rich text support (`setAcceptRichText(true)`).

The following patch is working properly on macOS, updating the text document styling on demand without any document clear requirement:
```
try this
Index: src/qt/pivx/settings/settingsconsolewidget.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/qt/pivx/settings/settingsconsolewidget.cpp b/src/qt/pivx/settings/settingsconsolewidget.cpp
--- a/src/qt/pivx/settings/settingsconsolewidget.cpp    (revision a51b254f276cad8f23549f7f2eb5d5fb510446ad)
+++ b/src/qt/pivx/settings/settingsconsolewidget.cpp    (date 1616509199078)
@@ -251,6 +251,7 @@
     setCssProperty({ui->left, ui->messagesWidget}, "container");
     ui->left->setContentsMargins(10,10,10,10);
     ui->messagesWidget->setReadOnly(true);
+    ui->messagesWidget->setAcceptRichText(true);
     ui->messagesWidget->setTextInteractionFlags(Qt::TextInteractionFlag::TextSelectableByMouse);
 
     // Title
``

**Comment by random-zebra** [comment]
> The following patch is working properly on macOS, updating the text document styling on demand without any document clear requirement:

This is not working for me on linux though.

**Pull request closed without merging**
