### PR TITLE
Fix the major block corruption issues

### PR DESCRIPTION
**Pull request by presstab**
When the client is not properly shutdown it can cause the database to get into a state where a block and index have been written to disk, but the corresponding metadata has not been written to disk. This adds various assertions and attempts to correct the faulty state when the client is initialized. This addresses https://github.com/PIVX-Project/PIVX/issues/69

### CODE REVIEW

**Comment by jonspock** [comment]
utACK

**Comment by Fuzzbawls** [comment]
utACK

**Comment by PIVX-Project** [comment]
utACK

**Comment by jonspock** [comment]
utACK

**Comment by thebitcoiner** [comment]
Please also change the help message to reflect the new default.

https://github.com/PIVX-Project/PIVX/blob/master/src/init.cpp#L283

**Comment by presstab** [comment]
@thebitcoiner thanks. Added to the latest commit.

**Comment by thebitcoiner** [comment]
thanks!

**Comment by Fuzzbawls** [comment]
NIT: when an inconsistency is found, could we allow init to continue by passing `-reindex` by itself, as well as the current `-forcestart`

(ie, `-reindex` will force a rebuild of the block database, so `-reindex -forcestart` shouldn't be necessary)

**Comment by sugar84** [comment]
good news everyone!

**Pull request merged**
