### PR TITLE
[Net] Add Tor v3 hardcoded seeds

### PR DESCRIPTION
**Pull request by Fuzzbawls**
Adapted from https://github.com/bitcoin/bitcoin/pull/21560, this adds support for Tor v3 hardcoded seed nodes.

Upstream PR description:

> * Add a few hardcoded seeds for TorV3
>   * As the bitcoin-seeder doesn't collect TorV3 addresses yet, I have extracted these from my own node using a [script](https://gist.github.com/laanwj/b3d7b01ef61ce07c2eff0a72a6b90183) and added them manually. This is intended to be a temporary stop gap until 22.0's seeds update.
> * Change hardcoded seeds to variable length BIP155 binary format.
>   * It is stored as a single serialized blob in a byte array, instead of pseudo-IPv6 address slots. This is more flexible and, assuming most of the list is IPv4, more compact.
>   * Only the (networkID, addr, port) subset (CService). Services and time are construed on the fly as before.
> * Change input format for nodes_*.txt.
>   * Drop legacy 0xAABBCCDD format for IPv4. It is never generated by makeseeds.py.
>   * Stop interpreting lack of port as default port, interpret it as 'no port', to accomodate I2P and other port-less protocols (not handled in this PR). An explicit port is always generated by makeseeds.py so in practice this makes no difference right now.

Marked as WIP for now because we need more Tor v3 nodes on mainnet for this to really be of use to end users, but this is currently testable on testnet as we already have a number of Tor v3 capable nodes there (which have been added to the hardcoded seeds here)

### CODE REVIEW

**Comment by furszy** [comment]
Have set up two nodes to have them as seeds, will leave them running 24/7:

Public onion address in mainnet:
`furszycdwjsgeevkwsdg5hsattsvaw4i6y3xkzdvb7zez24uwhjjddid.onion`

Public onion address in testnet:
`x4ys3tklrydij35o7m7x4f2baoolmew3q45r7dvlpdkzuoogfb3lbfqd.onion`

The first address is a bit special ✌️.

**Comment by Fuzzbawls** [comment]
Updated with 5 mainnet full time Tor v3 nodes, ready for review

**Review by random-zebra — APPROVED** [review]
ACK 4aec9352e245d1f44d6f746b1edf3bff2e093b29

**Review by furszy — APPROVED** [review]
ACK 4aec935

**Pull request merged**
