### PR TITLE
[Cleanup] Use C++11 nullptr instead of NULL

### PR DESCRIPTION
**Pull request by Fuzzbawls**
Scripted diff to replace all `NULL` macros with the C++11 `nullptr` keyword

```bash
-BEGIN VERIFY SCRIPT-
sed -i 's/\<NULL\>/nullptr/g' src/*.cpp src/*.h src/*/*.cpp src/*/*.h src/qt/*/*.cpp src/qt/*/*.h src/qt/pivx/*/*.cpp src/qt/pivx/*/*.h src/wallet/*/*.cpp src/test/*/*.cpp src/wallet/*/*.h
sed -i 's/Prefer nullptr, otherwise SAFECOOKIE./Prefer NULL, otherwise SAFECOOKIE./g' src/torcontrol.cpp
sed -i 's/tor: Using nullptr authentication/tor: Using NULL authentication/g' src/torcontrol.cpp
sed -i 's/METHODS=nullptr/METHODS=NULL/g' src/test/torcontrol_tests.cpp src/torcontrol.cpp
sed -i 's/nullptr certificates/NULL certificates/g' src/qt/paymentserver.cpp
sed -i 's/"nullptr"/"NULL"/g' src/torcontrol.cpp src/test/torcontrol_tests.cpp
-END VERIFY SCRIPT-
```

### CODE REVIEW

**Review by random-zebra — APPROVED** [review]
utACK a3346e25bee7f237ba455efc380c0002900e7b53

**Review by PeterL73 — DISMISSED** [review]
tACK https://github.com/PIVX-Project/PIVX/commit/54e116883de87985e128858052afe90d8bc4581d

Nit: `src/qt/paymentserver.cpp` does not contain `NULL certificates` so `sed -i 's/nullptr certificates/NULL certificates/g' src/qt/paymentserver.cpp` could be skipped

**Review by panleone — APPROVED** [review]
utACK a3346e25bee7f237ba455efc380c0002900e7b53

**Review by panleone — APPROVED** [review]
re-utACK 58e254e2e734e561201794274b39490eb0d4ce33
changes are consistent with the script

**Review by Liquid369 — APPROVED** [review]
tACK 58e254e2e734e561201794274b39490eb0d4ce33

**Pull request merged**
