### PR TITLE
[Qt] Feature: setstakesplitthreshold value set in Qt GUI

### PR DESCRIPTION
**Pull request by lex-dev1**
This is the implementation of the feature request #424 
 
image

Requested feature has been completed considering current architecture of CWallet class.

This architecture raised few concerns that we would like to bring to everyone's attention. We believe some attention should be paid to the future possibility of refactoring done for this class and setting up a separate issue if approved by core team task specifically for that purpose.

We would like to bring current implementation with public fields in this class to core team's attention. The way it's currently implemented may result in the possibility of future unstable code and ultimately bugs in application in general.

CWallet class as a Base class allows the derived classes to get direct access to CWallet class fields and alter their status without regard for its inner implementation. Getter/setter allows to solve this issue by means of controlling input parameters in the Base class.

It is required to check the existing public fields and in cases where it is necessary to make class fields private and accessible through setter/getter, which will allow to control their alteration.

This task will also require additional work on tests coverage in addition to refactoring.

**This is an updated PR, previous discussion [here](https://github.com/PIVX-Project/PIVX/pull/456)**

### CODE REVIEW

**Comment by Mrs-X** [comment]
utACK and merging...

**Comment by Mrs-X** [comment]
Oh, and your (very appreciated) comment about encapsulating members with get/set methods is correct of course.
Problem is, there are tons of code places which would need refactoring and a day has just 24 hours, so it's usually postponed.

But it would be nice if someone with a solid C++ background would compile a list with those findings for the (unlikely) case we would find more time for this in the future.

**Comment by datasubsystems** [comment]
@Mrs-X thank you for your kind feedback. If senior developer review will be requested someone indeed may find time for other findings as well as for improving overall QA of the project. Sacrificing code for the speed may accumulate technical debt for the project and have consequences. The reason why pivx doesn't have time for things like this is an issue of available resources (relatively small dev team for $600M growing blockchain project no?)

**Comment by Sieres** [comment]
ACK

**Pull request merged**
