### PR TITLE
[Cleanup] Declare single-argument (non-converting) constructors "explicit"

### PR DESCRIPTION
**Pull request by Fuzzbawls**
Declare single-argument (non-converting) constructors `explicit`.

In order to avoid unintended implicit conversions.

Coming from https://github.com/bitcoin/bitcoin/pull/10969

Added a new CI lint job that uses `cppcheck` to indicate any regressions or new introductions. This lint framework can be expanded on to catch other static analysis warnings in future PRs.

### CODE REVIEW

**Review by panleone — DISMISSED** [review]
utACK 18a9d6cd373437243355474ba55801a18db364c7

**Review by Duddino — APPROVED** [review]
utACK 18a9d6cd373437243355474ba55801a18db364c7

**Review by Liquid369 — APPROVED** [review]
utACK 18a9d6cd373437243355474ba55801a18db364c7

**Comment by Fuzzbawls** [comment]
Rebased on master to resolve conflicts

**Review by panleone — APPROVED** [review]
utACK 1cc9a805eaa4fd8b84b660e439dfa517e9b1f1bb

**Review by Liquid369 — APPROVED** [review]
utACK 1cc9a805eaa4fd8b84b660e439dfa517e9b1f1bb

**Pull request merged**
