### PR TITLE
[Qt] Show progress percent for zpiv reindex operations

### PR DESCRIPTION
**Pull request by Fuzzbawls**
`-reindexaccumulators` and `-reindexzerocoin` can take a considerable
time to complete depending on system hardware. Lets show a progress percent
 similar to `VerifyDB()` on the splashscreen.

### CODE REVIEW

**Comment by Fuzzbawls** [comment]
Rebased now that #609 has been merged

**Comment by Fuzzbawls** [comment]
looks like the `if` conditions weren't updated for v2 zPIV.

@presstab should the `if` instead read as
```c++
if (!listMissingCheckpoints.empty() && chainActive.Height() >= Params().Zerocoin_Block_V2_Start()) {
```
since we set `pindex` to `Params().Zerocoin_Block_V2_Start()` for looping just a few lines below (thus ignoring any block height prior to v2 start height)?

**Comment by Fuzzbawls** [comment]
adjusted some of the logic for these two reindex options, as well as added checks to see if they should even run based on the client's `chainActive` height. (no point in running either if the local `chainActive` is at a height below the respective zPIV activation values.

**Comment by Warrows** [comment]
ACK bed79e2

**Comment by Fuzzbawls** [comment]
@Mrs-X good point, moved it up a bit.

**Pull request merged**
