### PR TITLE
[Policy] Child-pays-for-parent Implementation + CoinAge priority removal

### PR DESCRIPTION
**Pull request by random-zebra**
This PR implements CPFP transaction selection mechanism, which is the simplest "fee bumping technique" (we might want to consider implementing RBF too later on).
The algorithm in `CreateNewBlock` now selects transactions based on their feerate, inclusive of unconfirmed ancestor transactions.  This means that a low-fee transaction can become more likely to be selected if a high-fee transaction that spends its outputs is relayed: the fee burned in the "child" transaction, actually pays for the parent tx too (hence the name).

This PR also removes completely the (already deprecated) notion of coinage-based priority and "free transactions area".

Changes backported / adapted from:

- bitcoin#7600 [Suhas Daftuar]
- bitcoin#8287 [MarcoFalke]
- bitcoin#8295 [Suhas Daftuar]
- bitcoin#9138 [Alex Morcos]
- bitcoin#9602 [Alex Morcos]
- bitcoin#11847 [Suhas Daftuar]

### CODE REVIEW

**Review by furszy — COMMENTED** [review]
Looking really nice, light ACK 1580748eda1e649128fdc51c0e4d2025df013ec9 .
Will get deeper.

**Comment by random-zebra** [comment]
Rebased, fixing conflicts.

**Comment by random-zebra** [comment]
Rebased.

**Comment by random-zebra** [comment]
Rebased

**Review by furszy — COMMENTED** [review]
re-code ACK ce30647

**Comment by furszy** [comment]
Rebase needed.

**Comment by random-zebra** [comment]
Rebased again.

**Comment by furszy** [comment]
will need another rebase.

**Comment by random-zebra** [comment]
Rebased on master, fixing conflicts, and added last commit for #2469

**Comment by furszy** [comment]
Got broken after the rebase, will need to do some changes due the serialization framework changes.

**Comment by random-zebra** [comment]
> will need to do some changes due the serialization framework changes.

Yep, will fix this soon.

**Comment by random-zebra** [comment]
Fixed

**Review by Fuzzbawls — APPROVED** [review]
utACK f5b2e5490d4559caf5ba50fd4db6e4292b5917e6

**Review by furszy — APPROVED** [review]
re-ACK f5b2e549 after rebase and last commit.

left two comments that can be tackled in a follow up PR, merging..

**Pull request merged**
