### PR TITLE
[Wallet] Speedup coinstake creation removing redundancies.

### PR DESCRIPTION
**Pull request by furszy**
Improvement over the coinstake transaction creation flow, it will speed up the process a lot.
Removing a for loop redundancy (it was looping over the available outputs twice), removing a simply bad usage of unique_ptr, guarding `chainActive` access, removing unused zPoS code and few smaller warnings fixes.

### CODE REVIEW

**Review by random-zebra — APPROVED** [review]
nice cleanup :+1: utACK 4f5329c6a5fa63a77ed3145fa73faf274a6c20f6

**Review by Fuzzbawls — DISMISSED** [review]
ACK 4f5329c6a5fa63a77ed3145fa73faf274a6c20f6

**Comment by random-zebra** [comment]
Needs rebase

**Comment by furszy** [comment]
rebased

**Review by random-zebra — APPROVED** [review]
re-utACK 9fb497d3089a71292441e973c100f3aa6ac0f5b6 and merging...

**Pull request merged**
