### PR TITLE
[WIP][Validation] Back ports up to "bye bye" boost signal usages.

### PR DESCRIPTION
**Pull request by furszy**
A second attempt to solve #1840 in a more cleaner way.

Made my own way up to remove most of the the boost signal usages. Had to adapt some PRs from upstream with further customizations as we aren't one to one with them.

Base upstream PRs are the following ones:
* #9010
* #10179
* #13743
* #11783
* #10244 (only the handler interface)

### CODE REVIEW

**Comment by Fuzzbawls** [comment]
Quick note: need to use `for j in $(seq 1 6)` in the scripted-diff to use `std::placeholders` as our `walletmodel.cpp`'s `NotifyAddressBookChanged` signal has 6 placeholders, so the last one is being missed.

**Comment by furszy** [comment]
good catch, updated.

**Comment by furszy** [comment]
Reworked the PR one more time, added a good number of changes, should be ready to go now (long way to get to this point..).
I'm finally able to compile the project in MacOS again.

**Comment by furszy** [comment]
between #2082, #2192 and few others added in #1726, can finally close this, it ended up being a deep rabbit hole..

**Pull request closed without merging**
