### PR TITLE
[Cleanup] Removing unused and unneeded functions and members

### PR DESCRIPTION
**Pull request by furszy**
Going further with the cleanup, have removed several unused and not needed functions and files from the GUI and the wallet. The `LongDescriptionRole` (which was calling to the `TransactionDesc` class) is not needed anymore, just a remanent of the previous GUI. Then have gone down the rabbit hole and cleaned the methods and fields that were connected to the removed function and currently are not needed anymore.

### CODE REVIEW

**Review by random-zebra — DISMISSED** [review]
Guess a rebase issue with commit-names, but 2dc45db63b48e57ffd4c26e9f6aec4365a0b0bba was probably meant to be squashed in 9144be022336cc8e7b44f2bb3c47f16fb4cea2e4.

Aside from this, all good. utACK

**Comment by furszy** [comment]
yeah, done 👍

**Review by Fuzzbawls — APPROVED** [review]
utACK 5a4e41697ffd1e5744d0bca25d515f860744f07a

**Review by random-zebra — APPROVED** [review]
utACK 5a4e41697ffd1e5744d0bca25d515f860744f07a

**Pull request merged**
