### PR TITLE
[RPC] Register calls where they are defined

### PR DESCRIPTION
**Pull request by Liquid369**
Follow up to PR #1702 

Bitcoin backport https://github.com/bitcoin/bitcoin/pull/7766/

Splitting out registration methods from rpcserver.cpp.

Making for easier RPC command additions and not needing to rebuild everything in rpcserver.h includes.

### CODE REVIEW

**Comment by random-zebra** [comment]
Thanks for the submission @Liquid369 !
This should be rebased on top of #1702, to not revert its changes (e.g. `threadSafe` and `reqWallet` members have been removed from `CRPCCommand`s), and avoid future conflicts after its merge.

**Comment by random-zebra** [comment]
Also, it does not compile currently.

**Comment by furszy** [comment]
this will not work if it's not connected to the code. Need to back port the register interface and connect it to init.cpp and test_pivx.cpp. 
And there are duplicated functions `RegisterBlockchainRPCCommands`. Need to have unique names on each rpc file.

**Comment by Liquid369** [comment]
Ah yes I forgot test_pivx.cpp. My apologies on init.cpp being missed. I had done the work and realized my repo was about 400ish commits behind and then refactored. I guess I missed init.cpp additions for adding in rpc/register.h

Do you have a naming suggestion as per the changes I am bringing in for the duplicated functions? 

I will rebase ontop of 1702 for fixing conflicts and then fix the subsequent issues pointed out by furzy

**Comment by Liquid369** [comment]
It doesnt even show my Makefile changes might not have staged those. 

I will work on it just awaiting suggestions I asked about above.

**Comment by furszy** [comment]
just use the rpc file name for the register methods. Same convention as in the other places.

**Comment by Liquid369** [comment]
I think I am going to close this and reopen it.
After finishing the work on bitcoin#7766
I noticed in the comments it is worked ontop of bitcoin#7307 
https://github.com/bitcoin/bitcoin/pull/7307


So rebase ontop of #1702 
Backport bitcoin#7307 
Backport bitcoin#7766

Alongside other comments in this.

Agreed?

**Comment by furszy** [comment]
#1702 contains 7307. You can only work on 7766.

Feel free to close it and open a new one or force push the work here.
Just take your time to understand the flow and test it locally.

**Pull request closed without merging**
