### PR TITLE
[Validation][Test] Fix concurrency issues in ActivateBestChain + optimization

### PR DESCRIPTION
**Pull request by furszy**
Made some back ports and adaptations to validate further the work introduced in #2203 and #2209.
Now that the scheduler thread is processing most of the chain events, the callbacks execution order must be verified to dispatch the events serially, ensuring a consistent memory state in each event processing invocation.
There are some concurrency issues solved, as well a an optimization for larger chains for the ABC workflow. Each commit details them well.

List:
#7917 (only fb8fad1586ced69fa37c665a11916ae4c4d0df05)
#12988
#13023
#13247
#13835

This is built on top of #2284 (and the reason that made me notice that problem). So, 2284 comes first, then this one.

### CODE REVIEW

**Comment by random-zebra** [comment]
#2284 merged. This needs rebase

**Comment by furszy** [comment]
rebased.

**Review by Fuzzbawls — APPROVED** [review]
ACK 50dbec59277e25f3e24f447773c12b60f360427a

**Review by random-zebra — APPROVED** [review]
ACK 50dbec59277e25f3e24f447773c12b60f360427a and merging...

**Pull request merged**
