### PR TITLE
[Wallet] Look at last CoinsView block for corruption fix process

### PR DESCRIPTION
**Pull request by presstab**
This addresses https://github.com/PIVX-Project/PIVX/issues/106

### CODE REVIEW

**Comment by jonspock** [comment]
utACK. This happened to me a couple of times. I will test with this code if it happens again

**Comment by Fuzzbawls** [comment]
ACK b826305

Though do note that the test was done on a pre-corrupted datadir. none of my own datadirs have shown any corruption.

**Comment by presstab** [comment]
Every instance users with #106 that I have given a binary built from this PR to has reported it worked.

**Comment by presstab** [comment]
Temporary testing code got slipped in. Rebased and squashed.

**Comment by Fuzzbawls** [comment]
ACK f63c1a3

**Pull request merged**
