### PR TITLE
[Build] Bump master to 5.4.99

### PR DESCRIPTION
**Pull request by furszy**
Now that 5.4.0 has been released, bump master to 5.4.99

### CODE REVIEW

**Review by random-zebra — APPROVED** [review]
utACK 139a314f46c1f54ad81a6af50ddbc4fd0d09da36

**Comment by Fuzzbawls** [comment]
need to also update https://github.com/PIVX-Project/PIVX/blob/master/build-aux/snap/snapcraft.yaml#L5 to `5.4.99`

**Comment by furszy** [comment]
done, updated.

**Review by random-zebra — APPROVED** [review]
utACK f11e1bbb47338585cb14bf1b425e27aa47b98002

**Pull request merged**
