### PR TITLE
[Refactor] Reorder mnw processing and validation

### PR DESCRIPTION
**Pull request by random-zebra**
Extracted from #2421 (and based on top of it) so #2550 can be merged in between.

### CODE REVIEW

**Review by furszy — DISMISSED** [review]
good, ACK 70ee3c66c156b30f8900130a0a413d45184d38d0

**Review by Fuzzbawls — DISMISSED** [review]
ACK 70ee3c66c156b30f8900130a0a413d45184d38d0

**Comment by random-zebra** [comment]
Rebased on master, now that #2611 has been merged.

**Review by furszy — APPROVED** [review]
utACK e8559fc2638045909c9e34c0cb843e8d3069e2b5 after rebase

**Pull request merged**
