### PR TITLE
Update rust.mk

### PR DESCRIPTION
**Pull request by AndersonTYLER**

### CODE REVIEW

**Comment by Fuzzbawls** [comment]
NACK

We don't support 32-bit windows builds anymore. also, you failed to provide a description.

**Comment by furszy** [comment]
true, no 32-bit windows support anymore. Thanks for trying it anyway, please try next time to provide a good description of the changes involved in the PR following the contributions guidelines.
Closing this.

**Comment by AndersonTYLER** [comment]
Ah ok, it works though with those changes, i've been able to compile it on 32 bits. 

If you  change your mind, just change those lines, could help anyone who 'd like to compile 32 bits wallets

**Comment by furszy** [comment]
Yeah we know. It was not included there on purpose. https://github.com/PIVX-Project/PIVX/issues/1315

**Pull request closed without merging**
