### PR TITLE
[test] fix coinstake input selection on secondary chains.

### PR DESCRIPTION
**Pull request by furszy**
Fixing an inconsistency in the PoS validations unit tests, specifically in the secondary chain branches acceptance test cases.

As the wallet is not prepared to follow several chains at the same time, need to manually remove from the stakeable utxo set the coinstake inputs that were used on the previous blocks of the parallel chain so they are not used again in the block that is being crafted.

### CODE REVIEW

**Comment by random-zebra** [comment]
I've spent a bit of time with this test, to debug the last intermittent failures.
There are two more issues, aside from the one fixed here.

1) failures due to `bad-txns-premature-spend-of-coinbase-coinstake`:
when the wallet checks the maturity of a coin, the depth is calculated considering the current tip. Such coin could result immature if spent in a forked block, at a lower height (either inside a regular tx, or a coinstake).
Fix --> <https://github.com/random-zebra/PIVX/commit/0957885a5c01243228af6afa39e998ffcf021db0>

2) (a bit harder and fun to track) failures due to `bad-txns-inputs-spent-fork-post-split` in G3.
This is because when the input to spend in `gTx` (to be mined in block G) is selected, this input could be already spent either in block `D3` or `E3` (which are accepted but not connected yet). 
When `gTx` is duplicated in G3, in such cases, the longest chain could not be connected anymore, as it would contain a double spend.
Fix --> <https://github.com/random-zebra/PIVX/commit/e1ddfb6e2efa426c43e3456d22726c204c1773e4>

**Comment by furszy** [comment]
Awesome findings zebra 👌👌, would love to clone you.
Cherry-picking them.. 🥃 .

**Review by random-zebra — APPROVED** [review]
ACK 47448c88da1537899321b7ca5e3e9692a2846fdd

**Review by Fuzzbawls — APPROVED** [review]
ACK 47448c88da1537899321b7ca5e3e9692a2846fdd

**Pull request merged**
