### PR TITLE
[GUI][Bug] StartAll stop starting already Enabled MN

### PR DESCRIPTION
**Pull request by Liquid369**
This is to fix as described in #2408 

As per the discussion, @furszy suggested checking this way instead.

Hopefully this is how you wanted it

### CODE REVIEW

**Review by random-zebra — CHANGES_REQUESTED** [review]
Aside from introducing trailing whitespaces (making the linter complain), this code does not even compile.
There is no `IsMnEnabled`, nor `hasServiceDataChange` members in the `MNModel`. Also the variable `mneConf` does not exist.

I think that furszy was just giving you the "general idea" in #2408.
The point is restarting the masternode only if it is inactive, or some data has been changed inside the masternode.conf file.

Honestly, I don't think this is a UX issue. `StartAll` is to (force) start all masternodes (for whatever reason), otherwise there's `Start Inactive/s` (and the possibility to start a single one with the context menu).

Further, with DMN (#soon) there will be no need to "start" masternodes anymore.
Masternodes will be simply registered __once__, and they will be automatically reinserted in the list when they turn back online after a downtime (so no further intervention from the controller will be required).

**Comment by Liquid369** [comment]
Got it.

**Comment by kyeno** [comment]
> Honestly, I don't think this is a UX issue. `StartAll` is to (force) start all masternodes (for whatever reason), otherwise there's `Start Inactive/s` (and the possibility to start a single one with the context menu).

I disagree here, Zebra. If this is by design, this kind of button should definitely be placed elsewhere, be smaller than "Start Inactive/s" and have some warnings and/or confirmations around - hence UX issue. We want to build user-friendly product, right? :)

**Comment by random-zebra** [comment]
> I disagree here, Zebra. 

The point is that there is a use case for re-starting already-active masternodes: essentially when the new broadcast would have different data (thus why furszy suggested [to implement] a function named hasServiceDataChange).

I agree that giving more relevance to "Start Inactive/s" (over "Start All") could prevent some error, thus possibly be more user friendly... or maybe even a simple confirmation pop-up dialog after "Start All" could do.
But, again, this whole UI flow will be obsolete soon after the new release is out, so IMO it doesn't make much sense to focus on this now.

**Comment by furszy** [comment]
@kyeno check #2408 please. I detailed the issue and the solution there. There is a missing validation in the flow before broadcast the mnb message. Can be added for v6.0 for sure.
liquid closed this PR because the code was just bad. Not for other reason. If it's not him, i will fix the problem in another PR.
As zebra said, it will get obsolete after moving to DMN but it will still be usable in the transition period.

Side point, i understand that in front of users' eyes, everything is an GUI/UX problem. But at least in this case, it's not related to the GUI/UX, it's the backend not checking if the masternode exists locally and its status before broadcast the message.

**Comment by Liquid369** [comment]
Yeah, I had wrongly assumed the example was from functions we did have. Im on the fence of doing the work because is it relevant if entirely it will not be needed when DMN is out with 6.0? Its more of a fix for now and I do not see you guys doing another release at this present point for this to be added.

If its something that is wanted and will be used of course I will do the actual leg work to implement proper functions for checking on this data/status changes. Just let me know 👍

**Comment by kyeno** [comment]
All understood and indeed no sense of reworking this if 6.0 changes a lot of logic here.
Thanks for explanation. 👍

**Pull request closed without merging**
