### PR TITLE
[budget] Clean pre-v5 consensus guards for proposal start block and max payment amount

### PR DESCRIPTION
**Pull request by furszy**
Cleaning pre-v5 consensus guards for the proposal start block and max payment amount validation.

### CODE REVIEW

**Comment by random-zebra** [comment]
We cannot do this yet, or we risk forking the network, as we have still active proposals that were submitted before V5 (thus with old rules). Note that the new rules apply only if the proposal's *block-start* is after v5 enforcement.

There are 3 of these proposals. Two of them will expire after then next cycle. But the last one still needs 4 more cycles (it has a payment count of 12, which is not even allowed by the new rules).

**Comment by furszy** [comment]
No need to merge this one now, let's leave it open until we can do it.

**Review by random-zebra — APPROVED** [review]
utACK 3a9476c4b7bd7e852343d591831100f28803ed15

**Review by Fuzzbawls — APPROVED** [review]
ACK 3a9476c4b7bd7e852343d591831100f28803ed15

**Pull request merged**
