### PR TITLE
Generic event handler interface

### PR DESCRIPTION
**Pull request by furszy**
A set of commits decoupled from #1973, solving #1840.

The final goal is #1973 but the scope there got pretty big and is requiring more previous back ports (like 9725 among others that are an entire branch of back ports by themselves) so.. better to start merging this sooner rather than later to not continue having issues on macOS deployment (or well, more specifically issues with newer boost versions).

### CODE REVIEW

**Review by random-zebra — DISMISSED** [review]
Really nice stuff. ACK 0eb456419dbd1031892b9f094d2250177b920d22.
Just a couple nits.

**Comment by furszy** [comment]
Done, nits tackled.
Plus added a last commit guarding the `UnregisterValidationInterface` function (taken from 1973 as well).

**Review by random-zebra — APPROVED** [review]
utACK a09990a5f6b7fc9ef9f9f9bf643e046f7b2f1792 after the changes.

**Review by random-zebra — APPROVED** [review]
ACK 30fcd32452338ebc5e9bfc3fb42f862153cc3d82

**Review by Fuzzbawls — APPROVED** [review]
ACK 30fcd32452338ebc5e9bfc3fb42f862153cc3d82

**Pull request merged**
