### PR TITLE
[Scripts] LogPrint(f) scanner script

### PR DESCRIPTION
**Pull request by soniccrypto**
Script to identify errorneous LogPrint and LogPrintf calls (calls that do not have matching number of format specifiers and supplied arguments to the calls).

### CODE REVIEW

**Comment by derekhansen** [comment]
Would we want to run this in the before_script of .travis.yml so that the build is continuously checking it?

**Comment by presstab** [comment]
ACK . Worked well for me.
```
./logprint-scanner.py 
Incorrect number of arguments for LogPrint(f) statement found.
/home/pt/workspace/pivx/src/wallet.cpp:3772
Line =             LogPrintf("%s: fee of %s is too large to insert into last output\n");
numRelevantCommas = 0, numRelevantPercents = 2

Incorrect number of arguments for LogPrint(f) statement found.
/home/pt/workspace/pivx/src/miner.cpp:237
Line =                     LogPrintf("%s : found invalid input %s in tx %s", __func__, txin.prevout.ToString());
numRelevantCommas = 2, numRelevantPercents = 3

# of incorrect instances: 2
```

@derekhansen yes the intent will be to add this to Travis

**Comment by PeterL73** [comment]
Hi,
Great to have an extra check, but I think multi lines aren't handled correctly. Further more double % should be ignored. I don't know if this is the correct way to go, but I made a pull request on the original @soniccrypto branch to fix this.

**Comment by Fuzzbawls** [comment]
Squashed into a single commit

**Pull request merged**
