### PR TITLE
[RPC] Register calls where they are defined

### PR DESCRIPTION
**Pull request by Liquid369**
Follow up to PR #1702
This time it was based off the #1702 branch so it is compiling now.

Bitcoin backport bitcoin#7766

Splitting out registration methods from rpcserver.cpp.

Making for easier RPC command additions and not needing to rebuild everything in rpcserver.h includes.

Split most functions to their respective files,
PIVX specific masternode/budget commands are moved to respective

rpc/masternode.cpp
rpc/budget.cpp

Test functions are now included.

Closing #1714 

I believe this is neater and done properly, sorry GIT is a pain sometimes.

EDIT: I see 5 commits urgh, rebase? or.. not sure. I apologize.

### CODE REVIEW

**Comment by furszy** [comment]
Check that you squashed master's recently merged commits inside your commit. Check the code, it has #1715 and #1705 inside.

**Comment by Liquid369** [comment]
Ah crap.

Suggestion on easy fix? 

I am not the best with rebasing/squashing

**Comment by furszy** [comment]
1) `git reset HEAD~ --soft`
2) remove the changes included in master manually.
3) commit the changes again.

**Comment by Liquid369** [comment]
Did exactly that and it reverting the changes....?

**Comment by Liquid369** [comment]
Alright I got it.

**Comment by random-zebra** [comment]
There are several failures, that should be fixed, in the functional test suite.
Also, this should be rebased on master, now that  #1702 has been merged (`git rebase -i master` and remove the `pick` lines of the four commits from #1702).

**Comment by Liquid369** [comment]
I will rebase removing the #1702 commits.

As far as the tests go I have to look and see what specifically failed not familiar with your full test suite.
I see one as a disable wallet issue and I will look into what they are replicating.

Might be some ifdefs from the refactoring missed.

Thanks for the rebasing assistance.

**Comment by random-zebra** [comment]
@Liquid369 you can check the tests locally, launching the individual test files (from the `test/functional` directory), or the full test suite with `./test/functional/test_runner.py` (first run will take a while to create a cached blockchain, in the successive runs you can reuse it doing `./test/functional/test_runner --keep-cache`).

**Comment by furszy** [comment]
hey, this needs a rebase. 
Dunno if you are still planning to work on this or should we take it. Let us know.

**Comment by Liquid369** [comment]
I plan on finishing, this week I just started getting back into things after the baby. I can rebase off current master? Or should I rebase the prior PR specifically, master should work since merged? 

Will try to start today/tomorrow on the rebase and get PR updated.

**Comment by Liquid369** [comment]
tried rebasing only messing it up more.

**Comment by random-zebra** [comment]
Replaced by #1926

**Pull request closed without merging**
