### PR TITLE
Convert main.cpp to unix format, update .clang-format from bitcoin, r…

### PR DESCRIPTION
**Pull request by jonspock**
…un on many source files

### CODE REVIEW

**Comment by PIVX-Project** [comment]
Ack

**Comment by Mrs-X** [comment]
utACK

**Comment by presstab** [comment]
ack

**Comment by Fuzzbawls** [comment]
Concept ACK
Particular Implementation proposed here NACK

Reviewing a commit of this scale is tedious at best, and numerous readability issues have been introduced due to the automated nature of clang-format.

`src/main.cpp` stil DOES need to have it's line endings fixed, which unfortunately will result in a diff that is not pretty, but the rest of this commit (IMHO) should be dropped or broken out into smaller, more atomic commits and/or PRs.

**Pull request merged**
