### PR TITLE
[Cleanup] Remove deprecated OpenSSL Bignum support

### PR DESCRIPTION
**Pull request by Fuzzbawls**
We've been using GMP for Bignum support by default already, and now that
 zerocoin has been replaced, there is little reason to keep the OpenSSL
 fallback Bignum support anymore.

### CODE REVIEW

**Comment by Fuzzbawls** [comment]
rebased now that #2278 has been merged

**Review by random-zebra — APPROVED** [review]
utACK 6e25d8320eb9f8f4c2c6f7cd09dd299126cdb454

**Review by furszy — APPROVED** [review]
ACK 00a32dd

**Review by random-zebra — APPROVED** [review]
ACK 00a32dd0f3782262527843f31e9a74a184bd0f27 and merging...

**Pull request merged**
