### PR TITLE
[Core] Locked memory manager

### PR DESCRIPTION
**Pull request by random-zebra**
First commit adapts btc d7d187e8a451ae946fa14cead7962edbe0046f12.
Then backport the last 3 commits of bitcoin#8753, which were left out in #1488.

### CODE REVIEW

**Review by furszy — COMMENTED** [review]
initial quick code review ack 7eab0b59908baded7006c972c814f59c3cab9b6e .

I spent more time checking what should go next than reviewing this code, would be good to go further and look at: #9063 ,#9070, #15117 for example. Plus the algo change introduced in #12048.
We could leave them for another PR or port all at once here. I'm fine either way, all of this changes should be pretty scoped to the private key memory allocation.

**Comment by random-zebra** [comment]
I think this can be merged as is.

**Review by Fuzzbawls — COMMENTED** [review]
Overall good. few nits that could simply be addressed in #2266 if this is merged first. Other than that, `src/support/lockedpool.cpp` is being included in multiple libs when it doesn't need to be for CMake builds.

**Comment by random-zebra** [comment]
> src/support/lockedpool.cpp is being included in multiple libs when it doesn't need to be for CMake builds

Yeah, that's because `allocators.cpp` was originally included in both libs (for CMake, as well as for native builds).
Fixed now.
Also rebased on master and fixed `NULL`-->`nullptr`.

**Review by Fuzzbawls — APPROVED** [review]
ACK 1c04a3500848fb3c7513cd352b7422b4b131f42d

**Review by furszy — APPROVED** [review]
all good 👍 , we can tackle the next PRs in the list in another branch.

ACK 1c04a3500848fb3c7513cd352b7422b4b131f42d .

**Pull request merged**
