### PR TITLE
Squashed trading removal code

### PR DESCRIPTION
**Pull request by jonspock**

### CODE REVIEW

**Comment by Fuzzbawls** [comment]
Includes and code functions should probably also be removed, not much point in leaving them in place, wrapped around conditionals or not

**Comment by Mrs-X** [comment]
I agree, remove them so it's easy to isolate the remaining issues.
If we should ever want trading back we can just cherry-pick it from v2.1.7.

**Comment by Mrs-X** [comment]
Locally tested and works as ecpected 👍 

ACK

**Comment by PIVX-Project** [comment]
Ack

**Comment by presstab** [comment]
utACK

**Pull request merged**
