### PR TITLE
[Tests] Fix the unit test suite for use with PIVX

### PR DESCRIPTION
**Pull request by Fuzzbawls**
No *new* tests have been added, but a few have been disabled to prevent prolonging this PR's submission (Alert/Bloom/Miner tests).

Most of the code changes are confined to the `src/test` path, but there are a few minor changes to `src/` and `src/script`

After this is merged, automatic testing can be re-enabled in TravisCI via `make check`

### CODE REVIEW

**Comment by Mrs-X** [comment]
I've pulled your PR, re-enabled the tests for Travis and committed to my own repository.

Results: https://travis-ci.org/Mrs-X/PIVX/builds/235979522?utm_source=github_status&utm_medium=notification

When the issues are fixed (or the tests for the failing platforms were disabled, whatever you prefer) ping me and I'll let Travis do its job again...

**Edit:** all but the first build failed with a timeout, I've seen this before and as far as I remember you can't change this timeout with the free Travis account, so we might disable tests for those platforms.

Maybe you can check _which_ test causes the timeout and neither try to fix it / speed it up or selectively disable just this test.

**Comment by Fuzzbawls** [comment]
The timeouts are due to secondary RPC coverage tests that aren't part of this PR: https://github.com/PIVX-Project/PIVX/blob/master/.travis.yml#L72

The failures for arm and osx are because you changed the global `RUN_TESTS` var from false to true (RUN_TESTS should be false for arm and OSX due to environment limitations with cross builds).


I should have clarified that the `.travis.yml` file would need specific modification (namely comment out line 72 for the time being, and enable the tests on a per-build basis instead of globally)

**Comment by Mrs-X** [comment]
Okay, will try again.

**Comment by Mrs-X** [comment]
https://github.com/Mrs-X/PIVX/blob/Fuzzbawls-2017_unit_tests/.travis.yml#L18 
and
https://github.com/Mrs-X/PIVX/blob/Fuzzbawls-2017_unit_tests/.travis.yml#L72

Result: https://travis-ci.org/Mrs-X/PIVX/builds/236154773?utm_source=github_status&utm_medium=notification

I think it's
```
NioClientManager.handleKey: Successfully connected to localhost/127.0.0.1:13202
Peer.connectionOpened: Announcing to localhost/127.0.0.1:8333 as: /bitcoinj:0.12-SNAPSHOT/BlockAcceptanceComparisonTool:1.1/
```

8333 looks VERY bitcoinish...without looking at the test-code I guess nobody is listening on that port.

**Comment by jonspock** [comment]
ACK

**Comment by Fuzzbawls** [comment]
Added a couple more commits to satisfy Travis

**Comment by Mrs-X** [comment]
ACK
https://travis-ci.org/Mrs-X/PIVX/builds/236244343?utm_source=github_status&utm_medium=notification 👍 

Normally I'd say we squash before merging because that's a lot of commits, however they are all nicely labeled and it might be easier to track certain changes down in case we need to change something later.
What do you think?

**Comment by Fuzzbawls** [comment]
I would prefer to keep the commits in their current (atomic) state rather than squash them into one large and rather arbitrary "Fix unit tests" commit

**Comment by Mrs-X** [comment]
Okay, merging...

**Pull request merged**
