### PR TITLE
[Build] Update to latest leveldb

### LINKED ISSUE #534: Mac 10.13 warning: 'OSMemoryBarrier' is deprecated
### Describe the issue
When compiling for Mac, a warning....
```make
./port/atomic_pointer.h:55:3: warning: 'OSMemoryBarrier' is deprecated: first deprecated in macOS 10.12 - Use
      std::atomic_thread_fence() from <atomic> instead [-Wdeprecated-declarations]
  OSMemoryBarrier();
  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libkern/OSAtomicDeprecated.h:749:9: note: 
      'OSMemoryBarrier' has been explicitly marked deprecated here
void    OSMemoryBarrier( void );
```

May also want to look here where they deal with it https://github.com/google/leveldb/pull/422

#### If so, please list the steps to reproduce below:
1. autogen
2. configure
3. make!

### Expected behavior
No warnings...

### Actual behavior
Warnings

### Machine specs:
- OS: OSX 10.13

### PR DESCRIPTION
**Pull request by Fuzzbawls**
Switch to a git subtree for leveldb (similar to univalue and secp256k1)

This also fixes #534

### CODE REVIEW

**Comment by Mrs-X** [comment]
Since this is a huge PR, is it sufficient to run a Gitian build for all OSs to test it properly?

**Comment by Fuzzbawls** [comment]
build and unit tests are always good, but this one also needs extensive runtime testing with new and existing chain/wallet data.

**Comment by Mrs-X** [comment]
I'm starting to test this right now and will report back in a day or two...

**Comment by Mrs-X** [comment]
First result: ACK that it fixes https://github.com/PIVX-Project/PIVX/issues/534 There's still a million Qt-warnings, though. At least for Qt 5.4. And it's not our code.

**Pull request merged**
