### PR TITLE
[Cleanup] Remove Q_FOREACH, PAIRTYPE, and BOOST_REVERSE_FOREACH

### PR DESCRIPTION
**Pull request by Fuzzbawls**
Replaces ForEachMacros with native c++11 for loops and replaces the PARTYPE macro with `std::pair`

Most of the changes are scripted (scripts are in commit messages where applicable), with a few self-explanatory manual commits

### CODE REVIEW

**Review by furszy — DISMISSED** [review]
utACK d4942d6. 
It will possibly conflict with 1851, better to merge that one first.

Update: i didn't check that was already conflicting.. so, nvm.

**Comment by furszy** [comment]
rebase needed.

**Comment by Fuzzbawls** [comment]
rebased

**Review by furszy — APPROVED** [review]
utACK ec7417bd6d2e88c9ab002d1fc89c60aeafbd26f4

**Review by random-zebra — APPROVED** [review]
utACK ec7417bd6d2e88c9ab002d1fc89c60aeafbd26f4 and merging...

**Pull request merged**
