### PR TITLE
[RPC] Support for JSON-RPC named arguments

### PR DESCRIPTION
**Pull request by random-zebra**
The [JSON-RPC specification](http://www.jsonrpc.org/specification) allows either passing parameters as an Array, for positional arguments, or as an Object, for named arguments. Currently PIVX Core only supports positional arguments.

This pull request adds support for named arguments, but preserves full backwards compatibility. APIs using by-name arguments are easier to extend - as arguments can be left out - and easier to use - no need to guess which argument goes where.

This is especially nice in languages such as Python, which have native support for named arguments. Examples from the test:
```python
h = node.help(command='getinfo')
h = node.getblockhash(height=0)
h = node.getblock(hash=h)
```

Backported from:
- bitcoin#8811 : Add support for JSON-RPC named arguments _[W. J. van der Laan]_
- bitcoin#10084 : Rename first named arg of createrawtransaction _[MarcoFalke]_

### CODE REVIEW

**Comment by furszy** [comment]
needs rebase

**Comment by random-zebra** [comment]
> needs rebase

also reviews :)

There were a couple conflicts with #2308, merged only few hours ago. Fixed.

**Review by furszy — APPROVED** [review]
cool feature, ACK 9ed1bdd

**Comment by random-zebra** [comment]
It would be good to merge this PR before others that are introducing new RPC commands, or modifying existing ones (such as #2341, #2349, #2351, etc.).

**Review by Fuzzbawls — APPROVED** [review]
ACK 9ed1bddc1cb6c9363dbcbdd11c1de1eb9f21d07a

**Pull request merged**
