### PR TITLE
[Deployment] Windows taskbar icon pixelated fix.

### PR DESCRIPTION
**Pull request by furszy**
Windows taskbar icon pixelated (#1108), new icon created.

Thanks Rhubarbarian for the icon resource.

### CODE REVIEW

**Comment by Fuzzbawls** [comment]
copy the new icon file over to `src/qt/res/icons/bitcoin.ico` as well.

**Comment by furszy** [comment]
@Fuzzbawls instead of copy it, will change the `make_windows_icon.sh` pointing to a single location. No need to have the same file twice in our repository.

**Comment by Fuzzbawls** [comment]
@furszy the icon file at `src/qt/res/icons/` is the **application** icon used during the regular pivx-qt.exe build process.
the icon file at `share/pixmaps/` is the **installer** icon used when creating the windows installer package.

simply removing one or the other from the file tree leads to build/packaging errors.

**Comment by furszy** [comment]
I know.

It leaded to build/packaging errors if and only if the scripts that build/package the system are pointing to an inexistent file. I updated it to only look in the pixmaps directory and removed the file in the `res/icons` directory, check the changes in `make_windows_icon.sh`. It was the only script using it. 

No need to have the same file duplicated, it's the same icon.

**Pull request merged**
