### PR TITLE
accurate staking and masternode ROI

### PR DESCRIPTION
**Pull request by techy2**
accurate CLI function for staking and masternode ROI
getroi
{
  "3 hour avg ROI": "23.9%",
  "30 min stk ROI": "29.5%",
  "network  stake": "8,564,072",
  "--------------": "--------------",
  "masternode ROI": "16.0%",
  "tot collateral": "19,150,000",
  "enabled  nodes": "1915",
  "blocks per day": "1401.1"
}

### CODE REVIEW

**Review by panleone — COMMENTED** [review]
Thanks for the contribution, before doing a real review there is one thing that I don't understand in your logic:

```
arith_uint256 workDiff = csra.pb->nChainWork - csra.pb0->nChainWork;
...
int64_t networkHashPS = (int64_t)(workDiff.getdouble() / timeDiff);
```

Why are you assuming that `nChainWork` is a good measure of the number of hashes in the chain? 

It should be true in a PoW chain, but It's not clear to me why the same happens in a PoS chain.

Also please rebase the PR on master (so that the first 11 commits are removed)

**Comment by techy2** [comment]
With respect to the chainwork question, when PIVX implemented fixed slots, the amount of work done is discreet to each slot and directly proportional the the hash rate expressed as blocks per day since there is one slot per block. This is easily extracted  by formula. I will redo the PR, I have to look at what I submitted to PIVX as I recently made a slight revision and don't remember if that was included in my PIVX submission.

 I will redo the PR shortly as you request. have to finish a current project and then update my local PIVX repo.

**Comment by techy2** [comment]
updated to PR #2933, built against current master branch

**Comment by Duddino** [comment]
Superseded by #2933

**Pull request closed without merging**
