### PR TITLE
[Tests] Clean and lint the python regtest suite

### PR DESCRIPTION
**Pull request by Fuzzbawls**
Cleanup the python regtest suite to adhere to a number of flake8 standards and start linting the test suite in CI jobs.

This will, ultimately, lead to easier to read and more uniform test code.

Commits here have been made as atomic as possible in order to ease the review process given the relatively large number of files touched.

For reference only: this is a GA build job that shows the new `lint-python.sh` script returning an intentional error https://github.com/Fuzzbawls/PIVX/actions/runs/970753309

Still todo in separate PRs in the future: update/cleanup any python files to also adhere to / pass mypy inspections, enforce python 3.6 as a minimum requirement (python 3.5 was EOL'd in September 2020), and extend the python linting to python scripts outside the regtest suite.

### CODE REVIEW

**Comment by Fuzzbawls** [comment]
rebased to resolve conflicts and fix an issue introduced in #2410

**Review by random-zebra — CHANGES_REQUESTED** [review]
This needs rebase.
Aside from that, noticed that the first commit introduces a bunch of changes, regarding import ordering, that are going in the wrong direction (I haven't  commented them all).
According  to [PEP8 styling guideline](https://www.python.org/dev/peps/pep-0008/#imports), and our own comment in `example_test.py`:

```
Imports are always put at the top of the file, just after any module comments and docstrings, 
and before module globals and constants.

Imports should be grouped in the following order:

1. Standard library imports.
2. Related third party imports.
3. Local application/library specific imports.

You should put a blank line between each group of imports.

**Comment by Fuzzbawls** [comment]
rebased and fixed the first commit to do imports in the popper order for all test suite files.

**Review by random-zebra — APPROVED** [review]
ACK 1a15dc478dc2aa1ca9b4860995a9989ba9039697

**Review by furszy — APPROVED** [review]
ACK 1a15dc478dc2aa1ca9b4860995a9989ba9039697 and merging..

The TODO in `wallet_multiwallet.py` is already covered by #2423.

**Pull request merged**
