### PR TITLE
[Doc] v5.2.0 Release Notes

### PR DESCRIPTION
**Pull request by furszy**
Finalized release notes for v5.2.0.

### CODE REVIEW

**Comment by furszy** [comment]
Added merged 2440 and 2441. Ready to go.

**Comment by furszy** [comment]
Added #2450 so this can get merged right after #2450.

**Review by random-zebra — APPROVED** [review]
utACK feba6061d46bbd5e8b47158ec708ed9a4e3f91c2

**Review by Fuzzbawls — APPROVED** [review]
utACK feba6061d46bbd5e8b47158ec708ed9a4e3f91c2

**Pull request merged**
