### PR TITLE
[GUI] Periodic make translate

### PR DESCRIPTION
**Pull request by Fuzzbawls**
Doing this for `master` branch as a precursor to a couple other translation related PRs in order to reduce the diff complexity

### CODE REVIEW

**Review by furszy — DISMISSED** [review]
utACK 3607d5d45e04518727205564188aa1987945d4b6

**Comment by Fuzzbawls** [comment]
rebased on master to pull in the most recent translation changes.

would like to get this merged sooner rather than later in order to ease the review of follow-up translation-related PRs.

**Review by random-zebra — APPROVED** [review]
utACK c3ed97a3d63e34be224c021a6cfb17b8ad482d48

**Review by furszy — APPROVED** [review]
utACK c3ed97a and merging..

**Pull request merged**
