### PR TITLE
[Wallet] Masternode config check: wallet must be enabled

### LINKED ISSUE #158: [Wallet] Segmentation fault on masternode with --disablewallet
### Describe the issue
Executing pivxd with options like `masternode=1 disablewallet=1` causes a segmentation fault with no useful debug output.

#### If so, please list the steps to reproduce below:
1. Add `disablewallet=1` to otherwise valid masternode configuration.
2. Run pivxd.

### Expected behavior
Program should throw InitError with useful troubleshooting information for user.

### Actual behavior
Segmentation fault.

### What version of PIVX Core are you using?
Self-compiled master commit id 41fdeaa

### Machine specs:
- OS: Tested on Debian, CentOS, and Arch Linux

### Any extra information that might be useful in the debugging process.
See my PR for a proposed fix.

### PR DESCRIPTION
**Pull request by AaronM-Cloudtek**
Fixes #158

Adds a check to init.cpp which verifies that wallet support is compiled
and enabled for masternodes.

### CODE REVIEW

**Comment by Fuzzbawls** [comment]
utACK

However, a Nit: the returned message doesn't get translated into the user's language.

There are a lot of inconsistencies with what gets translated and what doesn't. This is something that I think needs discussion, and can certainly be done at a later time AFTER this is merged as is to prevent this from being held up longer than it needs to be right now.

**Comment by Mrs-X** [comment]
Nice find 👍 

But, NACK.

The check is incomplete, you only check for `GetBoolArg("-masternode", false);` (that means, the masternodes was configured in pivx.conf).
You can also run a masternode configured via masternode.conf. For this you have to check `masternodeConfig.getCount()` as well (that's actually the preferred way, upstream completely removed masternode configuration outside masternode.conf somewhere in the past).

Besides this, I fear that you're only hiding the symptoms and not curing the cause for that segfault.
Did you debug down to the point where the segfault actually happens? I ask because I can't remember any reason why a masternode shouldn't run without wallet (this doesn't necessarily mean there isn't one, that's what we would need to find out).

Feel free to ping me if you should need help.

**Comment by AaronM-Cloudtek** [comment]
Thanks @Mrs-X you are absolutely correct. I was assuming the wallet is required but it's not.

[Here's a backtrace of the segfault](https://paste.ee/p/WPWyL). ThreadStakeMinter is the culprit which is invoked at https://github.com/PIVX-Project/PIVX/blob/master/src/net.cpp#L1603

Aha, so `-staking` is enabled by default and the real incompatibility is with it and `-disablewallet`. Which does make a lot more sense. I confirmed this by adding `staking=0` to my masternode config and now it runs fine with the wallet disabled.

So I'm thinking I should update this PR, replacing the previous changes with a check for the actual incompatible configuration: staking enabled with wallet functionality disabled or not compiled.

Also I'd like to add documentation for the `-staking` option to init.cpp::HelpMessage() as it is missing. Suggestions on how that should be worded would be helpful.

Thoughts?

**Comment by Fuzzbawls** [comment]
closing in favor of an alternate solution that isn't as strict.

**Pull request closed without merging**
