### PR TITLE
[UI] Complete re-design of Qt-wallet

### PR DESCRIPTION
**Pull request by Mrs-X**
Since there are way too much changes to be documented with screen-shots you have to build the wallet yourself to see all the finer details.

**------------------------------------------------------------------------------------------------------------------------**
**Edit:** for your convenience, and because it's Christmas time, here's the link to some prebuild binaries for testing.
Use at your own risk:
http://178.254.23.111/~pub/PIVX/temp/downloads/2017-12-23/pivx-3.0.99-osx-unsigned.dmg
http://178.254.23.111/~pub/PIVX/temp/downloads/2017-12-23/pivx-3.0.99-win64.zip
http://178.254.23.111/~pub/PIVX/temp/downloads/2017-12-23/pivx-3.0.99-x86_64-linux-gnu.tar.gz
**------------------------------------------------------------------------------------------------------------------------**

To give you an idea what to expect, here's the new overview page in all its glory:
overview-1

**Note:** to resolve merging conflicts early (I had to change almost all UI-related files after all) I merged the master branch regularly into my working branch.

As I know NOW, this was a bad idea, as squashing all of my commits into a single one is almost impossible, at least not in reasonable time and without messing up the commit history.

So, as long as no git-wizzard shows up who knows how to do this, we have to merge this PR without squashing.
Sorry about that....

### CODE REVIEW

**Comment by Warrows** [comment]
About the git situation, you could use the --squash option with merge. I believe the github interface offers it but I never used it myself https://help.github.com/articles/about-pull-request-merges/

**Comment by Mrs-X** [comment]
@Warrows thanks 👍 , but that only works if you have consecutive commits as described in the example you've linked to.
What we have here:
```
master  A -> B -> C -> D -> E -> F -> G -> H ...
                  |    |---------  
                   ---------     |
                            |    |
feature A -> B -> U -> V -> C -> D -> W -> ...
```
I know how it _could_ be done (reset my branch to  master, revert the back then needed merge-conflict changes (which would mean patching them by hand out of my changes), add all changed files again, resolve all the merging conflicts again, ...) but I didn't find a documentation which covers this scenario and is doable in reasonable time.
We had the same problem back when we merged the Zerocoin development branch, and after some discussions and trial and error we decided to just leave most of those commits.

Oh, and for future reference, we don't use the Gihub interface for merging, we use https://github.com/PIVX-Project/PIVX/blob/master/contrib/devtools/github-merge.py because it tests the build and allows signing of the merging commit and some other nice stuff...

**Comment by Warrows** [comment]
Ah yes, my bad, I went through the article way too fast. There is git rerere which could be useful to replay the merging conflicts. But it has to be activated before doing it the first time... You might want to check this article if you have it enabled: https://hackernoon.com/fix-conflicts-only-once-with-git-rerere-7d116b2cec67

**Comment by Mrs-X** [comment]
No more reviews -> I'll merge it as it is.

People will find things to complain anyway ;-)

**Pull request merged**
