### PR TITLE
[Cleanup] Remove zerocoin wallet

### PR DESCRIPTION
**Pull request by random-zebra**
Keep going with the zerocoin cleanup.
This time:
- RPC
- wallet
- tracker
- unit tests
- supply map
- init flags

Based on top of
- [x] #1983 

To be merged **after** zerocoin-maintenance has been activated via spork on main net.

### CODE REVIEW

**Comment by random-zebra** [comment]
Rebased on master. Ready to be reviewed & merged (zPIV deactivated on both test-net and main-net).

**Comment by furszy** [comment]
thanks for the division, reviewing again.

**Review by Fuzzbawls — APPROVED** [review]
ACK e6ca43bd93a097ee8cdb67e8f0f74b933c16fd04

**Review by furszy — APPROVED** [review]
ACK e6ca43bd93a097ee8cdb67e8f0f74b933c16fd04 .

Nice first step 👍 . Will definitely not miss all of this code..

**Pull request merged**
