### PR TITLE
[Refactoring] Budget, round 7: split masternode-budget files

### PR DESCRIPTION
**Pull request by random-zebra**
Based on top of 
- [x] #1861 

Final round for this first cleanup of the budget classes.
MOVE-ONLY commits. Split masternode-budget.h/.cpp in single files inside the `budget` subdir:
- `budget/budgetdb.*` (CBudgetDB)
- `budget/budgetmanager.*` (CBudgetManager)
- `budget/budgetproposal.*` (CBudgetProposal)
- `budget/budgetvote.*` (CBudgetVote)
- `budget/finalizedbudget.*` (CFinalizedBudget)
- `budget/finalizedbudgetvote.*` (CFinalizedBudgetVote)

### CODE REVIEW

**Comment by furszy** [comment]
Final round 🚜 , needs rebase :)

**Comment by random-zebra** [comment]
Rebased.

**Comment by Fuzzbawls** [comment]
needs another rebase

**Comment by random-zebra** [comment]
Rebased again. Please let's get this merged before other updates to the budget code.

**Review by furszy — APPROVED** [review]
looking good, utACK c7051e7

**Review by Fuzzbawls — APPROVED** [review]
ACK c7051e71175fcae30ea40cfeb1419979ff4bc645

**Pull request merged**
