### PR TITLE
[Trivial] constant functions in SaplingScriptPubKeyMan

### PR DESCRIPTION
**Pull request by random-zebra**
Fix some class function not marked `const`.
Also add a brief description for the class (removing another todo left there).

### CODE REVIEW

**Review by furszy — APPROVED** [review]
Needs rebase, otherwise utACK d137288

**Comment by random-zebra** [comment]
Rebased.

**Review by furszy — APPROVED** [review]
ACK 9f94d489b944e0a6b81f7239e59a8b8c0074cbe7

**Review by Fuzzbawls — APPROVED** [review]
utACK 9f94d489b944e0a6b81f7239e59a8b8c0074cbe7

**Pull request merged**
