### PR TITLE
Squash valgrind warnings for groestl by initing array

### PR DESCRIPTION
**Pull request by jonspock**

### CODE REVIEW

**Comment by PIVX-Project** [comment]
Ack

**Comment by presstab** [comment]
I still get this in groestl:
`
==5245== Use of uninitialised value of size 8
==5245==    at 0x62E003: groestl_big_core (in /home/pt/workspace/pivx/src/pivxd)
==5245==    by 0x630F9E: groestl_big_close (groestl.c:2996)
==5245==    by 0x5C2784: uint256 HashQuark<char*>(char*, char*) (hash.h:304)
==5245==    by 0x5F45BD: GetHash (spork.h:82)
==5245==    by 0x5F45BD: ProcessSpork(CNode*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, CDataStream&) (spork.cpp:39)
==5245==    by 0x4A382C: ProcessMessage(CNode*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, CDataStream&, long) (main.cpp:5566)
==5245==    by 0x4A3EBF: ProcessMessages(CNode*) (main.cpp:5659)
==5245==    by 0x4ECAC2: operator() (function_template.hpp:773)
==5245==    by 0x4ECAC2: m_invoke<bool, boost::function<bool(CNode*)>, 0u, CNode*&> (variadic_slot_invoker.hpp:87)
==5245==    by 0x4ECAC2: operator()<boost::function<bool(CNode*)>, CNode*&, 1ul> (variadic_slot_invoker.hpp:81)
==5245==    by 0x4ECAC2: m_invoke<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool(CNode*), boost::function<bool(CNode*)> >, boost::signals2::mutex> > > (variadic_slot_invoker.hpp:132)
==5245==    by 0x4ECAC2: operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool(CNode*), boost::function<bool(CNode*)> >, boost::signals2::mutex> > > (variadic_slot_invoker.hpp:120)
==5245==    by 0x4ECAC2: dereference (slot_call_iterator.hpp:82)
==5245==    by 0x4ECAC2: dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<bool, CNode*>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool(CNode*), boost::function<bool(CNode*)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool(CNode*), boost::function<bool(CNode*)> >, boost::signals2::mutex> > > (iterator_facade.hpp:540)
==5245==    by 0x4ECAC2: operator* (iterator_facade.hpp:646)
==5245==    by 0x4ECAC2: operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<bool, CNode*>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool(CNode*), boost::function<bool(CNode*)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool(CNode*), boost::function<bool(CNode*)> >, boost::signals2::mutex> > > (optional_last_value.hpp:34)
==5245==    by 0x4ECAC2: operator()<boost::signals2::optional_last_value<bool>, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<bool, CNode*>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool(CNode*), boost::function<bool(CNode*)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool(CNode*), boost::function<bool(CNode*)> >, boost::signals2::mutex> > > (result_type_wrapper.hpp:53)
==5245==    by 0x4ECAC2: operator() (signal_template.hpp:246)
==5245==    by 0x4ECAC2: operator() (signal_template.hpp:718)
==5245==    by 0x4ECAC2: ThreadMessageHandler() (net.cpp:1368)
==5245==    by 0x4FA0E7: void TraceThread<void (*)()>(char const*, void (*)()) (util.h:229)
==5245==    by 0x54E55D4: ??? (in /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0)
==5245==    by 0x6E356B9: start_thread (pthread_create.c:333)
==5245==    by 0x715182C: clone (clone.S:109)
`

**Comment by presstab** [comment]
Concept ACK, but anything that touches hashing code should require a test resync before getting ACK. I will give this a test sync soon.

**Comment by jonspock** [comment]
I did do a full resync, but then changed it again

**Comment by presstab** [comment]
Synced. ACK.

**Pull request merged**
