### PR TITLE
[Docs] OSX Build - Instructions on how to make the Homebrew OpenSSL headers visible

### PR DESCRIPTION
**Pull request by gpdionisio**

### CODE REVIEW

**Comment by Warrows** [comment]
I am using neither Homebrew or OSX. So I am curious, what's happening if you don't export those two variables ?

**Comment by gpdionisio** [comment]
On newer versions of OSX you could get
```
checking for libssl... yes
checking for libcrypto... yes
checking for protobuf... yes
checking for libqrencode... no
checking for libevent... yes
checking for libevent_pthreads... yes
checking for libzmq >= 4... yes
checking for RAND_egd in -lcrypto... yes
checking openssl/ec.h usability... no
checking openssl/ec.h presence... no
checking for openssl/ec.h... no
configure: error: OpenSSL ec header missing
```
during the `./configure`

**Comment by Warrows** [comment]
Okay. And what is the OpenSSL version? If 1.1+ do you get the warning about it being unsupported and consensus risky ?

**Comment by gpdionisio** [comment]
Nope. tested only with `OpenSSL 1.0.2j`

**Comment by Mrs-X** [comment]
Thanks. 
Please squash the commits to a single one.

**Pull request merged**
