### PR TITLE
[RPC] Convert source tree from json_spirit to UniValue

### PR DESCRIPTION
**Pull request by Fuzzbawls**
Rather that continue to use both json_spirit AND UniValue in tandem,
which is redundant and highly inefficient, switch over all the
RPC functions to UniValue and get rid of json_spirit.

- [x] Remove old json_spirit source files
- [x] Convert existing rpc functions to UniValue
- [x] Convert existing test files to UniValue (even though tests may still fail)
- [x] Update included UniValue to a subtree
- [x] Incorporate updated UniValue into the build system

### CODE REVIEW

**Comment by PIVX-Project** [comment]
utACK

**Comment by presstab** [comment]
NACK. Too many changes, this should be held to the side until zerocoin is merged and then merged after that.

**Comment by Fuzzbawls** [comment]
i'm ok waiting on this until later, it is complete but will just need rebasing to resolve any future merge conflicts.

**Comment by jonspock** [comment]
Sounds good. Love to see this stuff getting done. I presume it brings us closer to latest Bitcoin too. But agree better to rebase later to avoid merge issues with Zerocoin code

**Comment by Fuzzbawls** [comment]
needs rebasing now

**Comment by Fuzzbawls** [comment]
Rebased on top of the current `master` branch now

Some Notes:
1) `emplace_back()` has been replaced with `push_back()` as UniValue doesn't recognize the former (which was really just being used as a pseudonym for exactly how `push_back()` was being used).
2) Functional tests for **ALL** RPC commands will need to be done manually.
3) This is a precursor to a number of other core updates.

**Comment by presstab** [comment]
@Fuzzbawls I am working on backporting an RPC commit from dash. I notice that many of the univalue methods don't seem to be present in the current codebase, for example `get_str()`. I was trying to use univalue, but think it may be cleaner just to use jsonrpc lib and then port over after this is merged. Thoughts?

**Comment by Fuzzbawls** [comment]
@presstab `get_str()` should be in both json_spirit (old lib) and UniValue (new lib). Up to you on wither or not you want to base your PR off of json_spirit (current `master`) or base it on top of this PR.

I'm not too keen on the idea of rebasing this PR yet again though, but whatever works.

**Comment by presstab** [comment]
Behaves as expected for me. ACK

**Pull request merged**
