### PR TITLE
[UI] Edit masternode.conf in Qt-wallet

### PR DESCRIPTION
**Pull request by Mrs-X**
Subject says it all.
mn-edit

### CODE REVIEW

**Comment by presstab** [comment]
Will this instantly apply the updated settings or will it require a restart?

**Comment by jonspock** [comment]
utACK

**Comment by Mrs-X** [comment]
@presstab Like changed wallet settings changed masternode settings need a restart to apply.

**Comment by Fuzzbawls** [comment]
@Mrs-X can you post a screenshot of the button's position in the information panel of the tools window?

**Comment by presstab** [comment]
utACK

**Comment by Mrs-X** [comment]
> can you post a screenshot of the button's position in the information panel of the tools window?

@Fuzzbawls I'm a bit confused on what you want which isn't covered in the screenshot above.

**Comment by PIVX-Project** [comment]
Ack

**Pull request merged**
