### PR TITLE
[Refactoring] [Move Only] Move wallet files into their own folder

### PR DESCRIPTION
**Pull request by Warrows**
Backport of https://github.com/bitcoin/bitcoin/pull/5745
Improves the source file structure.
Also allows for easier backports.

This is a simple move of files. This does not contain any technical change.

### CODE REVIEW

**Comment by Mrs-X** [comment]
Testing the builds: ACK

One nit: in my opinion `zpivwallet.*` should also go into the wallet folder, will you do that or shall I do it?

**Comment by Fuzzbawls** [comment]
Concept ACK, but let’s hold off on merging until after 3.2.0 is branched

**Comment by Warrows** [comment]
@Mrs-X If I'm not mistaken, `zpivwallet` and his friends are scheduled to move to a `zpiv` folder with the introduction of precomputing.

**Comment by Fuzzbawls** [comment]
needs rebase

**Comment by Warrows** [comment]
Rebased.

**Pull request merged**
