### PR TITLE
[GUI] Customizable sorting for address books

### LINKED ISSUE #1038: [GUI] sort addresses in addressbook
Contacts / Receive tab --> My Addresses:

Entries are sorted alphabetically by address string which is not very useful.
Make them sortable either by label and/or creation date.

### PR DESCRIPTION
**Pull request by random-zebra**
This adds GUI controls and relative logic to sort the addresses saved in the wallet and presented to the user. 
Interested views:
- Receive --> My Addresses
- Cold Staking --> My Cold Staking Addresses
- Contacts
- Send / Delegate --> recipient dropdown

Addresses can now be sorted (ascending or descending order):
- by label (default)
- by address
- by creation date.

Closes #1038 .

---

For "receive" addresses and own "cold-staking" addresses, the controls are hidden with the list, and show up when the relative button is pressed:
<br>

sort_addys_1b

---

<br>
For "contacts" the controls are visible next to the title
<br>

sort_addys_2

---

<br>
For the dropdown in the "send" widget, instead, a fixed by-label ascending order is used (adding controls for customization here would be probably useless and only make the the space overcrowded).
<br>

sort_addys_3

---
<br>

Note: currently based on top of:
- [x] #1385 

The present diff starts with the second commit.

### CODE REVIEW

**Comment by random-zebra** [comment]
Rebased now that #1385 has been merged.

**Comment by random-zebra** [comment]
Rebased, and added release notes.

**Comment by random-zebra** [comment]
Rebased.

**Comment by random-zebra** [comment]
Rebased

**Comment by random-zebra** [comment]
Good catch @Fuzzbawls . Fixed.

**Comment by furszy** [comment]
Nice work. Code wise looking good, have been testing it and find some stuff.

Design wise:

* Will be good to remove the "Sort:" subtitle. Receive widget, contacts and cold staking screen. It doesn't look good and it doesn't clarify anything. Plus, when the wallet gets expanded, the subtitle end ups being really far from the combobox that it's supposedly describing.
What could help there instead is a tooltip over the combobox describing the filter action (could be coded in `qtutils`:`fillAddressSortControls` once and it will be used in every place).

* Decrease the space between the receive widget comboboxes and the addresses list by 4px.

* In contacts, the comboboxes text need to be in the same line as the screen subtitle. Currently those are few px above the line.

* In cold staking, the space between the comboboxes and the expandable button is too big, need to decrease it to be at the same distance as the receive widget screen.

* In cold staking, the space between the comboboxes and the addresses list is too large, need to decrease it to be at the same distance as the receive widget screen.

Functional:

In the receive list, the sort "by label" will show first the addresses with no label when it should be in the other way around, independently on the sort order, the addresses with no label should appear at the bottom of the list.

**Comment by random-zebra** [comment]
Removed the "Sort:" subtitle and adjusted margins as per request.

Didn't add tooltips to keep consistency with the combo boxes in the overview page.
Also they seem to have a minor issue, where, on hovering too fast, the length isn't  calculated properly and the text results cropped. When this minor bug is fixed, we can add them consistently in all combo boxes.

> independently on the sort order, the addresses with no label should appear at the bottom of the list.

when the label is not set, a default `(no label)` is assigned.
`QT::AscendingOrder` is locale-dependent: in Latin-1 (ISO-8859-1) the `(` character is **0x28**, thus comes before the `A` character, which is **0x41**.
This results in it being placed at the beginning. I don't think it's worth to add a different logic to handle these cases.

This fixes the current situation of having the addresses being basically in a random order (making the search for one of them a huge pain in the arse, if you have more than a few).
If we want to add  a specific logic for `(no label)` addresses, it can be done in a subsequent PR.
Same goes for eventual other visual/placement nitpicking imo.

**Pull request merged**
