### PR TITLE
[WIP] [Qt] Add QRCode scanning functionality to the GUI

### PR DESCRIPTION
**Pull request by Fuzzbawls**
Typing addresses and/or private keys is a PITA, and can lead to mistakes or even loss of funds. Copy/Paste is an established workaround, but falls short when dealing with cross medium data, such as paper wallets or the mobile wallets which both use QRCode images heavily.

The Core wallet has, for a long time, supported the generation of QRCode images, but has never had a way to scan/import data contained in a QRCode. This PR aims to establish such baseline functionality.

I have also done some UI element/layout cleanup in the places that I added this feature, most notably is standardizing the QToolButton styles across the entire UI, and re-arranging the zPIV spend portion of the Privacy UI.

See individual commit messages for details.

For the time being, this will **NOT** be compiled in with gitian, as additional support for QtMultimedia will need to be written.

Per-platform Functionality Checklist:
- [x] MacOS: Uses AVFoundation Backend
- [ ] Windows: Needs static linking of DSService
- [ ] Linux: Needs static linking of GStreamer

pivx-qrscan-bip38-valid
pivx-qrscan-payto-invalid
pivx-qrscan-payto-valid
pivx-qrscan-zpiv-invalid
pivx-qrscan-zpiv-valid

### CODE REVIEW

**Comment by Mrs-X** [comment]
I don't have a webcam, so someone else has to test this.

**Comment by Fuzzbawls** [comment]
@rejectedpromise reached the global timeout on one of the windows builds. will probably remove the last commit.

**Comment by Fuzzbawls** [comment]
Demoting this to `[WIP]` for the time being so I can solidify the functionality/performance across multiple platforms.

**Comment by Fuzzbawls** [comment]
I've pulled a number of non-QRScan refactors and updates into their own PR (#537). While the functionality of getting the core wallet to support QRCode Scanning is still something I'll be working on, It won't be a priority for the time being and I didn't want the unrelated changes to be held back.

Going to keep this open and tagged `[WIP]` still.

**Comment by Fuzzbawls** [comment]
Closing this for the time being. Will re-open when I have more time to work on it.

**Pull request closed without merging**
