### PR TITLE
[Backport] 5.2.0 cs backports

### PR DESCRIPTION
**Pull request by random-zebra**
Backports #2258 and #2428

### CODE REVIEW

**Review by furszy — APPROVED** [review]
code review ACK 3698900a42cd082660dc5e4eceeb315ac7b093a3.

**Comment by random-zebra** [comment]
Rebased on 5.2 to run updated GA jobs.

**Review by furszy — APPROVED** [review]
re code-ACK 62bf095

**Review by Fuzzbawls — APPROVED** [review]
utACK 62bf09573b082d51eb1c5b5be9053a0fe3752958

**Pull request merged**
