### PR TITLE
cleanup: IsBlockValueValid refactored properly. 

### PR DESCRIPTION
**Pull request by furszy**
Cleaned `IsBlockValueValid` method to be much more readable, plus removed a not needed chainActive access.

### CODE REVIEW

**Review by random-zebra — APPROVED** [review]
utACK 6513fe16701e5288bab2f0c2b07067531a97ffc9

**Review by Fuzzbawls — APPROVED** [review]
utACK 6513fe16701e5288bab2f0c2b07067531a97ffc9

**Comment by random-zebra** [comment]
Needs  rebase

**Comment by furszy** [comment]
rebased

**Review by random-zebra — APPROVED** [review]
re-utACK ed117ab2f34135a9718941f7423a5bade2db8192 and merging...

**Pull request merged**
